# warp.config.yml — build configuration

exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/capabilities": "src/api/capabilities/index.ts"
  "./api/transparentDataEncryptions": "src/api/transparentDataEncryptions/index.ts"
  "./api/sqlAgent": "src/api/sqlAgent/index.ts"
  "./api/serverAutomaticTuning": "src/api/serverAutomaticTuning/index.ts"
  "./api/serverAdvancedThreatProtectionSettings": "src/api/serverAdvancedThreatProtectionSettings/index.ts"
  "./api/managedLedgerDigestUploads": "src/api/managedLedgerDigestUploads/index.ts"
  "./api/managedInstancePrivateLinkResources": "src/api/managedInstancePrivateLinkResources/index.ts"
  "./api/managedInstanceAdvancedThreatProtectionSettings": "src/api/managedInstanceAdvancedThreatProtectionSettings/index.ts"
  "./api/managedDatabaseTransparentDataEncryption": "src/api/managedDatabaseTransparentDataEncryption/index.ts"
  "./api/managedDatabaseRestoreDetails": "src/api/managedDatabaseRestoreDetails/index.ts"
  "./api/managedDatabaseQueries": "src/api/managedDatabaseQueries/index.ts"
  "./api/managedDatabaseMoveOperations": "src/api/managedDatabaseMoveOperations/index.ts"
  "./api/managedDatabaseAdvancedThreatProtectionSettings": "src/api/managedDatabaseAdvancedThreatProtectionSettings/index.ts"
  "./api/maintenanceWindows": "src/api/maintenanceWindows/index.ts"
  "./api/maintenanceWindowOptions": "src/api/maintenanceWindowOptions/index.ts"
  "./api/ledgerDigestUploads": "src/api/ledgerDigestUploads/index.ts"
  "./api/usages": "src/api/usages/index.ts"
  "./api/elasticPoolOperations": "src/api/elasticPoolOperations/index.ts"
  "./api/managedInstanceTdeCertificates": "src/api/managedInstanceTdeCertificates/index.ts"
  "./api/managedDatabaseRecommendedSensitivityLabels": "src/api/managedDatabaseRecommendedSensitivityLabels/index.ts"
  "./api/managedDatabaseSecurityEvents": "src/api/managedDatabaseSecurityEvents/index.ts"
  "./api/dataWarehouseUserActivities": "src/api/dataWarehouseUserActivities/index.ts"
  "./api/dataMaskingRules": "src/api/dataMaskingRules/index.ts"
  "./api/databaseVulnerabilityAssessmentScans": "src/api/databaseVulnerabilityAssessmentScans/index.ts"
  "./api/databaseSqlVulnerabilityAssessmentScans": "src/api/databaseSqlVulnerabilityAssessmentScans/index.ts"
  "./api/sqlVulnerabilityAssessmentRuleBaselines": "src/api/sqlVulnerabilityAssessmentRuleBaselines/index.ts"
  "./api/sqlVulnerabilityAssessmentExecuteScan": "src/api/sqlVulnerabilityAssessmentExecuteScan/index.ts"
  "./api/databaseSqlVulnerabilityAssessmentExecuteScan": "src/api/databaseSqlVulnerabilityAssessmentExecuteScan/index.ts"
  "./api/databaseSqlVulnerabilityAssessmentsSettings": "src/api/databaseSqlVulnerabilityAssessmentsSettings/index.ts"
  "./api/sqlVulnerabilityAssessmentBaselines": "src/api/sqlVulnerabilityAssessmentBaselines/index.ts"
  "./api/databaseSqlVulnerabilityAssessmentBaselines": "src/api/databaseSqlVulnerabilityAssessmentBaselines/index.ts"
  "./api/databaseRecommendedActions": "src/api/databaseRecommendedActions/index.ts"
  "./api/databaseExtensions": "src/api/databaseExtensions/index.ts"
  "./api/databaseAutomaticTuning": "src/api/databaseAutomaticTuning/index.ts"
  "./api/databaseAdvisors": "src/api/databaseAdvisors/index.ts"
  "./api/databaseAdvancedThreatProtectionSettings": "src/api/databaseAdvancedThreatProtectionSettings/index.ts"
  "./api/tdeCertificates": "src/api/tdeCertificates/index.ts"
  "./api/serverUsages": "src/api/serverUsages/index.ts"
  "./api/serverOperations": "src/api/serverOperations/index.ts"
  "./api/synapseLinkWorkspaces": "src/api/synapseLinkWorkspaces/index.ts"
  "./api/recommendedSensitivityLabels": "src/api/recommendedSensitivityLabels/index.ts"
  "./api/databaseUsages": "src/api/databaseUsages/index.ts"
  "./api/databaseOperations": "src/api/databaseOperations/index.ts"
  "./api/databaseEncryptionProtectors": "src/api/databaseEncryptionProtectors/index.ts"
  "./api/managedDatabaseSensitivityLabels": "src/api/managedDatabaseSensitivityLabels/index.ts"
  "./api/workloadGroups": "src/api/workloadGroups/index.ts"
  "./api/workloadClassifiers": "src/api/workloadClassifiers/index.ts"
  "./api/virtualNetworkRules": "src/api/virtualNetworkRules/index.ts"
  "./api/virtualClusters": "src/api/virtualClusters/index.ts"
  "./api/timeZones": "src/api/timeZones/index.ts"
  "./api/syncMembers": "src/api/syncMembers/index.ts"
  "./api/syncGroups": "src/api/syncGroups/index.ts"
  "./api/syncAgents": "src/api/syncAgents/index.ts"
  "./api/subscriptionUsages": "src/api/subscriptionUsages/index.ts"
  "./api/startStopManagedInstanceSchedules": "src/api/startStopManagedInstanceSchedules/index.ts"
  "./api/serverVulnerabilityAssessments": "src/api/serverVulnerabilityAssessments/index.ts"
  "./api/serverTrustCertificates": "src/api/serverTrustCertificates/index.ts"
  "./api/serverSecurityAlertPolicies": "src/api/serverSecurityAlertPolicies/index.ts"
  "./api/serverKeys": "src/api/serverKeys/index.ts"
  "./api/serverDnsAliases": "src/api/serverDnsAliases/index.ts"
  "./api/serverDevOpsAuditSettings": "src/api/serverDevOpsAuditSettings/index.ts"
  "./api/serverConnectionPolicies": "src/api/serverConnectionPolicies/index.ts"
  "./api/serverConfigurationOptions": "src/api/serverConfigurationOptions/index.ts"
  "./api/serverAzureADOnlyAuthentications": "src/api/serverAzureADOnlyAuthentications/index.ts"
  "./api/serverAzureADAdministrators": "src/api/serverAzureADAdministrators/index.ts"
  "./api/restorableDroppedManagedDatabases": "src/api/restorableDroppedManagedDatabases/index.ts"
  "./api/restorableDroppedDatabases": "src/api/restorableDroppedDatabases/index.ts"
  "./api/recoverableManagedDatabases": "src/api/recoverableManagedDatabases/index.ts"
  "./api/recoverableDatabases": "src/api/recoverableDatabases/index.ts"
  "./api/privateLinkResources": "src/api/privateLinkResources/index.ts"
  "./api/privateEndpointConnections": "src/api/privateEndpointConnections/index.ts"
  "./api/outboundFirewallRules": "src/api/outboundFirewallRules/index.ts"
  "./api/networkSecurityPerimeterConfigurations": "src/api/networkSecurityPerimeterConfigurations/index.ts"
  "./api/managedServerSecurityAlertPolicies": "src/api/managedServerSecurityAlertPolicies/index.ts"
  "./api/managedServerDnsAliases": "src/api/managedServerDnsAliases/index.ts"
  "./api/managedInstanceVulnerabilityAssessments": "src/api/managedInstanceVulnerabilityAssessments/index.ts"
  "./api/managedInstancePrivateEndpointConnections": "src/api/managedInstancePrivateEndpointConnections/index.ts"
  "./api/managedInstanceOperations": "src/api/managedInstanceOperations/index.ts"
  "./api/managedInstanceLongTermRetentionPolicies": "src/api/managedInstanceLongTermRetentionPolicies/index.ts"
  "./api/managedInstanceKeys": "src/api/managedInstanceKeys/index.ts"
  "./api/managedInstanceEncryptionProtectors": "src/api/managedInstanceEncryptionProtectors/index.ts"
  "./api/managedInstanceDtcs": "src/api/managedInstanceDtcs/index.ts"
  "./api/managedInstanceAzureADOnlyAuthentications": "src/api/managedInstanceAzureADOnlyAuthentications/index.ts"
  "./api/managedInstanceAdministrators": "src/api/managedInstanceAdministrators/index.ts"
  "./api/managedDatabaseSecurityAlertPolicies": "src/api/managedDatabaseSecurityAlertPolicies/index.ts"
  "./api/managedRestorableDroppedDatabaseBackupShortTermRetentionPolicies": "src/api/managedRestorableDroppedDatabaseBackupShortTermRetentionPolicies/index.ts"
  "./api/managedBackupShortTermRetentionPolicies": "src/api/managedBackupShortTermRetentionPolicies/index.ts"
  "./api/longTermRetentionPolicies": "src/api/longTermRetentionPolicies/index.ts"
  "./api/longTermRetentionManagedInstanceBackups": "src/api/longTermRetentionManagedInstanceBackups/index.ts"
  "./api/longTermRetentionBackups": "src/api/longTermRetentionBackups/index.ts"
  "./api/jobVersions": "src/api/jobVersions/index.ts"
  "./api/jobTargetGroups": "src/api/jobTargetGroups/index.ts"
  "./api/jobSteps": "src/api/jobSteps/index.ts"
  "./api/jobPrivateEndpoints": "src/api/jobPrivateEndpoints/index.ts"
  "./api/jobs": "src/api/jobs/index.ts"
  "./api/jobTargetExecutions": "src/api/jobTargetExecutions/index.ts"
  "./api/jobStepExecutions": "src/api/jobStepExecutions/index.ts"
  "./api/jobCredentials": "src/api/jobCredentials/index.ts"
  "./api/jobAgents": "src/api/jobAgents/index.ts"
  "./api/jobExecutions": "src/api/jobExecutions/index.ts"
  "./api/iPv6FirewallRules": "src/api/iPv6FirewallRules/index.ts"
  "./api/instancePools": "src/api/instancePools/index.ts"
  "./api/instancePoolOperations": "src/api/instancePoolOperations/index.ts"
  "./api/instanceFailoverGroups": "src/api/instanceFailoverGroups/index.ts"
  "./api/geoBackupPolicies": "src/api/geoBackupPolicies/index.ts"
  "./api/failoverGroups": "src/api/failoverGroups/index.ts"
  "./api/endpointCertificates": "src/api/endpointCertificates/index.ts"
  "./api/encryptionProtectors": "src/api/encryptionProtectors/index.ts"
  "./api/elasticPools": "src/api/elasticPools/index.ts"
  "./api/managedInstances": "src/api/managedInstances/index.ts"
  "./api/serverTrustGroups": "src/api/serverTrustGroups/index.ts"
  "./api/managedDatabases": "src/api/managedDatabases/index.ts"
  "./api/distributedAvailabilityGroups": "src/api/distributedAvailabilityGroups/index.ts"
  "./api/deletedServers": "src/api/deletedServers/index.ts"
  "./api/dataMaskingPolicies": "src/api/dataMaskingPolicies/index.ts"
  "./api/managedDatabaseVulnerabilityAssessmentScans": "src/api/managedDatabaseVulnerabilityAssessmentScans/index.ts"
  "./api/managedDatabaseVulnerabilityAssessments": "src/api/managedDatabaseVulnerabilityAssessments/index.ts"
  "./api/databaseVulnerabilityAssessments": "src/api/databaseVulnerabilityAssessments/index.ts"
  "./api/managedDatabaseVulnerabilityAssessmentRuleBaselines": "src/api/managedDatabaseVulnerabilityAssessmentRuleBaselines/index.ts"
  "./api/databaseVulnerabilityAssessmentRuleBaselines": "src/api/databaseVulnerabilityAssessmentRuleBaselines/index.ts"
  "./api/sqlVulnerabilityAssessmentScans": "src/api/sqlVulnerabilityAssessmentScans/index.ts"
  "./api/sqlVulnerabilityAssessmentScanResult": "src/api/sqlVulnerabilityAssessmentScanResult/index.ts"
  "./api/databaseSqlVulnerabilityAssessmentScanResult": "src/api/databaseSqlVulnerabilityAssessmentScanResult/index.ts"
  "./api/sqlVulnerabilityAssessmentRuleBaseline": "src/api/sqlVulnerabilityAssessmentRuleBaseline/index.ts"
  "./api/databaseSqlVulnerabilityAssessmentRuleBaselines": "src/api/databaseSqlVulnerabilityAssessmentRuleBaselines/index.ts"
  "./api/sqlVulnerabilityAssessmentsSettings": "src/api/sqlVulnerabilityAssessmentsSettings/index.ts"
  "./api/sqlVulnerabilityAssessments": "src/api/sqlVulnerabilityAssessments/index.ts"
  "./api/sqlVulnerabilityAssessmentBaseline": "src/api/sqlVulnerabilityAssessmentBaseline/index.ts"
  "./api/databaseSecurityAlertPolicies": "src/api/databaseSecurityAlertPolicies/index.ts"
  "./api/managedDatabaseSchemas": "src/api/managedDatabaseSchemas/index.ts"
  "./api/databaseSchemas": "src/api/databaseSchemas/index.ts"
  "./api/managedDatabaseTables": "src/api/managedDatabaseTables/index.ts"
  "./api/databaseTables": "src/api/databaseTables/index.ts"
  "./api/managedDatabaseColumns": "src/api/managedDatabaseColumns/index.ts"
  "./api/serverAdvisors": "src/api/serverAdvisors/index.ts"
  "./api/extendedServerBlobAuditingPolicies": "src/api/extendedServerBlobAuditingPolicies/index.ts"
  "./api/extendedDatabaseBlobAuditingPolicies": "src/api/extendedDatabaseBlobAuditingPolicies/index.ts"
  "./api/databaseBlobAuditingPolicies": "src/api/databaseBlobAuditingPolicies/index.ts"
  "./api/serverBlobAuditingPolicies": "src/api/serverBlobAuditingPolicies/index.ts"
  "./api/servers": "src/api/servers/index.ts"
  "./api/replicationLinks": "src/api/replicationLinks/index.ts"
  "./api/firewallRules": "src/api/firewallRules/index.ts"
  "./api/databases": "src/api/databases/index.ts"
  "./api/sensitivityLabels": "src/api/sensitivityLabels/index.ts"
  "./api/restorePoints": "src/api/restorePoints/index.ts"
  "./api/databaseColumns": "src/api/databaseColumns/index.ts"
  "./api/backupShortTermRetentionPolicies": "src/api/backupShortTermRetentionPolicies/index.ts"
  "./api/operations": "src/api/operations/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
    polyfillSuffix: "-browser"

  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
    polyfillSuffix: "-react-native"

  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"

  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
