# warp.config.yml — build configuration

exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/workspaceManagerAssignmentJobs": "src/api/workspaceManagerAssignmentJobs/index.ts"
  "./api/getTriggeredAnalyticsRuleRuns": "src/api/getTriggeredAnalyticsRuleRuns/index.ts"
  "./api/reevaluate": "src/api/reevaluate/index.ts"
  "./api/getRecommendations": "src/api/getRecommendations/index.ts"
  "./api/update": "src/api/update/index.ts"
  "./api/get": "src/api/get/index.ts"
  "./api/entitiesGetTimeline": "src/api/entitiesGetTimeline/index.ts"
  "./api/threatIntelligence": "src/api/threatIntelligence/index.ts"
  "./api/threatIntelligenceIndicatorMetrics": "src/api/threatIntelligenceIndicatorMetrics/index.ts"
  "./api/sourceControl": "src/api/sourceControl/index.ts"
  "./api/dataConnectorsCheckRequirements": "src/api/dataConnectorsCheckRequirements/index.ts"
  "./api/threatIntelligenceIndicators": "src/api/threatIntelligenceIndicators/index.ts"
  "./api/threatIntelligenceIndicator": "src/api/threatIntelligenceIndicator/index.ts"
  "./api/metadata": "src/api/metadata/index.ts"
  "./api/entitiesRelations": "src/api/entitiesRelations/index.ts"
  "./api/incidentRelations": "src/api/incidentRelations/index.ts"
  "./api/contentTemplates": "src/api/contentTemplates/index.ts"
  "./api/contentTemplate": "src/api/contentTemplate/index.ts"
  "./api/productTemplates": "src/api/productTemplates/index.ts"
  "./api/productTemplate": "src/api/productTemplate/index.ts"
  "./api/productPackages": "src/api/productPackages/index.ts"
  "./api/productPackage": "src/api/productPackage/index.ts"
  "./api/contentPackage": "src/api/contentPackage/index.ts"
  "./api/contentPackages": "src/api/contentPackages/index.ts"
  "./api/bookmark": "src/api/bookmark/index.ts"
  "./api/actions": "src/api/actions/index.ts"
  "./api/alertRule": "src/api/alertRule/index.ts"
  "./api/workspaceManagerMembers": "src/api/workspaceManagerMembers/index.ts"
  "./api/workspaceManagerGroups": "src/api/workspaceManagerGroups/index.ts"
  "./api/workspaceManagerConfigurations": "src/api/workspaceManagerConfigurations/index.ts"
  "./api/workspaceManagerAssignments": "src/api/workspaceManagerAssignments/index.ts"
  "./api/triggeredAnalyticsRuleRun": "src/api/triggeredAnalyticsRuleRun/index.ts"
  "./api/productSettings": "src/api/productSettings/index.ts"
  "./api/officeConsents": "src/api/officeConsents/index.ts"
  "./api/huntRelations": "src/api/huntRelations/index.ts"
  "./api/huntComments": "src/api/huntComments/index.ts"
  "./api/hunts": "src/api/hunts/index.ts"
  "./api/fileImports": "src/api/fileImports/index.ts"
  "./api/entityQueryTemplates": "src/api/entityQueryTemplates/index.ts"
  "./api/entityQueries": "src/api/entityQueries/index.ts"
  "./api/entities": "src/api/entities/index.ts"
  "./api/billingStatistics": "src/api/billingStatistics/index.ts"
  "./api/watchlistItems": "src/api/watchlistItems/index.ts"
  "./api/watchlists": "src/api/watchlists/index.ts"
  "./api/sourceControls": "src/api/sourceControls/index.ts"
  "./api/securityMLAnalyticsSettings": "src/api/securityMLAnalyticsSettings/index.ts"
  "./api/sentinelOnboardingStates": "src/api/sentinelOnboardingStates/index.ts"
  "./api/incidentTasks": "src/api/incidentTasks/index.ts"
  "./api/entityRelations": "src/api/entityRelations/index.ts"
  "./api/bookmarkRelations": "src/api/bookmarkRelations/index.ts"
  "./api/incidentComments": "src/api/incidentComments/index.ts"
  "./api/dataConnectors": "src/api/dataConnectors/index.ts"
  "./api/dataConnectorDefinitions": "src/api/dataConnectorDefinitions/index.ts"
  "./api/bookmarks": "src/api/bookmarks/index.ts"
  "./api/incidents": "src/api/incidents/index.ts"
  "./api/automationRules": "src/api/automationRules/index.ts"
  "./api/alertRuleTemplates": "src/api/alertRuleTemplates/index.ts"
  "./api/alertRules": "src/api/alertRules/index.ts"
  "./api/operations": "src/api/operations/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
    polyfillSuffix: "-browser"

  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
    polyfillSuffix: "-react-native"

  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"

  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
