// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export {
  type ErrorResponse,
  type ErrorDetail,
  type ErrorAdditionalInfo,
  type SearchDocumentsResult,
  type FacetResult,
  type QueryAnswerResult,
  type DebugInfo,
  type SearchRequest,
  KnownQueryType,
  type QueryType,
  type ScoringStatistics,
  KnownQueryDebugMode,
  type QueryDebugMode,
  type SearchMode,
  KnownSemanticErrorMode,
  type SemanticErrorMode,
  KnownQueryAnswerType,
  type QueryAnswerType,
  KnownQueryCaptionType,
  type QueryCaptionType,
  type VectorQuery,
  type VectorQueryUnion,
  type VectorThreshold,
  type VectorThresholdUnion,
  KnownVectorThresholdKind,
  type VectorThresholdKind,
  type VectorSimilarityThreshold,
  type SearchScoreThreshold,
  KnownVectorQueryKind,
  type VectorQueryKind,
  type VectorizedQuery,
  type VectorizableTextQuery,
  type VectorizableImageUrlQuery,
  type VectorizableImageBinaryQuery,
  KnownVectorFilterMode,
  type VectorFilterMode,
  type SearchResult,
  type QueryCaptionResult,
  type DocumentDebugInfo,
  type VectorsDebugInfo,
  type QueryResultDocumentSubscores,
  type TextResult,
  type SingleVectorFieldResult,
  type QueryResultDocumentInnerHit,
  KnownSemanticErrorReason,
  type SemanticErrorReason,
  KnownSemanticSearchResultsType,
  type SemanticSearchResultsType,
  type LookupDocument,
  type SuggestDocumentsResult,
  type SuggestResult,
  type IndexDocumentsBatch,
  type IndexAction,
  type IndexActionType,
  type IndexDocumentsResult,
  type IndexingResult,
  type AutocompleteResult,
  type AutocompleteItem,
  type AutocompleteMode,
} from "./models.js";
