// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export {
  type ErrorResponse,
  type ErrorDetail,
  type ErrorAdditionalInfo,
  type SearchDocumentsResult,
  type FacetResult,
  type QueryAnswerResult,
  type DebugInfo,
  type QueryRewritesDebugInfo,
  type QueryRewritesValuesDebugInfo,
  type SearchRequest,
  KnownQueryType,
  type QueryType,
  type ScoringStatistics,
  KnownQueryDebugMode,
  type QueryDebugMode,
  type SearchMode,
  KnownQueryLanguage,
  type QueryLanguage,
  KnownQuerySpellerType,
  type QuerySpellerType,
  KnownSemanticErrorMode,
  type SemanticErrorMode,
  KnownQueryAnswerType,
  type QueryAnswerType,
  KnownQueryCaptionType,
  type QueryCaptionType,
  KnownQueryRewritesType,
  type QueryRewritesType,
  type VectorQuery,
  type VectorQueryUnion,
  type VectorThreshold,
  type VectorThresholdUnion,
  KnownVectorThresholdKind,
  type VectorThresholdKind,
  type VectorSimilarityThreshold,
  type SearchScoreThreshold,
  KnownVectorQueryKind,
  type VectorQueryKind,
  type VectorizedQuery,
  type VectorizableTextQuery,
  type VectorizableImageUrlQuery,
  type VectorizableImageBinaryQuery,
  KnownVectorFilterMode,
  type VectorFilterMode,
  type HybridSearch,
  KnownHybridCountAndFacetMode,
  type HybridCountAndFacetMode,
  type SearchResult,
  type QueryCaptionResult,
  type DocumentDebugInfo,
  type SemanticDebugInfo,
  type QueryResultDocumentSemanticField,
  KnownSemanticFieldState,
  type SemanticFieldState,
  type QueryResultDocumentRerankerInput,
  type VectorsDebugInfo,
  type QueryResultDocumentSubscores,
  type TextResult,
  type SingleVectorFieldResult,
  type QueryResultDocumentInnerHit,
  KnownSemanticErrorReason,
  type SemanticErrorReason,
  KnownSemanticSearchResultsType,
  type SemanticSearchResultsType,
  KnownSemanticQueryRewritesResultType,
  type SemanticQueryRewritesResultType,
  type LookupDocument,
  type SuggestDocumentsResult,
  type SuggestResult,
  type IndexDocumentsBatch,
  type IndexAction,
  type IndexActionType,
  type IndexDocumentsResult,
  type IndexingResult,
  type AutocompleteResult,
  type AutocompleteItem,
  type AutocompleteMode,
} from "./models.js";
