extends: ../../../warp.base.config.yml
exports:
  "./api": "./src/api/index.ts"
  "./api/serviceGroupMemberRelationships": "src/api/serviceGroupMemberRelationships/index.ts"
  "./api/dependencyOfRelationships": "src/api/dependencyOfRelationships/index.ts"
  "./api/operations": "src/api/operations/index.ts"
  "./models": "./src/models/index.ts"
