// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export {
  type DeploymentStacksWhatIfResult,
  type DeploymentStacksWhatIfResultProperties,
  type ErrorDetail,
  type ErrorAdditionalInfo,
  type DeploymentStacksTemplateLink,
  type DeploymentParameter,
  type KeyVaultParameterReference,
  type KeyVaultReference,
  type DeploymentStacksParametersLink,
  type DeploymentExtensionConfig,
  type DeploymentExtensionConfigItem,
  type DeploymentExternalInput,
  type DeploymentExternalInputDefinition,
  type ActionOnUnmanage,
  KnownUnmanageActionResourceMode,
  type UnmanageActionResourceMode,
  KnownUnmanageActionResourceGroupMode,
  type UnmanageActionResourceGroupMode,
  KnownUnmanageActionManagementGroupMode,
  type UnmanageActionManagementGroupMode,
  KnownResourcesWithoutDeleteSupportAction,
  type ResourcesWithoutDeleteSupportAction,
  type DeploymentStacksDebugSetting,
  type DenySettings,
  KnownDenySettingsMode,
  type DenySettingsMode,
  KnownDeploymentStackProvisioningState,
  type DeploymentStackProvisioningState,
  KnownValidationLevel,
  type ValidationLevel,
  type DeploymentStacksWhatIfChange,
  type DeploymentStacksWhatIfResourceChange,
  type DeploymentExtension,
  KnownDeploymentStacksWhatIfChangeType,
  type DeploymentStacksWhatIfChangeType,
  KnownDeploymentStacksWhatIfChangeCertainty,
  type DeploymentStacksWhatIfChangeCertainty,
  type DeploymentStacksChangeBaseDeploymentStacksManagementStatus,
  KnownDeploymentStacksManagementStatus,
  type DeploymentStacksManagementStatus,
  type DeploymentStacksChangeBaseDenyStatusMode,
  KnownDenyStatusMode,
  type DenyStatusMode,
  type DeploymentStacksChangeDeltaRecord,
  type DeploymentStacksWhatIfPropertyChange,
  KnownDeploymentStacksWhatIfPropertyChangeType,
  type DeploymentStacksWhatIfPropertyChangeType,
  type DeploymentStacksChangeDeltaDenySettings,
  type DeploymentStacksChangeBase,
  type DeploymentStacksDiagnostic,
  KnownDeploymentStacksDiagnosticLevel,
  type DeploymentStacksDiagnosticLevel,
  type ProxyResource,
  type Resource,
  type SystemData,
  KnownCreatedByType,
  type CreatedByType,
  type ErrorResponse,
  type DeploymentStack,
  type DeploymentStackProperties,
  type ResourceReference,
  type ResourceReferenceExtended,
  type ManagedResourceReference,
  KnownResourceStatusMode,
  type ResourceStatusMode,
  type DeploymentStackValidateResult,
  type DeploymentStackValidateProperties,
  type DeploymentStackTemplateDefinition,
  KnownVersions,
} from "./models.js";
