# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/horizonDbParameterGroups": "src/api/horizonDbParameterGroups/index.ts"
  "./api/horizonDbPrivateLinkResources": "src/api/horizonDbPrivateLinkResources/index.ts"
  "./api/horizonDbPrivateEndpointConnections": "src/api/horizonDbPrivateEndpointConnections/index.ts"
  "./api/horizonDbFirewallRules": "src/api/horizonDbFirewallRules/index.ts"
  "./api/horizonDbReplicas": "src/api/horizonDbReplicas/index.ts"
  "./api/horizonDbPools": "src/api/horizonDbPools/index.ts"
  "./api/horizonDbClusters": "src/api/horizonDbClusters/index.ts"
  "./api/operations": "src/api/operations/index.ts"
  "./models": "./src/models/index.ts"
