# warp.config.yml — build configuration

exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/operationsResults": "src/api/operationsResults/index.ts"
  "./api/operationStatus": "src/api/operationStatus/index.ts"
  "./api/workspaceApiExport": "src/api/workspaceApiExport/index.ts"
  "./api/apiManagementSkus": "src/api/apiManagementSkus/index.ts"
  "./api/apiExport": "src/api/apiExport/index.ts"
  "./api/workspace": "src/api/workspace/index.ts"
  "./api/apiManagementWorkspaceLinks": "src/api/apiManagementWorkspaceLinks/index.ts"
  "./api/apiManagementWorkspaceLink": "src/api/apiManagementWorkspaceLink/index.ts"
  "./api/userConfirmationPassword": "src/api/userConfirmationPassword/index.ts"
  "./api/userIdentities": "src/api/userIdentities/index.ts"
  "./api/userGroup": "src/api/userGroup/index.ts"
  "./api/user": "src/api/user/index.ts"
  "./api/tenantConfiguration": "src/api/tenantConfiguration/index.ts"
  "./api/tenantAccessGit": "src/api/tenantAccessGit/index.ts"
  "./api/tenantAccess": "src/api/tenantAccess/index.ts"
  "./api/tagProductLink": "src/api/tagProductLink/index.ts"
  "./api/tagOperationLink": "src/api/tagOperationLink/index.ts"
  "./api/tagApiLink": "src/api/tagApiLink/index.ts"
  "./api/subscription": "src/api/subscription/index.ts"
  "./api/tenantSettings": "src/api/tenantSettings/index.ts"
  "./api/globalSchema": "src/api/globalSchema/index.ts"
  "./api/productGroupLink": "src/api/productGroupLink/index.ts"
  "./api/productApiLink": "src/api/productApiLink/index.ts"
  "./api/productSubscriptions": "src/api/productSubscriptions/index.ts"
  "./api/productGroup": "src/api/productGroup/index.ts"
  "./api/productApi": "src/api/productApi/index.ts"
  "./api/privateEndpointConnection": "src/api/privateEndpointConnection/index.ts"
  "./api/portalRevision": "src/api/portalRevision/index.ts"
  "./api/clientApplicationProductLink": "src/api/clientApplicationProductLink/index.ts"
  "./api/clientApplication": "src/api/clientApplication/index.ts"
  "./api/portalConfig": "src/api/portalConfig/index.ts"
  "./api/policyRestriction": "src/api/policyRestriction/index.ts"
  "./api/policyFragment": "src/api/policyFragment/index.ts"
  "./api/openIdConnectProvider": "src/api/openIdConnectProvider/index.ts"
  "./api/workspaceNotificationRecipientEmail": "src/api/workspaceNotificationRecipientEmail/index.ts"
  "./api/workspaceNotificationRecipientUser": "src/api/workspaceNotificationRecipientUser/index.ts"
  "./api/notificationRecipientEmail": "src/api/notificationRecipientEmail/index.ts"
  "./api/notificationRecipientUser": "src/api/notificationRecipientUser/index.ts"
  "./api/notification": "src/api/notification/index.ts"
  "./api/namedValue": "src/api/namedValue/index.ts"
  "./api/logger": "src/api/logger/index.ts"
  "./api/identityProvider": "src/api/identityProvider/index.ts"
  "./api/workspaceGroupUser": "src/api/workspaceGroupUser/index.ts"
  "./api/groupUser": "src/api/groupUser/index.ts"
  "./api/group": "src/api/group/index.ts"
  "./api/gatewayCertificateAuthority": "src/api/gatewayCertificateAuthority/index.ts"
  "./api/gatewayHostnameConfiguration": "src/api/gatewayHostnameConfiguration/index.ts"
  "./api/gatewayApi": "src/api/gatewayApi/index.ts"
  "./api/gateway": "src/api/gateway/index.ts"
  "./api/apiGatewayHostnameBinding": "src/api/apiGatewayHostnameBinding/index.ts"
  "./api/apiGatewayConfigConnection": "src/api/apiGatewayConfigConnection/index.ts"
  "./api/emailTemplate": "src/api/emailTemplate/index.ts"
  "./api/documentation": "src/api/documentation/index.ts"
  "./api/deletedServices": "src/api/deletedServices/index.ts"
  "./api/contentItem": "src/api/contentItem/index.ts"
  "./api/contentType": "src/api/contentType/index.ts"
  "./api/certificate": "src/api/certificate/index.ts"
  "./api/cache": "src/api/cache/index.ts"
  "./api/backend": "src/api/backend/index.ts"
  "./api/authorizationServer": "src/api/authorizationServer/index.ts"
  "./api/authorizationAccessPolicy": "src/api/authorizationAccessPolicy/index.ts"
  "./api/authorizationLoginLinks": "src/api/authorizationLoginLinks/index.ts"
  "./api/authorization": "src/api/authorization/index.ts"
  "./api/authorizationProvider": "src/api/authorizationProvider/index.ts"
  "./api/apiVersionSet": "src/api/apiVersionSet/index.ts"
  "./api/apiTool": "src/api/apiTool/index.ts"
  "./api/productWikis": "src/api/productWikis/index.ts"
  "./api/apiWikis": "src/api/apiWikis/index.ts"
  "./api/apiWiki": "src/api/apiWiki/index.ts"
  "./api/apiTagDescription": "src/api/apiTagDescription/index.ts"
  "./api/apiIssueAttachment": "src/api/apiIssueAttachment/index.ts"
  "./api/apiIssueComment": "src/api/apiIssueComment/index.ts"
  "./api/apiIssue": "src/api/apiIssue/index.ts"
  "./api/apiDiagnostic": "src/api/apiDiagnostic/index.ts"
  "./api/apiSchema": "src/api/apiSchema/index.ts"
  "./api/graphQLApiResolver": "src/api/graphQLApiResolver/index.ts"
  "./api/apiOperationPolicy": "src/api/apiOperationPolicy/index.ts"
  "./api/apiOperation": "src/api/apiOperation/index.ts"
  "./api/apiRelease": "src/api/apiRelease/index.ts"
  "./api/tagResource": "src/api/tagResource/index.ts"
  "./api/reports": "src/api/reports/index.ts"
  "./api/region": "src/api/region/index.ts"
  "./api/quotaByPeriodKeys": "src/api/quotaByPeriodKeys/index.ts"
  "./api/quotaByCounterKeys": "src/api/quotaByCounterKeys/index.ts"
  "./api/product": "src/api/product/index.ts"
  "./api/portalSettings": "src/api/portalSettings/index.ts"
  "./api/policyRestrictionValidations": "src/api/policyRestrictionValidations/index.ts"
  "./api/policyDescription": "src/api/policyDescription/index.ts"
  "./api/outboundNetworkDependenciesEndpoints": "src/api/outboundNetworkDependenciesEndpoints/index.ts"
  "./api/networkStatus": "src/api/networkStatus/index.ts"
  "./api/apiManagementServiceSkus": "src/api/apiManagementServiceSkus/index.ts"
  "./api/allPolicies": "src/api/allPolicies/index.ts"
  "./api/apiManagementService": "src/api/apiManagementService/index.ts"
  "./api/workspaceApiRevision": "src/api/workspaceApiRevision/index.ts"
  "./api/operation": "src/api/operation/index.ts"
  "./api/apiProduct": "src/api/apiProduct/index.ts"
  "./api/apiRevision": "src/api/apiRevision/index.ts"
  "./api/api": "src/api/api/index.ts"
  "./api/apiManagementGatewaySkus": "src/api/apiManagementGatewaySkus/index.ts"
  "./api/apiGateway": "src/api/apiGateway/index.ts"
  "./api/apiManagementOperations": "src/api/apiManagementOperations/index.ts"
  "./api/workspaceTagProductLink": "src/api/workspaceTagProductLink/index.ts"
  "./api/workspaceTagOperationLink": "src/api/workspaceTagOperationLink/index.ts"
  "./api/workspaceTagApiLink": "src/api/workspaceTagApiLink/index.ts"
  "./api/workspaceSubscription": "src/api/workspaceSubscription/index.ts"
  "./api/userSubscription": "src/api/userSubscription/index.ts"
  "./api/workspaceGlobalSchema": "src/api/workspaceGlobalSchema/index.ts"
  "./api/workspaceProductGroupLink": "src/api/workspaceProductGroupLink/index.ts"
  "./api/workspaceProductApiLink": "src/api/workspaceProductApiLink/index.ts"
  "./api/workspaceProduct": "src/api/workspaceProduct/index.ts"
  "./api/delegationSettings": "src/api/delegationSettings/index.ts"
  "./api/signUpSettings": "src/api/signUpSettings/index.ts"
  "./api/signInSettings": "src/api/signInSettings/index.ts"
  "./api/workspacePolicyFragment": "src/api/workspacePolicyFragment/index.ts"
  "./api/workspaceNotification": "src/api/workspaceNotification/index.ts"
  "./api/workspaceNamedValue": "src/api/workspaceNamedValue/index.ts"
  "./api/workspaceLogger": "src/api/workspaceLogger/index.ts"
  "./api/workspaceGroup": "src/api/workspaceGroup/index.ts"
  "./api/workspaceCertificate": "src/api/workspaceCertificate/index.ts"
  "./api/workspaceBackend": "src/api/workspaceBackend/index.ts"
  "./api/workspaceApiVersionSet": "src/api/workspaceApiVersionSet/index.ts"
  "./api/productWiki": "src/api/productWiki/index.ts"
  "./api/issue": "src/api/issue/index.ts"
  "./api/workspaceApiDiagnostic": "src/api/workspaceApiDiagnostic/index.ts"
  "./api/workspaceDiagnostic": "src/api/workspaceDiagnostic/index.ts"
  "./api/diagnostic": "src/api/diagnostic/index.ts"
  "./api/workspaceApiSchema": "src/api/workspaceApiSchema/index.ts"
  "./api/workspaceTag": "src/api/workspaceTag/index.ts"
  "./api/tag": "src/api/tag/index.ts"
  "./api/workspaceProductPolicy": "src/api/workspaceProductPolicy/index.ts"
  "./api/workspaceApiPolicy": "src/api/workspaceApiPolicy/index.ts"
  "./api/workspaceApiOperationPolicy": "src/api/workspaceApiOperationPolicy/index.ts"
  "./api/workspacePolicy": "src/api/workspacePolicy/index.ts"
  "./api/productPolicy": "src/api/productPolicy/index.ts"
  "./api/policy": "src/api/policy/index.ts"
  "./api/apiPolicy": "src/api/apiPolicy/index.ts"
  "./api/graphQLApiResolverPolicy": "src/api/graphQLApiResolverPolicy/index.ts"
  "./api/workspaceApiOperation": "src/api/workspaceApiOperation/index.ts"
  "./api/workspaceApiRelease": "src/api/workspaceApiRelease/index.ts"
  "./api/apiManagementServiceResources": "src/api/apiManagementServiceResources/index.ts"
  "./api/workspaceApi": "src/api/workspaceApi/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
    polyfillSuffix: "-browser"

  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
    polyfillSuffix: "-react-native"

  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"

  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
