extends: ../../../warp.base.config.yml
exports:
  "./api": "./src/api/index.ts"
  "./api/playwrightWorkspaceQuotas": "./src/api/playwrightWorkspaceQuotas/index.ts"
  "./api/playwrightQuotas": "./src/api/playwrightQuotas/index.ts"
  "./api/playwrightWorkspaces": "./src/api/playwrightWorkspaces/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"
<<<<<<< HEAD

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
    polyfillSuffix: "-browser"

  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
    polyfillSuffix: "-react-native"

  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"

  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
    moduleType: commonjs
=======
>>>>>>> origin/main
