extends: ../../../warp.base.config.yml
exports:
  "./api": "./src/api/index.ts"
  "./api/playwrightWorkspaceQuotas": "./src/api/playwrightWorkspaceQuotas/index.ts"
  "./api/playwrightQuotas": "./src/api/playwrightQuotas/index.ts"
  "./api/playwrightWorkspaces": "./src/api/playwrightWorkspaces/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"
