/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import { PrivateLinkServicesForM365ComplianceCenter } from "../operationsInterfaces";
import * as coreClient from "@azure/core-client";
import * as Mappers from "../models/mappers";
import * as Parameters from "../models/parameters";
import { M365SecurityAndComplianceClient } from "../m365SecurityAndComplianceClient";
import { PollerLike, PollOperationState, LroEngine } from "@azure/core-lro";
import { LroImpl } from "../lroImpl";
import {
  PrivateLinkServicesForM365ComplianceCenterDescription,
  PrivateLinkServicesForM365ComplianceCenterListNextOptionalParams,
  PrivateLinkServicesForM365ComplianceCenterListOptionalParams,
  PrivateLinkServicesForM365ComplianceCenterListByResourceGroupNextOptionalParams,
  PrivateLinkServicesForM365ComplianceCenterListByResourceGroupOptionalParams,
  PrivateLinkServicesForM365ComplianceCenterGetOptionalParams,
  PrivateLinkServicesForM365ComplianceCenterGetResponse,
  PrivateLinkServicesForM365ComplianceCenterCreateOrUpdateOptionalParams,
  PrivateLinkServicesForM365ComplianceCenterCreateOrUpdateResponse,
  ServicesPatchDescription,
  PrivateLinkServicesForM365ComplianceCenterUpdateOptionalParams,
  PrivateLinkServicesForM365ComplianceCenterUpdateResponse,
  PrivateLinkServicesForM365ComplianceCenterDeleteOptionalParams,
  PrivateLinkServicesForM365ComplianceCenterListResponse,
  PrivateLinkServicesForM365ComplianceCenterListByResourceGroupResponse,
  PrivateLinkServicesForM365ComplianceCenterListNextResponse,
  PrivateLinkServicesForM365ComplianceCenterListByResourceGroupNextResponse
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Class containing PrivateLinkServicesForM365ComplianceCenter operations. */
export class PrivateLinkServicesForM365ComplianceCenterImpl
  implements PrivateLinkServicesForM365ComplianceCenter {
  private readonly client: M365SecurityAndComplianceClient;

  /**
   * Initialize a new instance of the class PrivateLinkServicesForM365ComplianceCenter class.
   * @param client Reference to the service client
   */
  constructor(client: M365SecurityAndComplianceClient) {
    this.client = client;
  }

  /**
   * Get all the privateLinkServicesForM365ComplianceCenter instances in a subscription.
   * @param options The options parameters.
   */
  public list(
    options?: PrivateLinkServicesForM365ComplianceCenterListOptionalParams
  ): PagedAsyncIterableIterator<
    PrivateLinkServicesForM365ComplianceCenterDescription
  > {
    const iter = this.listPagingAll(options);
    return {
      next() {
        return iter.next();
      },
      [Symbol.asyncIterator]() {
        return this;
      },
      byPage: () => {
        return this.listPagingPage(options);
      }
    };
  }

  private async *listPagingPage(
    options?: PrivateLinkServicesForM365ComplianceCenterListOptionalParams
  ): AsyncIterableIterator<
    PrivateLinkServicesForM365ComplianceCenterDescription[]
  > {
    let result = await this._list(options);
    yield result.value || [];
    let continuationToken = result.nextLink;
    while (continuationToken) {
      result = await this._listNext(continuationToken, options);
      continuationToken = result.nextLink;
      yield result.value || [];
    }
  }

  private async *listPagingAll(
    options?: PrivateLinkServicesForM365ComplianceCenterListOptionalParams
  ): AsyncIterableIterator<
    PrivateLinkServicesForM365ComplianceCenterDescription
  > {
    for await (const page of this.listPagingPage(options)) {
      yield* page;
    }
  }

  /**
   * Get all the service instances in a resource group.
   * @param resourceGroupName The name of the resource group that contains the service instance.
   * @param options The options parameters.
   */
  public listByResourceGroup(
    resourceGroupName: string,
    options?: PrivateLinkServicesForM365ComplianceCenterListByResourceGroupOptionalParams
  ): PagedAsyncIterableIterator<
    PrivateLinkServicesForM365ComplianceCenterDescription
  > {
    const iter = this.listByResourceGroupPagingAll(resourceGroupName, options);
    return {
      next() {
        return iter.next();
      },
      [Symbol.asyncIterator]() {
        return this;
      },
      byPage: () => {
        return this.listByResourceGroupPagingPage(resourceGroupName, options);
      }
    };
  }

  private async *listByResourceGroupPagingPage(
    resourceGroupName: string,
    options?: PrivateLinkServicesForM365ComplianceCenterListByResourceGroupOptionalParams
  ): AsyncIterableIterator<
    PrivateLinkServicesForM365ComplianceCenterDescription[]
  > {
    let result = await this._listByResourceGroup(resourceGroupName, options);
    yield result.value || [];
    let continuationToken = result.nextLink;
    while (continuationToken) {
      result = await this._listByResourceGroupNext(
        resourceGroupName,
        continuationToken,
        options
      );
      continuationToken = result.nextLink;
      yield result.value || [];
    }
  }

  private async *listByResourceGroupPagingAll(
    resourceGroupName: string,
    options?: PrivateLinkServicesForM365ComplianceCenterListByResourceGroupOptionalParams
  ): AsyncIterableIterator<
    PrivateLinkServicesForM365ComplianceCenterDescription
  > {
    for await (const page of this.listByResourceGroupPagingPage(
      resourceGroupName,
      options
    )) {
      yield* page;
    }
  }

  /**
   * Get the metadata of a privateLinkServicesForM365ComplianceCenter resource.
   * @param resourceGroupName The name of the resource group that contains the service instance.
   * @param resourceName The name of the service instance.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    resourceName: string,
    options?: PrivateLinkServicesForM365ComplianceCenterGetOptionalParams
  ): Promise<PrivateLinkServicesForM365ComplianceCenterGetResponse> {
    return this.client.sendOperationRequest(
      { resourceGroupName, resourceName, options },
      getOperationSpec
    );
  }

  /**
   * Create or update the metadata of a privateLinkServicesForM365ComplianceCenter instance.
   * @param resourceGroupName The name of the resource group that contains the service instance.
   * @param resourceName The name of the service instance.
   * @param privateLinkServicesForM365ComplianceCenterDescription The service instance metadata.
   * @param options The options parameters.
   */
  async beginCreateOrUpdate(
    resourceGroupName: string,
    resourceName: string,
    privateLinkServicesForM365ComplianceCenterDescription: PrivateLinkServicesForM365ComplianceCenterDescription,
    options?: PrivateLinkServicesForM365ComplianceCenterCreateOrUpdateOptionalParams
  ): Promise<
    PollerLike<
      PollOperationState<
        PrivateLinkServicesForM365ComplianceCenterCreateOrUpdateResponse
      >,
      PrivateLinkServicesForM365ComplianceCenterCreateOrUpdateResponse
    >
  > {
    const directSendOperation = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec
    ): Promise<PrivateLinkServicesForM365ComplianceCenterCreateOrUpdateResponse> => {
      return this.client.sendOperationRequest(args, spec);
    };
    const sendOperation = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec
    ) => {
      let currentRawResponse:
        | coreClient.FullOperationResponse
        | undefined = undefined;
      const providedCallback = args.options?.onResponse;
      const callback: coreClient.RawResponseCallback = (
        rawResponse: coreClient.FullOperationResponse,
        flatResponse: unknown
      ) => {
        currentRawResponse = rawResponse;
        providedCallback?.(rawResponse, flatResponse);
      };
      const updatedArgs = {
        ...args,
        options: {
          ...args.options,
          onResponse: callback
        }
      };
      const flatResponse = await directSendOperation(updatedArgs, spec);
      return {
        flatResponse,
        rawResponse: {
          statusCode: currentRawResponse!.status,
          body: currentRawResponse!.parsedBody,
          headers: currentRawResponse!.headers.toJSON()
        }
      };
    };

    const lro = new LroImpl(
      sendOperation,
      {
        resourceGroupName,
        resourceName,
        privateLinkServicesForM365ComplianceCenterDescription,
        options
      },
      createOrUpdateOperationSpec
    );
    return new LroEngine(lro, {
      resumeFrom: options?.resumeFrom,
      intervalInMs: options?.updateIntervalInMs,
      lroResourceLocationConfig: "location"
    });
  }

  /**
   * Create or update the metadata of a privateLinkServicesForM365ComplianceCenter instance.
   * @param resourceGroupName The name of the resource group that contains the service instance.
   * @param resourceName The name of the service instance.
   * @param privateLinkServicesForM365ComplianceCenterDescription The service instance metadata.
   * @param options The options parameters.
   */
  async beginCreateOrUpdateAndWait(
    resourceGroupName: string,
    resourceName: string,
    privateLinkServicesForM365ComplianceCenterDescription: PrivateLinkServicesForM365ComplianceCenterDescription,
    options?: PrivateLinkServicesForM365ComplianceCenterCreateOrUpdateOptionalParams
  ): Promise<PrivateLinkServicesForM365ComplianceCenterCreateOrUpdateResponse> {
    const poller = await this.beginCreateOrUpdate(
      resourceGroupName,
      resourceName,
      privateLinkServicesForM365ComplianceCenterDescription,
      options
    );
    return poller.pollUntilDone();
  }

  /**
   * Update the metadata of a privateLinkServicesForM365ComplianceCenter instance.
   * @param resourceGroupName The name of the resource group that contains the service instance.
   * @param resourceName The name of the service instance.
   * @param servicePatchDescription The service instance metadata and security metadata.
   * @param options The options parameters.
   */
  async beginUpdate(
    resourceGroupName: string,
    resourceName: string,
    servicePatchDescription: ServicesPatchDescription,
    options?: PrivateLinkServicesForM365ComplianceCenterUpdateOptionalParams
  ): Promise<
    PollerLike<
      PollOperationState<
        PrivateLinkServicesForM365ComplianceCenterUpdateResponse
      >,
      PrivateLinkServicesForM365ComplianceCenterUpdateResponse
    >
  > {
    const directSendOperation = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec
    ): Promise<PrivateLinkServicesForM365ComplianceCenterUpdateResponse> => {
      return this.client.sendOperationRequest(args, spec);
    };
    const sendOperation = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec
    ) => {
      let currentRawResponse:
        | coreClient.FullOperationResponse
        | undefined = undefined;
      const providedCallback = args.options?.onResponse;
      const callback: coreClient.RawResponseCallback = (
        rawResponse: coreClient.FullOperationResponse,
        flatResponse: unknown
      ) => {
        currentRawResponse = rawResponse;
        providedCallback?.(rawResponse, flatResponse);
      };
      const updatedArgs = {
        ...args,
        options: {
          ...args.options,
          onResponse: callback
        }
      };
      const flatResponse = await directSendOperation(updatedArgs, spec);
      return {
        flatResponse,
        rawResponse: {
          statusCode: currentRawResponse!.status,
          body: currentRawResponse!.parsedBody,
          headers: currentRawResponse!.headers.toJSON()
        }
      };
    };

    const lro = new LroImpl(
      sendOperation,
      { resourceGroupName, resourceName, servicePatchDescription, options },
      updateOperationSpec
    );
    return new LroEngine(lro, {
      resumeFrom: options?.resumeFrom,
      intervalInMs: options?.updateIntervalInMs,
      lroResourceLocationConfig: "location"
    });
  }

  /**
   * Update the metadata of a privateLinkServicesForM365ComplianceCenter instance.
   * @param resourceGroupName The name of the resource group that contains the service instance.
   * @param resourceName The name of the service instance.
   * @param servicePatchDescription The service instance metadata and security metadata.
   * @param options The options parameters.
   */
  async beginUpdateAndWait(
    resourceGroupName: string,
    resourceName: string,
    servicePatchDescription: ServicesPatchDescription,
    options?: PrivateLinkServicesForM365ComplianceCenterUpdateOptionalParams
  ): Promise<PrivateLinkServicesForM365ComplianceCenterUpdateResponse> {
    const poller = await this.beginUpdate(
      resourceGroupName,
      resourceName,
      servicePatchDescription,
      options
    );
    return poller.pollUntilDone();
  }

  /**
   * Delete a service instance.
   * @param resourceGroupName The name of the resource group that contains the service instance.
   * @param resourceName The name of the service instance.
   * @param options The options parameters.
   */
  async beginDelete(
    resourceGroupName: string,
    resourceName: string,
    options?: PrivateLinkServicesForM365ComplianceCenterDeleteOptionalParams
  ): Promise<PollerLike<PollOperationState<void>, void>> {
    const directSendOperation = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec
    ): Promise<void> => {
      return this.client.sendOperationRequest(args, spec);
    };
    const sendOperation = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec
    ) => {
      let currentRawResponse:
        | coreClient.FullOperationResponse
        | undefined = undefined;
      const providedCallback = args.options?.onResponse;
      const callback: coreClient.RawResponseCallback = (
        rawResponse: coreClient.FullOperationResponse,
        flatResponse: unknown
      ) => {
        currentRawResponse = rawResponse;
        providedCallback?.(rawResponse, flatResponse);
      };
      const updatedArgs = {
        ...args,
        options: {
          ...args.options,
          onResponse: callback
        }
      };
      const flatResponse = await directSendOperation(updatedArgs, spec);
      return {
        flatResponse,
        rawResponse: {
          statusCode: currentRawResponse!.status,
          body: currentRawResponse!.parsedBody,
          headers: currentRawResponse!.headers.toJSON()
        }
      };
    };

    const lro = new LroImpl(
      sendOperation,
      { resourceGroupName, resourceName, options },
      deleteOperationSpec
    );
    return new LroEngine(lro, {
      resumeFrom: options?.resumeFrom,
      intervalInMs: options?.updateIntervalInMs,
      lroResourceLocationConfig: "location"
    });
  }

  /**
   * Delete a service instance.
   * @param resourceGroupName The name of the resource group that contains the service instance.
   * @param resourceName The name of the service instance.
   * @param options The options parameters.
   */
  async beginDeleteAndWait(
    resourceGroupName: string,
    resourceName: string,
    options?: PrivateLinkServicesForM365ComplianceCenterDeleteOptionalParams
  ): Promise<void> {
    const poller = await this.beginDelete(
      resourceGroupName,
      resourceName,
      options
    );
    return poller.pollUntilDone();
  }

  /**
   * Get all the privateLinkServicesForM365ComplianceCenter instances in a subscription.
   * @param options The options parameters.
   */
  private _list(
    options?: PrivateLinkServicesForM365ComplianceCenterListOptionalParams
  ): Promise<PrivateLinkServicesForM365ComplianceCenterListResponse> {
    return this.client.sendOperationRequest({ options }, listOperationSpec);
  }

  /**
   * Get all the service instances in a resource group.
   * @param resourceGroupName The name of the resource group that contains the service instance.
   * @param options The options parameters.
   */
  private _listByResourceGroup(
    resourceGroupName: string,
    options?: PrivateLinkServicesForM365ComplianceCenterListByResourceGroupOptionalParams
  ): Promise<
    PrivateLinkServicesForM365ComplianceCenterListByResourceGroupResponse
  > {
    return this.client.sendOperationRequest(
      { resourceGroupName, options },
      listByResourceGroupOperationSpec
    );
  }

  /**
   * ListNext
   * @param nextLink The nextLink from the previous successful call to the List method.
   * @param options The options parameters.
   */
  private _listNext(
    nextLink: string,
    options?: PrivateLinkServicesForM365ComplianceCenterListNextOptionalParams
  ): Promise<PrivateLinkServicesForM365ComplianceCenterListNextResponse> {
    return this.client.sendOperationRequest(
      { nextLink, options },
      listNextOperationSpec
    );
  }

  /**
   * ListByResourceGroupNext
   * @param resourceGroupName The name of the resource group that contains the service instance.
   * @param nextLink The nextLink from the previous successful call to the ListByResourceGroup method.
   * @param options The options parameters.
   */
  private _listByResourceGroupNext(
    resourceGroupName: string,
    nextLink: string,
    options?: PrivateLinkServicesForM365ComplianceCenterListByResourceGroupNextOptionalParams
  ): Promise<
    PrivateLinkServicesForM365ComplianceCenterListByResourceGroupNextResponse
  > {
    return this.client.sendOperationRequest(
      { resourceGroupName, nextLink, options },
      listByResourceGroupNextOperationSpec
    );
  }
}
// Operation Specifications
const serializer = coreClient.createSerializer(Mappers, /* isXml */ false);

const getOperationSpec: coreClient.OperationSpec = {
  path:
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.M365SecurityAndCompliance/privateLinkServicesForM365ComplianceCenter/{resourceName}",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper: Mappers.PrivateLinkServicesForM365ComplianceCenterDescription
    },
    default: {
      bodyMapper: Mappers.ErrorDetails
    }
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.resourceName
  ],
  headerParameters: [Parameters.accept],
  serializer
};
const createOrUpdateOperationSpec: coreClient.OperationSpec = {
  path:
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.M365SecurityAndCompliance/privateLinkServicesForM365ComplianceCenter/{resourceName}",
  httpMethod: "PUT",
  responses: {
    200: {
      bodyMapper: Mappers.PrivateLinkServicesForM365ComplianceCenterDescription
    },
    201: {
      bodyMapper: Mappers.PrivateLinkServicesForM365ComplianceCenterDescription
    },
    202: {
      bodyMapper: Mappers.PrivateLinkServicesForM365ComplianceCenterDescription
    },
    204: {
      bodyMapper: Mappers.PrivateLinkServicesForM365ComplianceCenterDescription
    },
    default: {
      bodyMapper: Mappers.ErrorDetails
    }
  },
  requestBody: Parameters.privateLinkServicesForM365ComplianceCenterDescription,
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.resourceName
  ],
  headerParameters: [Parameters.accept, Parameters.contentType],
  mediaType: "json",
  serializer
};
const updateOperationSpec: coreClient.OperationSpec = {
  path:
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.M365SecurityAndCompliance/privateLinkServicesForM365ComplianceCenter/{resourceName}",
  httpMethod: "PATCH",
  responses: {
    200: {
      bodyMapper: Mappers.PrivateLinkServicesForM365ComplianceCenterDescription
    },
    201: {
      bodyMapper: Mappers.PrivateLinkServicesForM365ComplianceCenterDescription
    },
    202: {
      bodyMapper: Mappers.PrivateLinkServicesForM365ComplianceCenterDescription
    },
    204: {
      bodyMapper: Mappers.PrivateLinkServicesForM365ComplianceCenterDescription
    },
    default: {
      bodyMapper: Mappers.ErrorDetails
    }
  },
  requestBody: Parameters.servicePatchDescription,
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.resourceName
  ],
  headerParameters: [Parameters.accept, Parameters.contentType],
  mediaType: "json",
  serializer
};
const deleteOperationSpec: coreClient.OperationSpec = {
  path:
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.M365SecurityAndCompliance/privateLinkServicesForM365ComplianceCenter/{resourceName}",
  httpMethod: "DELETE",
  responses: {
    200: {},
    201: {},
    202: {},
    204: {},
    default: {
      bodyMapper: Mappers.ErrorDetails
    }
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.resourceName
  ],
  headerParameters: [Parameters.accept],
  serializer
};
const listOperationSpec: coreClient.OperationSpec = {
  path:
    "/subscriptions/{subscriptionId}/providers/Microsoft.M365SecurityAndCompliance/privateLinkServicesForM365ComplianceCenter",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper:
        Mappers.PrivateLinkServicesForM365ComplianceCenterDescriptionListResult
    },
    default: {
      bodyMapper: Mappers.ErrorDetails
    }
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [Parameters.$host, Parameters.subscriptionId],
  headerParameters: [Parameters.accept],
  serializer
};
const listByResourceGroupOperationSpec: coreClient.OperationSpec = {
  path:
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.M365SecurityAndCompliance/privateLinkServicesForM365ComplianceCenter",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper:
        Mappers.PrivateLinkServicesForM365ComplianceCenterDescriptionListResult
    },
    default: {
      bodyMapper: Mappers.ErrorDetails
    }
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName
  ],
  headerParameters: [Parameters.accept],
  serializer
};
const listNextOperationSpec: coreClient.OperationSpec = {
  path: "{nextLink}",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper:
        Mappers.PrivateLinkServicesForM365ComplianceCenterDescriptionListResult
    },
    default: {
      bodyMapper: Mappers.ErrorDetails
    }
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.nextLink,
    Parameters.subscriptionId
  ],
  headerParameters: [Parameters.accept],
  serializer
};
const listByResourceGroupNextOperationSpec: coreClient.OperationSpec = {
  path: "{nextLink}",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper:
        Mappers.PrivateLinkServicesForM365ComplianceCenterDescriptionListResult
    },
    default: {
      bodyMapper: Mappers.ErrorDetails
    }
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.nextLink,
    Parameters.subscriptionId,
    Parameters.resourceGroupName
  ],
  headerParameters: [Parameters.accept],
  serializer
};
