extends: ../../../warp.base.config.yml
exports:
  "./api": "./src/api/index.ts"
  "./api/deploymentStacks": "./src/api/deploymentStacks/index.ts"
  "./api/deploymentStacksWhatIfResultsAtManagementGroup": "./src/api/deploymentStacksWhatIfResultsAtManagementGroup/index.ts"
  "./api/deploymentStacksWhatIfResultsAtSubscription": "./src/api/deploymentStacksWhatIfResultsAtSubscription/index.ts"
  "./api/deploymentStacksWhatIfResultsAtResourceGroup": "./src/api/deploymentStacksWhatIfResultsAtResourceGroup/index.ts"
  "./models": "./src/models/index.ts"
<<<<<<< HEAD

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"
  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
    moduleType: commonjs
=======
>>>>>>> origin/main
