extends: ../../../warp.base.config.yml
exports:
  "./api": "./src/api/index.ts"
  "./api/deploymentStacks": "./src/api/deploymentStacks/index.ts"
  "./api/deploymentStacksWhatIfResultsAtManagementGroup": "./src/api/deploymentStacksWhatIfResultsAtManagementGroup/index.ts"
  "./api/deploymentStacksWhatIfResultsAtSubscription": "./src/api/deploymentStacksWhatIfResultsAtSubscription/index.ts"
  "./api/deploymentStacksWhatIfResultsAtResourceGroup": "./src/api/deploymentStacksWhatIfResultsAtResourceGroup/index.ts"
  "./models": "./src/models/index.ts"
