extends: ../../../warp.base.config.yml
exports:
  "./api": "./src/api/index.ts"
  "./api/operatorApiPlans": "./src/api/operatorApiPlans/index.ts"
  "./api/operatorApiConnections": "./src/api/operatorApiConnections/index.ts"
  "./api/gateways": "./src/api/gateways/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"
