/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";


/**
 * Contains the possible cases for ResponseBase.
 */
export type ResponseBaseUnion = ResponseBase | IdentifiableUnion;

/**
 * @interface
 * An interface representing ResponseBase.
 * Response base
 *
 */
export interface ResponseBase {
  /**
   * @member {string} _type Polymorphic Discriminator
   */
  _type: "ResponseBase";
}

/**
 * Contains the possible cases for Identifiable.
 */
export type IdentifiableUnion = Identifiable | ResponseUnion;

/**
 * @interface
 * An interface representing Identifiable.
 * Defines the identity of a resource.
 *
 */
export interface Identifiable {
  /**
   * @member {string} _type Polymorphic Discriminator
   */
  _type: "Identifiable";
  /**
   * @member {string} [id] A String identifier.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly id?: string;
}

/**
 * Contains the possible cases for Response.
 */
export type ResponseUnion = Response | AnswerUnion | ThingUnion | ErrorResponse;

/**
 * @interface
 * An interface representing Response.
 * Defines a response. All schemas that could be returned at the root of a
 * response should inherit from this
 *
 */
export interface Response {
  /**
   * @member {string} _type Polymorphic Discriminator
   */
  _type: "Response";
  /**
   * @member {string} [id] A String identifier.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly id?: string;
  /**
   * @member {string} [readLink] The URL that returns this resource.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly readLink?: string;
  /**
   * @member {string} [webSearchUrl] The URL To Bing's search result for this
   * item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly webSearchUrl?: string;
}

/**
 * Contains the possible cases for Thing.
 */
export type ThingUnion = Thing | CreativeWorkUnion;

/**
 * @interface
 * An interface representing Thing.
 * Defines a thing.
 *
 */
export interface Thing {
  /**
   * @member {string} _type Polymorphic Discriminator
   */
  _type: "Thing";
  /**
   * @member {string} [id] A String identifier.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly id?: string;
  /**
   * @member {string} [readLink] The URL that returns this resource.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly readLink?: string;
  /**
   * @member {string} [webSearchUrl] The URL To Bing's search result for this
   * item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly webSearchUrl?: string;
  /**
   * @member {string} [name] The name of the thing represented by this object.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly name?: string;
  /**
   * @member {string} [url] The URL to get more information about the thing
   * represented by this object.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly url?: string;
  /**
   * @member {ImageObject} [image] An image of the item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly image?: ImageObject;
  /**
   * @member {string} [description] A short description of the item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly description?: string;
  /**
   * @member {string} [alternateName] An alias for the item
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly alternateName?: string;
  /**
   * @member {string} [bingId] An ID that uniquely identifies this item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly bingId?: string;
}

/**
 * Contains the possible cases for CreativeWork.
 */
export type CreativeWorkUnion = CreativeWork | MediaObjectUnion | WebPage;

/**
 * @interface
 * An interface representing CreativeWork.
 * The most generic kind of creative work, including books, movies,
 * photographs, software programs, etc.
 *
 */
export interface CreativeWork {
  /**
   * @member {string} _type Polymorphic Discriminator
   */
  _type: "CreativeWork";
  /**
   * @member {string} [id] A String identifier.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly id?: string;
  /**
   * @member {string} [readLink] The URL that returns this resource.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly readLink?: string;
  /**
   * @member {string} [webSearchUrl] The URL To Bing's search result for this
   * item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly webSearchUrl?: string;
  /**
   * @member {string} [name] The name of the thing represented by this object.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly name?: string;
  /**
   * @member {string} [url] The URL to get more information about the thing
   * represented by this object.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly url?: string;
  /**
   * @member {ImageObject} [image] An image of the item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly image?: ImageObject;
  /**
   * @member {string} [description] A short description of the item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly description?: string;
  /**
   * @member {string} [alternateName] An alias for the item
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly alternateName?: string;
  /**
   * @member {string} [bingId] An ID that uniquely identifies this item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly bingId?: string;
  /**
   * @member {string} [thumbnailUrl] The URL to a thumbnail of the item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly thumbnailUrl?: string;
  /**
   * @member {ThingUnion[]} [provider] The source of the creative work.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly provider?: ThingUnion[];
  /**
   * @member {string} [text] Text content of this creative work
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly text?: string;
}

/**
 * Contains the possible cases for MediaObject.
 */
export type MediaObjectUnion = MediaObject | ImageObject;

/**
 * @interface
 * An interface representing MediaObject.
 * Defines a media object.
 *
 */
export interface MediaObject {
  /**
   * @member {string} _type Polymorphic Discriminator
   */
  _type: "MediaObject";
  /**
   * @member {string} [id] A String identifier.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly id?: string;
  /**
   * @member {string} [readLink] The URL that returns this resource.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly readLink?: string;
  /**
   * @member {string} [webSearchUrl] The URL To Bing's search result for this
   * item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly webSearchUrl?: string;
  /**
   * @member {string} [name] The name of the thing represented by this object.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly name?: string;
  /**
   * @member {string} [url] The URL to get more information about the thing
   * represented by this object.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly url?: string;
  /**
   * @member {ImageObject} [image] An image of the item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly image?: ImageObject;
  /**
   * @member {string} [description] A short description of the item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly description?: string;
  /**
   * @member {string} [alternateName] An alias for the item
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly alternateName?: string;
  /**
   * @member {string} [bingId] An ID that uniquely identifies this item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly bingId?: string;
  /**
   * @member {string} [thumbnailUrl] The URL to a thumbnail of the item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly thumbnailUrl?: string;
  /**
   * @member {ThingUnion[]} [provider] The source of the creative work.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly provider?: ThingUnion[];
  /**
   * @member {string} [text] Text content of this creative work
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly text?: string;
  /**
   * @member {string} [contentUrl] Original URL to retrieve the source (file)
   * for the media object (e.g the source URL for the image).
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly contentUrl?: string;
  /**
   * @member {string} [hostPageUrl] URL of the page that hosts the media
   * object.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly hostPageUrl?: string;
  /**
   * @member {string} [contentSize] Size of the media object content (use
   * format "value unit" e.g "1024 B").
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly contentSize?: string;
  /**
   * @member {string} [encodingFormat] Encoding format (e.g mp3, mp4, jpeg,
   * etc).
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly encodingFormat?: string;
  /**
   * @member {string} [hostPageDisplayUrl] Display URL of the page that hosts
   * the media object.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly hostPageDisplayUrl?: string;
  /**
   * @member {number} [width] The width of the media object, in pixels.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly width?: number;
  /**
   * @member {number} [height] The height of the media object, in pixels.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly height?: number;
}

/**
 * @interface
 * An interface representing ImageObject.
 * Defines an image
 *
 */
export interface ImageObject {
  /**
   * @member {string} _type Polymorphic Discriminator
   */
  _type: "ImageObject";
  /**
   * @member {string} [id] A String identifier.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly id?: string;
  /**
   * @member {string} [readLink] The URL that returns this resource.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly readLink?: string;
  /**
   * @member {string} [webSearchUrl] The URL To Bing's search result for this
   * item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly webSearchUrl?: string;
  /**
   * @member {string} [name] The name of the thing represented by this object.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly name?: string;
  /**
   * @member {string} [url] The URL to get more information about the thing
   * represented by this object.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly url?: string;
  /**
   * @member {ImageObject} [image] An image of the item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly image?: ImageObject;
  /**
   * @member {string} [description] A short description of the item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly description?: string;
  /**
   * @member {string} [alternateName] An alias for the item
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly alternateName?: string;
  /**
   * @member {string} [bingId] An ID that uniquely identifies this item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly bingId?: string;
  /**
   * @member {string} [thumbnailUrl] The URL to a thumbnail of the item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly thumbnailUrl?: string;
  /**
   * @member {ThingUnion[]} [provider] The source of the creative work.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly provider?: ThingUnion[];
  /**
   * @member {string} [text] Text content of this creative work
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly text?: string;
  /**
   * @member {string} [contentUrl] Original URL to retrieve the source (file)
   * for the media object (e.g the source URL for the image).
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly contentUrl?: string;
  /**
   * @member {string} [hostPageUrl] URL of the page that hosts the media
   * object.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly hostPageUrl?: string;
  /**
   * @member {string} [contentSize] Size of the media object content (use
   * format "value unit" e.g "1024 B").
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly contentSize?: string;
  /**
   * @member {string} [encodingFormat] Encoding format (e.g mp3, mp4, jpeg,
   * etc).
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly encodingFormat?: string;
  /**
   * @member {string} [hostPageDisplayUrl] Display URL of the page that hosts
   * the media object.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly hostPageDisplayUrl?: string;
  /**
   * @member {number} [width] The width of the media object, in pixels.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly width?: number;
  /**
   * @member {number} [height] The height of the media object, in pixels.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly height?: number;
  /**
   * @member {ImageObject} [thumbnail] The URL to a thumbnail of the image
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly thumbnail?: ImageObject;
  /**
   * @member {string} [imageInsightsToken] The token that you use in a
   * subsequent call to the Image Search API to get additional information
   * about the image. For information about using this token, see the
   * insightsToken query parameter.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly imageInsightsToken?: string;
  /**
   * @member {string} [imageId] Unique Id for the image
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly imageId?: string;
  /**
   * @member {string} [accentColor] A three-byte hexadecimal number that
   * represents the color that dominates the image. Use the color as the
   * temporary background in your client until the image is loaded.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly accentColor?: string;
  /**
   * @member {string} [visualWords] Visual representation of the image. Used
   * for getting more sizes
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly visualWords?: string;
}

/**
 * Contains the possible cases for Answer.
 */
export type AnswerUnion = Answer | SearchResultsAnswerUnion;

/**
 * @interface
 * An interface representing Answer.
 * Defines an answer.
 *
 */
export interface Answer {
  /**
   * @member {string} _type Polymorphic Discriminator
   */
  _type: "Answer";
  /**
   * @member {string} [id] A String identifier.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly id?: string;
  /**
   * @member {string} [readLink] The URL that returns this resource.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly readLink?: string;
  /**
   * @member {string} [webSearchUrl] The URL To Bing's search result for this
   * item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly webSearchUrl?: string;
}

/**
 * Contains the possible cases for SearchResultsAnswer.
 */
export type SearchResultsAnswerUnion = SearchResultsAnswer | Images;

/**
 * @interface
 * An interface representing SearchResultsAnswer.
 * Defines a search result answer.
 *
 */
export interface SearchResultsAnswer {
  /**
   * @member {string} _type Polymorphic Discriminator
   */
  _type: "SearchResultsAnswer";
  /**
   * @member {string} [id] A String identifier.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly id?: string;
  /**
   * @member {string} [readLink] The URL that returns this resource.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly readLink?: string;
  /**
   * @member {string} [webSearchUrl] The URL To Bing's search result for this
   * item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly webSearchUrl?: string;
  /**
   * @member {number} [totalEstimatedMatches] The estimated number of webpages
   * that are relevant to the query. Use this number along with the count and
   * offset query parameters to page the results.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly totalEstimatedMatches?: number;
}

/**
 * @interface
 * An interface representing Images.
 * Defines an image answer
 *
 */
export interface Images {
  /**
   * @member {string} _type Polymorphic Discriminator
   */
  _type: "Images";
  /**
   * @member {string} [id] A String identifier.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly id?: string;
  /**
   * @member {string} [readLink] The URL that returns this resource.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly readLink?: string;
  /**
   * @member {string} [webSearchUrl] The URL To Bing's search result for this
   * item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly webSearchUrl?: string;
  /**
   * @member {number} [totalEstimatedMatches] The estimated number of webpages
   * that are relevant to the query. Use this number along with the count and
   * offset query parameters to page the results.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly totalEstimatedMatches?: number;
  /**
   * @member {number} [nextOffset] Used as part of deduping. Tells client the
   * next offset that client should use in the next pagination request
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly nextOffset?: number;
  /**
   * @member {ImageObject[]} value A list of image objects that are relevant to
   * the query. If there are no results, the List is empty.
   */
  value: ImageObject[];
}

/**
 * @interface
 * An interface representing Query.
 * Defines a search query.
 *
 */
export interface Query {
  /**
   * @member {string} text The query string. Use this string as the query term
   * in a new search request.
   */
  text: string;
  /**
   * @member {string} [displayText] The display version of the query term. This
   * version of the query term may contain special characters that highlight
   * the search term found in the query string. The string contains the
   * highlighting characters only if the query enabled hit highlighting
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly displayText?: string;
  /**
   * @member {string} [webSearchUrl] The URL that takes the user to the Bing
   * search results page for the query.Only related search results include this
   * field.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly webSearchUrl?: string;
  /**
   * @member {string} [searchLink] The URL that you use to get the results of
   * the related search. Before using the URL, you must append query parameters
   * as appropriate and include the Ocp-Apim-Subscription-Key header. Use this
   * URL if you're displaying the results in your own user interface.
   * Otherwise, use the webSearchUrl URL.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly searchLink?: string;
  /**
   * @member {ImageObject} [thumbnail] The URL to a thumbnail of a related
   * image.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly thumbnail?: ImageObject;
}

/**
 * @interface
 * An interface representing ErrorModel.
 * Defines the error that occurred.
 *
 */
export interface ErrorModel {
  /**
   * @member {ErrorCode} code The error code that identifies the category of
   * error. Possible values include: 'None', 'ServerError', 'InvalidRequest',
   * 'RateLimitExceeded', 'InvalidAuthorization', 'InsufficientAuthorization'.
   * Default value: 'None' .
   */
  code: ErrorCode;
  /**
   * @member {ErrorSubCode} [subCode] The error code that further helps to
   * identify the error. Possible values include: 'UnexpectedError',
   * 'ResourceError', 'NotImplemented', 'ParameterMissing',
   * 'ParameterInvalidValue', 'HttpNotAllowed', 'Blocked',
   * 'AuthorizationMissing', 'AuthorizationRedundancy',
   * 'AuthorizationDisabled', 'AuthorizationExpired'
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly subCode?: ErrorSubCode;
  /**
   * @member {string} message A description of the error.
   */
  message: string;
  /**
   * @member {string} [moreDetails] A description that provides additional
   * information about the error.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly moreDetails?: string;
  /**
   * @member {string} [parameter] The parameter in the request that caused the
   * error.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly parameter?: string;
  /**
   * @member {string} [value] The parameter's value in the request that was not
   * valid.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly value?: string;
}

/**
 * @interface
 * An interface representing ErrorResponse.
 * The top-level response that represents a failed request.
 *
 */
export interface ErrorResponse {
  /**
   * @member {string} _type Polymorphic Discriminator
   */
  _type: "ErrorResponse";
  /**
   * @member {string} [id] A String identifier.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly id?: string;
  /**
   * @member {string} [readLink] The URL that returns this resource.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly readLink?: string;
  /**
   * @member {string} [webSearchUrl] The URL To Bing's search result for this
   * item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly webSearchUrl?: string;
  /**
   * @member {ErrorModel[]} errors A list of errors that describe the reasons
   * why the request failed.
   */
  errors: ErrorModel[];
}

/**
 * @interface
 * An interface representing WebPage.
 * Defines a webpage that is relevant to the query.
 *
 */
export interface WebPage {
  /**
   * @member {string} _type Polymorphic Discriminator
   */
  _type: "WebPage";
  /**
   * @member {string} [id] A String identifier.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly id?: string;
  /**
   * @member {string} [readLink] The URL that returns this resource.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly readLink?: string;
  /**
   * @member {string} [webSearchUrl] The URL To Bing's search result for this
   * item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly webSearchUrl?: string;
  /**
   * @member {string} [name] The name of the thing represented by this object.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly name?: string;
  /**
   * @member {string} [url] The URL to get more information about the thing
   * represented by this object.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly url?: string;
  /**
   * @member {ImageObject} [image] An image of the item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly image?: ImageObject;
  /**
   * @member {string} [description] A short description of the item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly description?: string;
  /**
   * @member {string} [alternateName] An alias for the item
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly alternateName?: string;
  /**
   * @member {string} [bingId] An ID that uniquely identifies this item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly bingId?: string;
  /**
   * @member {string} [thumbnailUrl] The URL to a thumbnail of the item.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly thumbnailUrl?: string;
  /**
   * @member {ThingUnion[]} [provider] The source of the creative work.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly provider?: ThingUnion[];
  /**
   * @member {string} [text] Text content of this creative work
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly text?: string;
}

/**
 * @interface
 * An interface representing CustomImageSearchClientOptions.
 * @extends ServiceClientOptions
 */
export interface CustomImageSearchClientOptions extends ServiceClientOptions {
  /**
   * @member {string} [endpoint] Supported Cognitive Services endpoints
   * (protocol and hostname, for example:
   * "https://westus.api.cognitive.microsoft.com",
   * "https://api.cognitive.microsoft.com"). Default value:
   * 'https://api.cognitive.microsoft.com' .
   */
  endpoint?: string;
}

/**
 * @interface
 * An interface representing CustomInstanceImageSearchOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CustomInstanceImageSearchOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [acceptLanguage] A comma-delimited list of one or more
   * languages to use for user interface strings. The list is in decreasing
   * order of preference. For additional information, including expected
   * format, see
   * [RFC2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html). This
   * header and the
   * [setLang](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#setlang)
   * query parameter are mutually exclusive; do not specify both. If you set
   * this header, you must also specify the
   * [cc](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#cc)
   * query parameter. To determine the market to return results for, Bing uses
   * the first supported language it finds from the list and combines it with
   * the cc parameter value. If the list does not include a supported language,
   * Bing finds the closest language and market that supports the request or it
   * uses an aggregated or default market for the results. To determine the
   * market that Bing used, see the BingAPIs-Market header. Use this header and
   * the cc query parameter only if you specify multiple languages. Otherwise,
   * use the
   * [mkt](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#mkt)
   * and
   * [setLang](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#setlang)
   * query parameters. A user interface string is a string that's used as a
   * label in a user interface. There are few user interface strings in the
   * JSON response objects. Any links to Bing.com properties in the response
   * objects apply the specified language.
   */
  acceptLanguage?: string;
  /**
   * @member {string} [userAgent] The user agent originating the request. Bing
   * uses the user agent to provide mobile users with an optimized experience.
   * Although optional, you are encouraged to always specify this header. The
   * user-agent should be the same string that any commonly used browser sends.
   * For information about user agents, see [RFC
   * 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html). The
   * following are examples of user-agent strings. Windows Phone: Mozilla/5.0
   * (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0;
   * ARM; Touch; NOKIA; Lumia 822). Android: Mozilla / 5.0 (Linux; U; Android
   * 2.3.5; en - us; SCH - I500 Build / GINGERBREAD) AppleWebKit / 533.1
   * (KHTML; like Gecko) Version / 4.0 Mobile Safari / 533.1. iPhone: Mozilla /
   * 5.0 (iPhone; CPU iPhone OS 6_1 like Mac OS X) AppleWebKit / 536.26 (KHTML;
   * like Gecko) Mobile / 10B142 iPhone4; 1 BingWeb / 3.03.1428.20120423. PC:
   * Mozilla / 5.0 (Windows NT 6.3; WOW64; Trident / 7.0; Touch; rv:11.0) like
   * Gecko. iPad: Mozilla / 5.0 (iPad; CPU OS 7_0 like Mac OS X) AppleWebKit /
   * 537.51.1 (KHTML, like Gecko) Version / 7.0 Mobile / 11A465 Safari /
   * 9537.53
   */
  userAgent?: string;
  /**
   * @member {string} [clientId] Bing uses this header to provide users with
   * consistent behavior across Bing API calls. Bing often flights new features
   * and improvements, and it uses the client ID as a key for assigning traffic
   * on different flights. If you do not use the same client ID for a user
   * across multiple requests, then Bing may assign the user to multiple
   * conflicting flights. Being assigned to multiple conflicting flights can
   * lead to an inconsistent user experience. For example, if the second
   * request has a different flight assignment than the first, the experience
   * may be unexpected. Also, Bing can use the client ID to tailor web results
   * to that client ID’s search history, providing a richer experience for the
   * user. Bing also uses this header to help improve result rankings by
   * analyzing the activity generated by a client ID. The relevance
   * improvements help with better quality of results delivered by Bing APIs
   * and in turn enables higher click-through rates for the API consumer.
   * IMPORTANT: Although optional, you should consider this header required.
   * Persisting the client ID across multiple requests for the same end user
   * and device combination enables 1) the API consumer to receive a consistent
   * user experience, and 2) higher click-through rates via better quality of
   * results from the Bing APIs. Each user that uses your application on the
   * device must have a unique, Bing generated client ID. If you do not include
   * this header in the request, Bing generates an ID and returns it in the
   * X-MSEdge-ClientID response header. The only time that you should NOT
   * include this header in a request is the first time the user uses your app
   * on that device. Use the client ID for each Bing API request that your app
   * makes for this user on the device. Persist the client ID. To persist the
   * ID in a browser app, use a persistent HTTP cookie to ensure the ID is used
   * across all sessions. Do not use a session cookie. For other apps such as
   * mobile apps, use the device's persistent storage to persist the ID. The
   * next time the user uses your app on that device, get the client ID that
   * you persisted. Bing responses may or may not include this header. If the
   * response includes this header, capture the client ID and use it for all
   * subsequent Bing requests for the user on that device. If you include the
   * X-MSEdge-ClientID, you must not include cookies in the request.
   */
  clientId?: string;
  /**
   * @member {string} [clientIp] The IPv4 or IPv6 address of the client device.
   * The IP address is used to discover the user's location. Bing uses the
   * location information to determine safe search behavior. Although optional,
   * you are encouraged to always specify this header and the X-Search-Location
   * header. Do not obfuscate the address (for example, by changing the last
   * octet to 0). Obfuscating the address results in the location not being
   * anywhere near the device's actual location, which may result in Bing
   * serving erroneous results.
   */
  clientIp?: string;
  /**
   * @member {string} [location] A semicolon-delimited list of key/value pairs
   * that describe the client's geographical location. Bing uses the location
   * information to determine safe search behavior and to return relevant local
   * content. Specify the key/value pair as <key>:<value>. The following are
   * the keys that you use to specify the user's location. lat (required): The
   * latitude of the client's location, in degrees. The latitude must be
   * greater than or equal to -90.0 and less than or equal to +90.0. Negative
   * values indicate southern latitudes and positive values indicate northern
   * latitudes. long (required): The longitude of the client's location, in
   * degrees. The longitude must be greater than or equal to -180.0 and less
   * than or equal to +180.0. Negative values indicate western longitudes and
   * positive values indicate eastern longitudes. re (required): The radius, in
   * meters, which specifies the horizontal accuracy of the coordinates. Pass
   * the value returned by the device's location service. Typical values might
   * be 22m for GPS/Wi-Fi, 380m for cell tower triangulation, and 18,000m for
   * reverse IP lookup. ts (optional): The UTC UNIX timestamp of when the
   * client was at the location. (The UNIX timestamp is the number of seconds
   * since January 1, 1970.) head (optional): The client's relative heading or
   * direction of travel. Specify the direction of travel as degrees from 0
   * through 360, counting clockwise relative to true north. Specify this key
   * only if the sp key is nonzero. sp (optional): The horizontal velocity
   * (speed), in meters per second, that the client device is traveling. alt
   * (optional): The altitude of the client device, in meters. are (optional):
   * The radius, in meters, that specifies the vertical accuracy of the
   * coordinates. Specify this key only if you specify the alt key. Although
   * many of the keys are optional, the more information that you provide, the
   * more accurate the location results are. Although optional, you are
   * encouraged to always specify the user's geographical location. Providing
   * the location is especially important if the client's IP address does not
   * accurately reflect the user's physical location (for example, if the
   * client uses VPN). For optimal results, you should include this header and
   * the X-MSEdge-ClientIP header, but at a minimum, you should include this
   * header.
   */
  location?: string;
  /**
   * @member {ImageAspect} [aspect] Filter images by the following aspect
   * ratios. All: Do not filter by aspect.Specifying this value is the same as
   * not specifying the aspect parameter. Square: Return images with standard
   * aspect ratio. Wide: Return images with wide screen aspect ratio. Tall:
   * Return images with tall aspect ratio. Possible values include: 'All',
   * 'Square', 'Wide', 'Tall'
   */
  aspect?: ImageAspect;
  /**
   * @member {ImageColor} [color] Filter images by the following color options.
   * ColorOnly: Return color images. Monochrome: Return black and white images.
   * Return images with one of the following dominant colors: Black, Blue,
   * Brown, Gray, Green, Orange, Pink, Purple, Red, Teal, White, Yellow.
   * Possible values include: 'ColorOnly', 'Monochrome', 'Black', 'Blue',
   * 'Brown', 'Gray', 'Green', 'Orange', 'Pink', 'Purple', 'Red', 'Teal',
   * 'White', 'Yellow'
   */
  color?: ImageColor;
  /**
   * @member {string} [countryCode] A 2-character country code of the country
   * where the results come from. For a list of possible values, see [Market
   * Codes](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#market-codes).
   * If you set this parameter, you must also specify the
   * [Accept-Language](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#acceptlanguage)
   * header. Bing uses the first supported language it finds from the languages
   * list, and combine that language with the country code that you specify to
   * determine the market to return results for. If the languages list does not
   * include a supported language, Bing finds the closest language and market
   * that supports the request, or it may use an aggregated or default market
   * for the results instead of a specified one. You should use this query
   * parameter and the Accept-Language query parameter only if you specify
   * multiple languages; otherwise, you should use the mkt and setLang query
   * parameters. This parameter and the
   * [mkt](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#mkt)
   * query parameter are mutually exclusive—do not specify both.
   */
  countryCode?: string;
  /**
   * @member {number} [count] The number of images to return in the response.
   * The actual number delivered may be less than requested. The default is 35.
   * The maximum value is 150. You use this parameter along with the offset
   * parameter to page results.For example, if your user interface displays 20
   * images per page, set count to 20 and offset to 0 to get the first page of
   * results.For each subsequent page, increment offset by 20 (for example, 0,
   * 20, 40). Use this parameter only with the Image Search API.Do not specify
   * this parameter when calling the Insights, Trending Images, or Web Search
   * APIs.
   */
  count?: number;
  /**
   * @member {Freshness} [freshness] Filter images by the following discovery
   * options. Day: Return images discovered by Bing within the last 24 hours.
   * Week: Return images discovered by Bing within the last 7 days. Month:
   * Return images discovered by Bing within the last 30 days. Possible values
   * include: 'Day', 'Week', 'Month'
   */
  freshness?: Freshness;
  /**
   * @member {number} [height] Filter images that have the specified height, in
   * pixels. You may use this filter with the size filter to return small
   * images that have a height of 150 pixels.
   */
  height?: number;
  /**
   * @member {string} [id] An ID that uniquely identifies an image. Use this
   * parameter to ensure that the specified image is the first image in the
   * list of images that Bing returns. The
   * [Image](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#image)
   * object's imageId field contains the ID that you set this parameter to.
   */
  id?: string;
  /**
   * @member {ImageContent} [imageContent] Filter images by the following
   * content types. Face: Return images that show only a person's face.
   * Portrait: Return images that show only a person's head and shoulders.
   * Possible values include: 'Face', 'Portrait'
   */
  imageContent?: ImageContent;
  /**
   * @member {ImageType} [imageType] Filter images by the following image
   * types. AnimatedGif: Return only animated GIFs. Clipart: Return only clip
   * art images. Line: Return only line drawings. Photo: Return only
   * photographs(excluding line drawings, animated Gifs, and clip art).
   * Shopping: Return only images that contain items where Bing knows of a
   * merchant that is selling the items. This option is valid in the en - US
   * market only.Transparent: Return only images with a transparent background.
   * Possible values include: 'AnimatedGif', 'Clipart', 'Line', 'Photo',
   * 'Shopping', 'Transparent'
   */
  imageType?: ImageType;
  /**
   * @member {ImageLicense} [license] Filter images by the following license
   * types. All: Do not filter by license type.Specifying this value is the
   * same as not specifying the license parameter. Any: Return images that are
   * under any license type. The response doesn't include images that do not
   * specify a license or the license is unknown. Public: Return images where
   * the creator has waived their exclusive rights, to the fullest extent
   * allowed by law. Share: Return images that may be shared with others.
   * Changing or editing the image might not be allowed. Also, modifying,
   * sharing, and using the image for commercial purposes might not be allowed.
   * Typically, this option returns the most images. ShareCommercially: Return
   * images that may be shared with others for personal or commercial purposes.
   * Changing or editing the image might not be allowed. Modify: Return images
   * that may be modified, shared, and used. Changing or editing the image
   * might not be allowed. Modifying, sharing, and using the image for
   * commercial purposes might not be allowed. ModifyCommercially: Return
   * images that may be modified, shared, and used for personal or commercial
   * purposes. Typically, this option returns the fewest images. For more
   * information about these license types, see [Filter Images By License
   * Type](http://go.microsoft.com/fwlink/?LinkId=309768). Possible values
   * include: 'All', 'Any', 'Public', 'Share', 'ShareCommercially', 'Modify',
   * 'ModifyCommercially'
   */
  license?: ImageLicense;
  /**
   * @member {string} [market] The market where the results come from.
   * Typically, mkt is the country where the user is making the request from.
   * However, it could be a different country if the user is not located in a
   * country where Bing delivers results. The market must be in the form
   * <language code>-<country code>. For example, en-US. The string is case
   * insensitive. For a list of possible market values, see [Market
   * Codes](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#market-codes).
   * NOTE: If known, you are encouraged to always specify the market.
   * Specifying the market helps Bing route the request and return an
   * appropriate and optimal response. If you specify a market that is not
   * listed in [Market
   * Codes](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#market-codes),
   * Bing uses a best fit market code based on an internal mapping that is
   * subject to change. This parameter and the
   * [cc](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#cc)
   * query parameter are mutually exclusive—do not specify both.
   */
  market?: string;
  /**
   * @member {number} [maxFileSize] Filter images that are less than or equal
   * to the specified file size. The maximum file size that you may specify is
   * 520,192 bytes. If you specify a larger value, the API uses 520,192. It is
   * possible that the response may include images that are slightly larger
   * than the specified maximum. You may specify this filter and minFileSize to
   * filter images within a range of file sizes.
   */
  maxFileSize?: number;
  /**
   * @member {number} [maxHeight] Filter images that have a height that is less
   * than or equal to the specified height. Specify the height in pixels. You
   * may specify this filter and minHeight to filter images within a range of
   * heights. This filter and the height filter are mutually exclusive.
   */
  maxHeight?: number;
  /**
   * @member {number} [maxWidth] Filter images that have a width that is less
   * than or equal to the specified width. Specify the width in pixels. You may
   * specify this filter and maxWidth to filter images within a range of
   * widths. This filter and the width filter are mutually exclusive.
   */
  maxWidth?: number;
  /**
   * @member {number} [minFileSize] Filter images that are greater than or
   * equal to the specified file size. The maximum file size that you may
   * specify is 520,192 bytes. If you specify a larger value, the API uses
   * 520,192. It is possible that the response may include images that are
   * slightly smaller than the specified minimum. You may specify this filter
   * and maxFileSize to filter images within a range of file sizes.
   */
  minFileSize?: number;
  /**
   * @member {number} [minHeight] Filter images that have a height that is
   * greater than or equal to the specified height. Specify the height in
   * pixels. You may specify this filter and maxHeight to filter images within
   * a range of heights. This filter and the height filter are mutually
   * exclusive.
   */
  minHeight?: number;
  /**
   * @member {number} [minWidth] Filter images that have a width that is
   * greater than or equal to the specified width. Specify the width in pixels.
   * You may specify this filter and maxWidth to filter images within a range
   * of widths. This filter and the width filter are mutually exclusive.
   */
  minWidth?: number;
  /**
   * @member {number} [offset] The zero-based offset that indicates the number
   * of images to skip before returning images. The default is 0. The offset
   * should be less than
   * ([totalEstimatedMatches](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#totalestimatedmatches)
   * - count). Use this parameter along with the count parameter to page
   * results. For example, if your user interface displays 20 images per page,
   * set count to 20 and offset to 0 to get the first page of results. For each
   * subsequent page, increment offset by 20 (for example, 0, 20, 40). It is
   * possible for multiple pages to include some overlap in results. To prevent
   * duplicates, see
   * [nextOffset](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#nextoffset).
   * Use this parameter only with the Image API. Do not specify this parameter
   * when calling the Trending Images API or the Web Search API.
   */
  offset?: number;
  /**
   * @member {SafeSearch} [safeSearch] Filter images for adult content. The
   * following are the possible filter values. Off: May return images with
   * adult content. If the request is through the Image Search API, the
   * response includes thumbnail images that are clear (non-fuzzy). However, if
   * the request is through the Web Search API, the response includes thumbnail
   * images that are pixelated (fuzzy). Moderate: If the request is through the
   * Image Search API, the response doesn't include images with adult content.
   * If the request is through the Web Search API, the response may include
   * images with adult content (the thumbnail images are pixelated (fuzzy)).
   * Strict: Do not return images with adult content. The default is Moderate.
   * If the request comes from a market that Bing's adult policy requires that
   * safeSearch is set to Strict, Bing ignores the safeSearch value and uses
   * Strict. If you use the site: query operator, there is the chance that the
   * response may contain adult content regardless of what the safeSearch query
   * parameter is set to. Use site: only if you are aware of the content on the
   * site and your scenario supports the possibility of adult content. Possible
   * values include: 'Off', 'Moderate', 'Strict'
   */
  safeSearch?: SafeSearch;
  /**
   * @member {ImageSize} [size] Filter images by the following sizes. All: Do
   * not filter by size. Specifying this value is the same as not specifying
   * the size parameter. Small: Return images that are less than 200x200
   * pixels. Medium: Return images that are greater than or equal to 200x200
   * pixels but less than 500x500 pixels. Large: Return images that are 500x500
   * pixels or larger. Wallpaper: Return wallpaper images. You may use this
   * parameter along with the height or width parameters. For example, you may
   * use height and size to request small images that are 150 pixels tall.
   * Possible values include: 'All', 'Small', 'Medium', 'Large', 'Wallpaper'
   */
  size?: ImageSize;
  /**
   * @member {string} [setLang] The language to use for user interface strings.
   * Specify the language using the ISO 639-1 2-letter language code. For
   * example, the language code for English is EN. The default is EN (English).
   * Although optional, you should always specify the language. Typically, you
   * set setLang to the same language specified by mkt unless the user wants
   * the user interface strings displayed in a different language. This
   * parameter and the
   * [Accept-Language](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#acceptlanguage)
   * header are mutually exclusive; do not specify both. A user interface
   * string is a string that's used as a label in a user interface. There are
   * few user interface strings in the JSON response objects. Also, any links
   * to Bing.com properties in the response objects apply the specified
   * language.
   */
  setLang?: string;
  /**
   * @member {number} [width] Filter images that have the specified width, in
   * pixels. You may use this filter with the size filter to return small
   * images that have a width of 150 pixels.
   */
  width?: number;
}

/**
 * Defines values for ErrorCode.
 * Possible values include: 'None', 'ServerError', 'InvalidRequest', 'RateLimitExceeded',
 * 'InvalidAuthorization', 'InsufficientAuthorization'
 * @readonly
 * @enum {string}
 */
export type ErrorCode = 'None' | 'ServerError' | 'InvalidRequest' | 'RateLimitExceeded' | 'InvalidAuthorization' | 'InsufficientAuthorization';

/**
 * Defines values for ErrorSubCode.
 * Possible values include: 'UnexpectedError', 'ResourceError', 'NotImplemented',
 * 'ParameterMissing', 'ParameterInvalidValue', 'HttpNotAllowed', 'Blocked',
 * 'AuthorizationMissing', 'AuthorizationRedundancy', 'AuthorizationDisabled',
 * 'AuthorizationExpired'
 * @readonly
 * @enum {string}
 */
export type ErrorSubCode = 'UnexpectedError' | 'ResourceError' | 'NotImplemented' | 'ParameterMissing' | 'ParameterInvalidValue' | 'HttpNotAllowed' | 'Blocked' | 'AuthorizationMissing' | 'AuthorizationRedundancy' | 'AuthorizationDisabled' | 'AuthorizationExpired';

/**
 * Defines values for ImageAspect.
 * Possible values include: 'All', 'Square', 'Wide', 'Tall'
 * @readonly
 * @enum {string}
 */
export type ImageAspect = 'All' | 'Square' | 'Wide' | 'Tall';

/**
 * Defines values for ImageColor.
 * Possible values include: 'ColorOnly', 'Monochrome', 'Black', 'Blue', 'Brown', 'Gray', 'Green',
 * 'Orange', 'Pink', 'Purple', 'Red', 'Teal', 'White', 'Yellow'
 * @readonly
 * @enum {string}
 */
export type ImageColor = 'ColorOnly' | 'Monochrome' | 'Black' | 'Blue' | 'Brown' | 'Gray' | 'Green' | 'Orange' | 'Pink' | 'Purple' | 'Red' | 'Teal' | 'White' | 'Yellow';

/**
 * Defines values for Freshness.
 * Possible values include: 'Day', 'Week', 'Month'
 * @readonly
 * @enum {string}
 */
export type Freshness = 'Day' | 'Week' | 'Month';

/**
 * Defines values for ImageContent.
 * Possible values include: 'Face', 'Portrait'
 * @readonly
 * @enum {string}
 */
export type ImageContent = 'Face' | 'Portrait';

/**
 * Defines values for ImageType.
 * Possible values include: 'AnimatedGif', 'Clipart', 'Line', 'Photo', 'Shopping', 'Transparent'
 * @readonly
 * @enum {string}
 */
export type ImageType = 'AnimatedGif' | 'Clipart' | 'Line' | 'Photo' | 'Shopping' | 'Transparent';

/**
 * Defines values for ImageLicense.
 * Possible values include: 'All', 'Any', 'Public', 'Share', 'ShareCommercially', 'Modify',
 * 'ModifyCommercially'
 * @readonly
 * @enum {string}
 */
export type ImageLicense = 'All' | 'Any' | 'Public' | 'Share' | 'ShareCommercially' | 'Modify' | 'ModifyCommercially';

/**
 * Defines values for SafeSearch.
 * Possible values include: 'Off', 'Moderate', 'Strict'
 * @readonly
 * @enum {string}
 */
export type SafeSearch = 'Off' | 'Moderate' | 'Strict';

/**
 * Defines values for ImageSize.
 * Possible values include: 'All', 'Small', 'Medium', 'Large', 'Wallpaper'
 * @readonly
 * @enum {string}
 */
export type ImageSize = 'All' | 'Small' | 'Medium' | 'Large' | 'Wallpaper';

/**
 * Contains response data for the imageSearch operation.
 */
export type CustomInstanceImageSearchResponse = Images & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Images;
    };
};
