# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/prometheusRuleGroups": "./src/api/prometheusRuleGroups/index.ts"
  "./models": "./src/models/index.ts"
