extends: ../../../warp.base.config.yml
exports:
  "./api": "./src/api/index.ts"
  "./api/agriService": "./src/api/agriService/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"
