// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export type {
  Endpoint,
  EndpointProperties,
  EndpointStatus,
  EndpointMonitorStatus,
  EndpointPropertiesSubnetsItem,
  EndpointPropertiesCustomHeadersItem,
  AlwaysServe,
  ProxyResource,
  Resource,
  CloudError,
  CloudErrorBody,
  DeleteOperationResult,
  Profile,
  ProfileProperties,
  ProfileStatus,
  TrafficRoutingMethod,
  DnsConfig,
  MonitorConfig,
  ProfileMonitorStatus,
  MonitorProtocol,
  MonitorConfigCustomHeadersItem,
  MonitorConfigExpectedStatusCodeRangesItem,
  TrafficViewEnrollmentStatus,
  AllowedEndpointRecordType,
  RecordType,
  TrackedResource,
  CheckTrafficManagerRelativeDnsNameAvailabilityParameters,
  TrafficManagerNameAvailability,
  TrafficManagerGeographicHierarchy,
  GeographicHierarchyProperties,
  Region,
  HeatMapModel,
  HeatMapProperties,
  HeatMapEndpoint,
  TrafficFlow,
  QueryExperience,
  UserMetricsModel,
  UserMetricsProperties,
  EndpointType,
} from "./models.js";
export {
  KnownEndpointStatus,
  KnownEndpointMonitorStatus,
  KnownAlwaysServe,
  KnownProfileStatus,
  KnownTrafficRoutingMethod,
  KnownProfileMonitorStatus,
  KnownMonitorProtocol,
  KnownTrafficViewEnrollmentStatus,
  KnownAllowedEndpointRecordType,
  KnownRecordType,
  KnownVersions,
} from "./models.js";
