# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/serviceGroups": "src/api/serviceGroups/index.ts"
  "./models": "./src/models/index.ts"
