trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - common/tools/js-sdk-release-tools/

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - common/tools/js-sdk-release-tools/

jobs:
  - job: Build
    displayName: 'js-sdk-release-tools validation'

    variables:
      - template: /eng/pipelines/templates/variables/globals.yml
      - template: /eng/pipelines/templates/variables/image.yml
      - name: NodeVersion
        value: '22.x'

    pool:
      name: $(LINUXPOOL)
      demands: ImageOverride -equals $(LINUXVMIMAGE)

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '$(NodeVersion)'
        displayName: 'Install Node.js'

      - script: |
          npm ci
        displayName: 'npm ci'
        workingDirectory: $(System.DefaultWorkingDirectory)/common/tools/js-sdk-release-tools

      - script: |
          npm run format:check
        displayName: 'Prettier format check'
        workingDirectory: $(System.DefaultWorkingDirectory)/common/tools/js-sdk-release-tools

      - script: |
          npm run build
        displayName: 'npm run build'
        workingDirectory: $(System.DefaultWorkingDirectory)/common/tools/js-sdk-release-tools

      - script: |
          npm run test
        displayName: 'npm run test'
        workingDirectory: $(System.DefaultWorkingDirectory)/common/tools/js-sdk-release-tools

      - script: |
          npm pack
        displayName: 'npm pack'
        workingDirectory: $(System.DefaultWorkingDirectory)/common/tools/js-sdk-release-tools

      - script: 'cp azure-tools-js-sdk-release-tools-*.tgz $(Build.ArtifactStagingDirectory)'
        displayName: 'copy to staging dir'
        workingDirectory: $(System.DefaultWorkingDirectory)/common/tools/js-sdk-release-tools

      - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
        parameters:
            ArtifactName: drop
            ArtifactPath: $(Build.ArtifactStagingDirectory)
