#!/bin/sh
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

COMMAND=common/temp/node_modules/.bin/precise-commits

echo --------------------------------------------
echo Starting Git hook: pre-commit

MERGE=$(git rev-parse -q --verify MERGE_HEAD)

if [ ! -z ${MERGE} ]; then
    echo "This is a merge.... Skipping prettying"
    exit
fi

if [ -f $COMMAND ]; then
  echo Invoking $COMMAND
  $COMMAND
else
  echo Command not installed: $COMMAND
fi

echo Finished Git hook: pre-commit
echo --------------------------------------------
