#!/usr/bin/env node

const { execSync } = require("child_process");

function getEnvVariable(name) {
    return process.env[name];
}

function preparePrePushRemote() {
  try {
    execSync("git remote add prepush https://github.com/Azure/azure-sdk-for-js.git");
  } catch (e) {
    console.log("Remote 'prepush' already exists. No need to add it again. Continuing...");
  }  
  execSync("git fetch prepush");
}

function getLocalCommitsNotMerged() {
  // Fetch updates from the remote repository
  execSync("git fetch");
  preparePrePushRemote();

  // Get the list of commits not merged to the remote main branch
  const localCommitsNotMerged = execSync(`git log prepush/main..HEAD --oneline`)
    .toString()
    .trim()
    .split("\n");

  return localCommitsNotMerged.map((localCommit) => localCommit.split(" ")[0].trim());
}

function getListOfFilesForSingleCommit(commit) {
  const files = execSync(`git diff-tree --no-commit-id --name-only ${commit} -r`, {
    encoding: "utf-8",
    stdio: "pipe",
  }).trim();
  return files.split("\n");
}

function getListOfModifiedProjects(commits) {
  const fileSet = new Set();

  commits.map((commit) => {
    const files = getListOfFilesForSingleCommit(commit);
    files.forEach((file) => {
      if (file.startsWith("sdk/")) {
        const extractedFilePath = extractPathPrefix(file);
        fileSet.add(extractedFilePath);
      }
    });
  });

  return Array.from(fileSet);
}

function extractPathPrefix(inputString) {
  const regex = /^(sdk\/[^\/]+\/[^\/]+)\/.*$/;
  const match = inputString.match(regex);

  if (match && match[1]) {
    return match[1];
  } else {
    return null;
  }
}

function executeScript(projectFolderPath, script) {
  const originalCwd = process.cwd();
  let err = "";
  try {
    // Change directory to the project folder
    process.chdir(projectFolderPath);

    const output = execSync(`${script} 2>&1`, {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    });
  } catch (error) {
    err = error.stdout.toString();
  } finally {
    process.chdir(originalCwd);
  }
  return err;
}

async function execute(listOfModifiedProjects, check_script, fix_script) {
  const errors = [];
  listOfModifiedProjects.forEach((projectFolderPath) => {
    if (projectFolderPath && projectFolderPath.trim() != "") {
      console.log(`Checking the format for the project: ${projectFolderPath}`);
      const error = executeScript(projectFolderPath, check_script);
      if (error !== "") {
        errors.push({
          project: projectFolderPath,
          err: error,
        });
      }
    }
  });

  if (errors.length != 0) {
    console.log(`You have the following errors in your code.`);
    console.log();
    errors.forEach((error) => {
      console.log(`============================`);
      console.log(`Project: ${error.project}`);
      console.log(`Errors: ${error.err}`);
      console.log(`============================`);
    });

    console.log(
      `\nThis will cause a CI Failure. Fixing it now. Please commit the fixes before pushing the changes.........\n`,
    );

    listOfModifiedProjects.forEach((projectFolderPath) => {
      executeScript(projectFolderPath, fix_script);
    });

    return true;
  }
  return false;
}

console.log("Running the Pre Push Checks on your commits. You could skip these checks by setting SKIP_PREPUSH_CHECKS to true.\n");

async function main() {
  const skipPrePushChecks = getEnvVariable('SKIP_PREPUSH_CHECKS');
  if (skipPrePushChecks !== undefined && skipPrePushChecks.trim().toLowerCase() === 'true') {
    console.log("Skipping pre-push checks as SKIP_PREPUSH_CHECKS is set to true");
    process.exit(0);
  }
  const localCommits = getLocalCommitsNotMerged();
  if (localCommits.length != 0 && localCommits[0].trim() == "") {
    console.log("No local commits to push");
    process.exit(0);
  }
  const listOfModifiedProjects = getListOfModifiedProjects(localCommits);
  const abortStatus = await execute(listOfModifiedProjects, "rushx check-format", "rushx format");
  if (abortStatus) {
    process.exit(1);
  }
}

main();
