# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/privateLinkScopes": "src/api/privateLinkScopes/index.ts"
  "./api/privateEndpointConnections": "src/api/privateEndpointConnections/index.ts"
  "./api/privateLinkResources": "src/api/privateLinkResources/index.ts"
  "./models": "./src/models/index.ts"
