# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/privateLinkResources": "./src/api/privateLinkResources/index.ts"
  "./api/privateEndpointConnections": "./src/api/privateEndpointConnections/index.ts"
  "./api/informationalOperations": "./src/api/informationalOperations/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./api/fileShareSnapshots": "./src/api/fileShareSnapshots/index.ts"
  "./api/fileShares": "./src/api/fileShares/index.ts"
  "./models": "./src/models/index.ts"
