exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/guestAgents": "./src/api/guestAgents/index.ts"
  "./api/attestationStatuses": "./src/api/attestationStatuses/index.ts"
  "./api/hybridIdentityMetadata": "./src/api/hybridIdentityMetadata/index.ts"
  "./api/virtualMachineInstances": "./src/api/virtualMachineInstances/index.ts"
  "./api/virtualHardDisks": "./src/api/virtualHardDisks/index.ts"
  "./api/storageContainers": "./src/api/storageContainers/index.ts"
  "./api/securityRules": "./src/api/securityRules/index.ts"
  "./api/networkSecurityGroups": "./src/api/networkSecurityGroups/index.ts"
  "./api/networkInterfaces": "./src/api/networkInterfaces/index.ts"
  "./api/marketplaceGalleryImages": "./src/api/marketplaceGalleryImages/index.ts"
  "./api/logicalNetworks": "./src/api/logicalNetworks/index.ts"
  "./api/galleryImages": "./src/api/galleryImages/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"
  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
