# warp.config.yml — build configuration

exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/indexes": "src/api/indexes/index.ts"
  "./api/deployments": "src/api/deployments/index.ts"
  "./api/datasets": "src/api/datasets/index.ts"
  "./api/connections": "src/api/connections/index.ts"
  "./api/evaluationRules": "src/api/evaluationRules/index.ts"
  "./api/agents": "src/api/agents/index.ts"
  "./api/beta/toolboxes": "src/api/beta/toolboxes/index.ts"
  "./api/beta/schedules": "src/api/beta/schedules/index.ts"
  "./api/beta/redTeams": "src/api/beta/redTeams/index.ts"
  "./api/beta/memoryStores": "src/api/beta/memoryStores/index.ts"
  "./api/beta/insights": "src/api/beta/insights/index.ts"
  "./api/beta/evaluators": "src/api/beta/evaluators/index.ts"
  "./api/beta/evaluationTaxonomies": "src/api/beta/evaluationTaxonomies/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
    polyfillSuffix: "-browser"

  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
    polyfillSuffix: "-react-native"

  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"

  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
