# warp.config.yml — build configuration

exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/applicationGroup": "./src/api/applicationGroup/index.ts"
  "./api/schemaRegistry": "./src/api/schemaRegistry/index.ts"
  "./api/networkSecurityPerimeterConfiguration": "./src/api/networkSecurityPerimeterConfiguration/index.ts"
  "./api/privateLinkResources": "./src/api/privateLinkResources/index.ts"
  "./api/namespaces": "./src/api/namespaces/index.ts"
  "./api/configuration": "./src/api/configuration/index.ts"
  "./api/consumerGroups": "./src/api/consumerGroups/index.ts"
  "./api/networkSecurityPerimeterConfigurations": "./src/api/networkSecurityPerimeterConfigurations/index.ts"
  "./api/privateEndpointConnections": "./src/api/privateEndpointConnections/index.ts"
  "./api/eventHubs": "./src/api/eventHubs/index.ts"
  "./api/disasterRecoveryConfigs": "./src/api/disasterRecoveryConfigs/index.ts"
  "./api/clusters": "./src/api/clusters/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "./config/tsconfig.src.browser.json"

  - name: esm
    condition: import
    tsconfig: "./config/tsconfig.src.esm.json"

  - name: commonjs
    condition: require
    tsconfig: "./config/tsconfig.src.cjs.json"
    moduleType: commonjs
