# warp.config.yml — build configuration

exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/usages": "./src/api/usages/index.ts"
  "./api/serviceTagInformationOperations": "./src/api/serviceTagInformationOperations/index.ts"
  "./api/serviceTags": "./src/api/serviceTags/index.ts"
  "./api/bgpServiceCommunities": "./src/api/bgpServiceCommunities/index.ts"
  "./api/availablePrivateEndpointTypes": "./src/api/availablePrivateEndpointTypes/index.ts"
  "./api/networkSecurityPerimeterServiceTags": "./src/api/networkSecurityPerimeterServiceTags/index.ts"
  "./api/networkSecurityPerimeterOperationStatuses": "./src/api/networkSecurityPerimeterOperationStatuses/index.ts"
  "./api/networkSecurityPerimeterAssociableResourceTypes": "./src/api/networkSecurityPerimeterAssociableResourceTypes/index.ts"
  "./api/expressRouteServiceProviders": "./src/api/expressRouteServiceProviders/index.ts"
  "./api/availableEndpointServices": "./src/api/availableEndpointServices/index.ts"
  "./api/azureFirewallFqdnTags": "./src/api/azureFirewallFqdnTags/index.ts"
  "./api/availableServiceAliases": "./src/api/availableServiceAliases/index.ts"
  "./api/availableResourceGroupDelegations": "./src/api/availableResourceGroupDelegations/index.ts"
  "./api/availableDelegations": "./src/api/availableDelegations/index.ts"
  "./api/routingIntentOperations": "./src/api/routingIntentOperations/index.ts"
  "./api/virtualHubIpConfiguration": "./src/api/virtualHubIpConfiguration/index.ts"
  "./api/virtualHubBgpConnections": "./src/api/virtualHubBgpConnections/index.ts"
  "./api/virtualHubBgpConnection": "./src/api/virtualHubBgpConnection/index.ts"
  "./api/expressRouteConnections": "./src/api/expressRouteConnections/index.ts"
  "./api/p2SVpnGateways": "./src/api/p2SVpnGateways/index.ts"
  "./api/natRules": "./src/api/natRules/index.ts"
  "./api/vpnLinkConnections": "./src/api/vpnLinkConnections/index.ts"
  "./api/vpnConnections": "./src/api/vpnConnections/index.ts"
  "./api/virtualHubRouteTableV2S": "./src/api/virtualHubRouteTableV2S/index.ts"
  "./api/hubVirtualNetworkConnections": "./src/api/hubVirtualNetworkConnections/index.ts"
  "./api/configurationPolicyGroups": "./src/api/configurationPolicyGroups/index.ts"
  "./api/vpnServerConfigurationsAssociatedWithVirtualWan": "./src/api/vpnServerConfigurationsAssociatedWithVirtualWan/index.ts"
  "./api/vpnSitesConfiguration": "./src/api/vpnSitesConfiguration/index.ts"
  "./api/serviceAssociationLinks": "./src/api/serviceAssociationLinks/index.ts"
  "./api/resourceNavigationLinks": "./src/api/resourceNavigationLinks/index.ts"
  "./api/routeFilterRules": "./src/api/routeFilterRules/index.ts"
  "./api/privateDnsZoneGroups": "./src/api/privateDnsZoneGroups/index.ts"
  "./api/connectionMonitors": "./src/api/connectionMonitors/index.ts"
  "./api/packetCaptures": "./src/api/packetCaptures/index.ts"
  "./api/inboundSecurityRuleOperations": "./src/api/inboundSecurityRuleOperations/index.ts"
  "./api/virtualApplianceSkus": "./src/api/virtualApplianceSkus/index.ts"
  "./api/networkSecurityPerimeterLoggingConfigurations": "./src/api/networkSecurityPerimeterLoggingConfigurations/index.ts"
  "./api/networkSecurityPerimeterLinkReferences": "./src/api/networkSecurityPerimeterLinkReferences/index.ts"
  "./api/networkSecurityPerimeterLinks": "./src/api/networkSecurityPerimeterLinks/index.ts"
  "./api/networkSecurityPerimeterAssociations": "./src/api/networkSecurityPerimeterAssociations/index.ts"
  "./api/networkSecurityPerimeterAccessRules": "./src/api/networkSecurityPerimeterAccessRules/index.ts"
  "./api/networkSecurityPerimeterProfiles": "./src/api/networkSecurityPerimeterProfiles/index.ts"
  "./api/adminRules": "./src/api/adminRules/index.ts"
  "./api/subscriptionNetworkManagerConnections": "./src/api/subscriptionNetworkManagerConnections/index.ts"
  "./api/loadBalancerProbes": "./src/api/loadBalancerProbes/index.ts"
  "./api/loadBalancerOutboundRules": "./src/api/loadBalancerOutboundRules/index.ts"
  "./api/loadBalancerLoadBalancingRules": "./src/api/loadBalancerLoadBalancingRules/index.ts"
  "./api/loadBalancerFrontendIPConfigurations": "./src/api/loadBalancerFrontendIPConfigurations/index.ts"
  "./api/loadBalancerBackendAddressPools": "./src/api/loadBalancerBackendAddressPools/index.ts"
  "./api/loadBalancerNetworkInterfaces": "./src/api/loadBalancerNetworkInterfaces/index.ts"
  "./api/networkManagerDeploymentStatusOperations": "./src/api/networkManagerDeploymentStatusOperations/index.ts"
  "./api/networkManagerCommits": "./src/api/networkManagerCommits/index.ts"
  "./api/firewallPolicyDeployments": "./src/api/firewallPolicyDeployments/index.ts"
  "./api/firewallPolicyIdpsSignaturesFilterValues": "./src/api/firewallPolicyIdpsSignaturesFilterValues/index.ts"
  "./api/firewallPolicyIdpsSignatures": "./src/api/firewallPolicyIdpsSignatures/index.ts"
  "./api/expressRouteLinks": "./src/api/expressRouteLinks/index.ts"
  "./api/expressRouteCrossConnectionPeerings": "./src/api/expressRouteCrossConnectionPeerings/index.ts"
  "./api/dscpConfigurationOperations": "./src/api/dscpConfigurationOperations/index.ts"
  "./api/customIPPrefixes": "./src/api/customIPPrefixes/index.ts"
  "./api/vipSwap": "./src/api/vipSwap/index.ts"
  "./api/networkInterfaceLoadBalancers": "./src/api/networkInterfaceLoadBalancers/index.ts"
  "./api/expressRouteProviderPortsLocation": "./src/api/expressRouteProviderPortsLocation/index.ts"
  "./api/webCategories": "./src/api/webCategories/index.ts"
  "./api/applicationGatewayWafDynamicManifests": "./src/api/applicationGatewayWafDynamicManifests/index.ts"
  "./api/applicationGatewayWafDynamicManifestsDefault": "./src/api/applicationGatewayWafDynamicManifestsDefault/index.ts"
  "./api/applicationGatewayPrivateLinkResources": "./src/api/applicationGatewayPrivateLinkResources/index.ts"
  "./api/addressPrefixSets": "./src/api/addressPrefixSets/index.ts"
  "./api/firstPartyServiceTags": "./src/api/firstPartyServiceTags/index.ts"
  "./api/subgroups": "./src/api/subgroups/index.ts"
  "./api/interconnectGroups": "./src/api/interconnectGroups/index.ts"
  "./api/serviceGateways": "./src/api/serviceGateways/index.ts"
  "./api/virtualNetworkApplianceCapabilities": "./src/api/virtualNetworkApplianceCapabilities/index.ts"
  "./api/virtualNetworkAppliances": "./src/api/virtualNetworkAppliances/index.ts"
  "./api/webApplicationFirewallPolicies": "./src/api/webApplicationFirewallPolicies/index.ts"
  "./api/connectionPolicies": "./src/api/connectionPolicies/index.ts"
  "./api/hubRouteTables": "./src/api/hubRouteTables/index.ts"
  "./api/expressRouteGateways": "./src/api/expressRouteGateways/index.ts"
  "./api/vpnSiteLinkConnections": "./src/api/vpnSiteLinkConnections/index.ts"
  "./api/vpnGateways": "./src/api/vpnGateways/index.ts"
  "./api/routeMaps": "./src/api/routeMaps/index.ts"
  "./api/virtualHubs": "./src/api/virtualHubs/index.ts"
  "./api/vpnServerConfigurations": "./src/api/vpnServerConfigurations/index.ts"
  "./api/vpnSiteLinks": "./src/api/vpnSiteLinks/index.ts"
  "./api/vpnSites": "./src/api/vpnSites/index.ts"
  "./api/virtualWans": "./src/api/virtualWans/index.ts"
  "./api/virtualRouterPeerings": "./src/api/virtualRouterPeerings/index.ts"
  "./api/virtualRouters": "./src/api/virtualRouters/index.ts"
  "./api/virtualNetworkTaps": "./src/api/virtualNetworkTaps/index.ts"
  "./api/virtualNetworkGatewayNatRules": "./src/api/virtualNetworkGatewayNatRules/index.ts"
  "./api/localNetworkGateways": "./src/api/localNetworkGateways/index.ts"
  "./api/virtualNetworkGatewayConnections": "./src/api/virtualNetworkGatewayConnections/index.ts"
  "./api/virtualNetworkGateways": "./src/api/virtualNetworkGateways/index.ts"
  "./api/virtualNetworkPeerings": "./src/api/virtualNetworkPeerings/index.ts"
  "./api/subnets": "./src/api/subnets/index.ts"
  "./api/virtualNetworks": "./src/api/virtualNetworks/index.ts"
  "./api/serviceEndpointPolicyDefinitions": "./src/api/serviceEndpointPolicyDefinitions/index.ts"
  "./api/serviceEndpointPolicies": "./src/api/serviceEndpointPolicies/index.ts"
  "./api/securityPartnerProviders": "./src/api/securityPartnerProviders/index.ts"
  "./api/routes": "./src/api/routes/index.ts"
  "./api/routeTables": "./src/api/routeTables/index.ts"
  "./api/routeFilters": "./src/api/routeFilters/index.ts"
  "./api/publicIPPrefixes": "./src/api/publicIPPrefixes/index.ts"
  "./api/privateLinkServices": "./src/api/privateLinkServices/index.ts"
  "./api/privateEndpoints": "./src/api/privateEndpoints/index.ts"
  "./api/flowLogs": "./src/api/flowLogs/index.ts"
  "./api/networkWatchers": "./src/api/networkWatchers/index.ts"
  "./api/virtualApplianceSites": "./src/api/virtualApplianceSites/index.ts"
  "./api/networkVirtualAppliances": "./src/api/networkVirtualAppliances/index.ts"
  "./api/networkVirtualApplianceConnections": "./src/api/networkVirtualApplianceConnections/index.ts"
  "./api/reachabilityAnalysisRuns": "./src/api/reachabilityAnalysisRuns/index.ts"
  "./api/verifierWorkspaces": "./src/api/verifierWorkspaces/index.ts"
  "./api/reachabilityAnalysisIntents": "./src/api/reachabilityAnalysisIntents/index.ts"
  "./api/networkSecurityPerimeters": "./src/api/networkSecurityPerimeters/index.ts"
  "./api/defaultSecurityRules": "./src/api/defaultSecurityRules/index.ts"
  "./api/securityRules": "./src/api/securityRules/index.ts"
  "./api/networkSecurityGroups": "./src/api/networkSecurityGroups/index.ts"
  "./api/networkProfiles": "./src/api/networkProfiles/index.ts"
  "./api/securityUserRules": "./src/api/securityUserRules/index.ts"
  "./api/securityUserRuleCollections": "./src/api/securityUserRuleCollections/index.ts"
  "./api/securityUserConfigurations": "./src/api/securityUserConfigurations/index.ts"
  "./api/adminRuleCollections": "./src/api/adminRuleCollections/index.ts"
  "./api/securityAdminConfigurations": "./src/api/securityAdminConfigurations/index.ts"
  "./api/commits": "./src/api/commits/index.ts"
  "./api/scopeConnections": "./src/api/scopeConnections/index.ts"
  "./api/routingRules": "./src/api/routingRules/index.ts"
  "./api/routingRuleCollections": "./src/api/routingRuleCollections/index.ts"
  "./api/networkManagerRoutingConfigurations": "./src/api/networkManagerRoutingConfigurations/index.ts"
  "./api/staticMembers": "./src/api/staticMembers/index.ts"
  "./api/networkGroups": "./src/api/networkGroups/index.ts"
  "./api/connectivityConfigurations": "./src/api/connectivityConfigurations/index.ts"
  "./api/managementGroupNetworkManagerConnections": "./src/api/managementGroupNetworkManagerConnections/index.ts"
  "./api/networkInterfaceTapConfigurations": "./src/api/networkInterfaceTapConfigurations/index.ts"
  "./api/networkInterfaceIPConfigurations": "./src/api/networkInterfaceIPConfigurations/index.ts"
  "./api/natGateways": "./src/api/natGateways/index.ts"
  "./api/inboundNatRules": "./src/api/inboundNatRules/index.ts"
  "./api/loadBalancers": "./src/api/loadBalancers/index.ts"
  "./api/ipGroups": "./src/api/ipGroups/index.ts"
  "./api/ipAllocations": "./src/api/ipAllocations/index.ts"
  "./api/staticCidrs": "./src/api/staticCidrs/index.ts"
  "./api/networkManagers": "./src/api/networkManagers/index.ts"
  "./api/ipamPools": "./src/api/ipamPools/index.ts"
  "./api/firewallPolicyRuleCollectionGroupDrafts": "./src/api/firewallPolicyRuleCollectionGroupDrafts/index.ts"
  "./api/firewallPolicyDrafts": "./src/api/firewallPolicyDrafts/index.ts"
  "./api/firewallPolicyIdpsSignaturesOverrides": "./src/api/firewallPolicyIdpsSignaturesOverrides/index.ts"
  "./api/firewallPolicyKubeSelectorGroups": "./src/api/firewallPolicyKubeSelectorGroups/index.ts"
  "./api/firewallPolicyRuleCollectionGroups": "./src/api/firewallPolicyRuleCollectionGroups/index.ts"
  "./api/firewallPolicies": "./src/api/firewallPolicies/index.ts"
  "./api/expressRouteLagAuthorizations": "./src/api/expressRouteLagAuthorizations/index.ts"
  "./api/expressRouteLags": "./src/api/expressRouteLags/index.ts"
  "./api/expressRoutePortAuthorizations": "./src/api/expressRoutePortAuthorizations/index.ts"
  "./api/expressRoutePorts": "./src/api/expressRoutePorts/index.ts"
  "./api/expressRoutePortsLocations": "./src/api/expressRoutePortsLocations/index.ts"
  "./api/expressRouteCrossConnections": "./src/api/expressRouteCrossConnections/index.ts"
  "./api/peerExpressRouteCircuitConnections": "./src/api/peerExpressRouteCircuitConnections/index.ts"
  "./api/expressRouteCircuitConnections": "./src/api/expressRouteCircuitConnections/index.ts"
  "./api/expressRouteCircuitPeerings": "./src/api/expressRouteCircuitPeerings/index.ts"
  "./api/expressRouteCircuits": "./src/api/expressRouteCircuits/index.ts"
  "./api/expressRouteCircuitAuthorizations": "./src/api/expressRouteCircuitAuthorizations/index.ts"
  "./api/ddosProtectionPlans": "./src/api/ddosProtectionPlans/index.ts"
  "./api/ddosCustomPolicies": "./src/api/ddosCustomPolicies/index.ts"
  "./api/publicIPAddresses": "./src/api/publicIPAddresses/index.ts"
  "./api/networkInterfaces": "./src/api/networkInterfaces/index.ts"
  "./api/bastionHosts": "./src/api/bastionHosts/index.ts"
  "./api/azureFirewalls": "./src/api/azureFirewalls/index.ts"
  "./api/authenticationPolicies": "./src/api/authenticationPolicies/index.ts"
  "./api/applicationSecurityGroups": "./src/api/applicationSecurityGroups/index.ts"
  "./api/applicationGatewayPrivateEndpointConnections": "./src/api/applicationGatewayPrivateEndpointConnections/index.ts"
  "./api/applicationGateways": "./src/api/applicationGateways/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"
  "./models/common": "./src/models/common/index.ts"
  "./models/network": "./src/models/network/index.ts"
  "./models/network/connectionAnalyzerEndpointTypes": "./src/models/network/connectionAnalyzerEndpointTypes/index.ts"

targets:
  - name: browser
    tsconfig: "./config/tsconfig.src.browser.json"

  - name: esm
    condition: import
    tsconfig: "./config/tsconfig.src.esm.json"

  - name: commonjs
    condition: require
    tsconfig: "./config/tsconfig.src.cjs.json"
    moduleType: commonjs
