extends: ../../../warp.base.config.yml
exports:
  "./api": "./src/api/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./api/snapshots": "./src/api/snapshots/index.ts"
  "./api/replicas": "./src/api/replicas/index.ts"
  "./api/keyValues": "./src/api/keyValues/index.ts"
  "./api/privateLinkResources": "./src/api/privateLinkResources/index.ts"
  "./api/privateEndpointConnections": "./src/api/privateEndpointConnections/index.ts"
  "./api/configurationStores": "./src/api/configurationStores/index.ts"
  "./models": "./src/models/index.ts"
<<<<<<< HEAD

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"
  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
    moduleType: commonjs
=======
>>>>>>> origin/main
