extends: ../../../warp.base.config.yml
exports:
  "./api": "./src/api/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./api/snapshots": "./src/api/snapshots/index.ts"
  "./api/replicas": "./src/api/replicas/index.ts"
  "./api/keyValues": "./src/api/keyValues/index.ts"
  "./api/privateLinkResources": "./src/api/privateLinkResources/index.ts"
  "./api/privateEndpointConnections": "./src/api/privateEndpointConnections/index.ts"
  "./api/configurationStores": "./src/api/configurationStores/index.ts"
  "./models": "./src/models/index.ts"
