// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import type {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { AzureSiteRecoveryManagementServiceAPI } from "./azureSiteRecoveryManagementServiceAPI.js";
export { restorePoller, type RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  type Operation,
  type OperationDisplay,
  KnownOrigin,
  type Origin,
  KnownActionType,
  type ActionType,
  type ErrorResponse,
  type ErrorDetail,
  type ErrorAdditionalInfo,
  type EmailConfigurationModel,
  type EmailConfigurationModelProperties,
  KnownProvisioningState,
  type ProvisioningState,
  type ProxyResource,
  type Resource,
  type SystemData,
  KnownCreatedByType,
  type CreatedByType,
  type VaultModel,
  type VaultModelProperties,
  KnownReplicationVaultType,
  type ReplicationVaultType,
  type ManagedServiceIdentity,
  KnownManagedServiceIdentityType,
  type ManagedServiceIdentityType,
  type UserAssignedIdentity,
  type TrackedResource,
  type VaultModelUpdate,
  type VaultIdentityModel,
  KnownVaultIdentityType,
  type VaultIdentityType,
  type EventModel,
  type EventModelProperties,
  type HealthErrorModel,
  type InnerHealthErrorModel,
  type EventModelCustomProperties,
  type EventModelCustomPropertiesUnion,
  type HyperVToAzStackHCIEventModelCustomProperties,
  type VMwareToAzStackHCIEventModelCustomProperties,
  type FabricModel,
  type FabricModelProperties,
  KnownHealthStatus,
  type HealthStatus,
  type FabricModelCustomProperties,
  type FabricModelCustomPropertiesUnion,
  type AzStackHCIFabricModelCustomProperties,
  type AzStackHCIClusterProperties,
  type StorageContainerProperties,
  type HyperVMigrateFabricModelCustomProperties,
  type VMwareMigrateFabricModelCustomProperties,
  type FabricModelUpdate,
  type FabricAgentModel,
  type FabricAgentModelProperties,
  type IdentityModel,
  type FabricAgentModelCustomProperties,
  type FabricAgentModelCustomPropertiesUnion,
  type VMwareFabricAgentModelCustomProperties,
  type JobModel,
  type JobModelProperties,
  KnownJobState,
  type JobState,
  KnownJobObjectType,
  type JobObjectType,
  type TaskModel,
  KnownTaskState,
  type TaskState,
  type TaskModelCustomProperties,
  type ErrorModel,
  type JobModelCustomProperties,
  type JobModelCustomPropertiesUnion,
  type AffectedObjectDetails,
  type FailoverJobModelCustomProperties,
  type FailoverProtectedItemProperties,
  type TestFailoverCleanupJobModelCustomProperties,
  type TestFailoverJobModelCustomProperties,
  type PolicyModel,
  type PolicyModelProperties,
  type PolicyModelCustomProperties,
  type PolicyModelCustomPropertiesUnion,
  type HyperVToAzStackHCIPolicyModelCustomProperties,
  type VMwareToAzStackHCIPolicyModelCustomProperties,
  type PrivateEndpointConnection,
  type PrivateEndpointConnectionResponseProperties,
  type PrivateEndpoint,
  type PrivateLinkServiceConnectionState,
  KnownPrivateEndpointConnectionStatus,
  type PrivateEndpointConnectionStatus,
  type PrivateEndpointConnectionProxy,
  type PrivateEndpointConnectionProxyProperties,
  type RemotePrivateEndpoint,
  type PrivateLinkServiceConnection,
  type PrivateLinkServiceProxy,
  type RemotePrivateEndpointConnection,
  type GroupConnectivityInformation,
  type ConnectionDetails,
  type PrivateLinkResource,
  type PrivateLinkResourceProperties,
  type ProtectedItemModel,
  type ProtectedItemModelProperties,
  KnownProtectionState,
  type ProtectionState,
  KnownTestFailoverState,
  type TestFailoverState,
  KnownResynchronizationState,
  type ResynchronizationState,
  type ProtectedItemJobProperties,
  type ProtectedItemModelCustomProperties,
  type ProtectedItemModelCustomPropertiesUnion,
  type HyperVToAzStackHCIProtectedItemModelCustomProperties,
  KnownProtectedItemActiveLocation,
  type ProtectedItemActiveLocation,
  type HyperVToAzStackHCIDiskInput,
  type DiskControllerInputs,
  type HyperVToAzStackHCINicInput,
  KnownVMNicSelection,
  type VMNicSelection,
  type ProtectedItemDynamicMemoryConfig,
  type HyperVToAzStackHCIProtectedDiskProperties,
  type HyperVToAzStackHCIProtectedNicProperties,
  type VMwareToAzStackHCIProtectedItemModelCustomProperties,
  type VMwareToAzStackHCIDiskInput,
  type VMwareToAzStackHCINicInput,
  type VMwareToAzStackHCIProtectedDiskProperties,
  type VMwareToAzStackHCIProtectedNicProperties,
  KnownVMwareToAzureMigrateResyncState,
  type VMwareToAzureMigrateResyncState,
  type ProtectedItemModelUpdate,
  type ProtectedItemModelPropertiesUpdate,
  type ProtectedItemModelCustomPropertiesUpdate,
  type ProtectedItemModelCustomPropertiesUpdateUnion,
  type HyperVToAzStackHCIProtectedItemModelCustomPropertiesUpdate,
  type VMwareToAzStackHCIProtectedItemModelCustomPropertiesUpdate,
  type PlannedFailoverModel,
  type PlannedFailoverModelProperties,
  type PlannedFailoverModelCustomProperties,
  type PlannedFailoverModelCustomPropertiesUnion,
  type HyperVToAzStackHCIPlannedFailoverModelCustomProperties,
  type VMwareToAzStackHCIPlannedFailoverModelCustomProperties,
  type RecoveryPointModel,
  type RecoveryPointModelProperties,
  KnownRecoveryPointType,
  type RecoveryPointType,
  type RecoveryPointModelCustomProperties,
  type RecoveryPointModelCustomPropertiesUnion,
  type HyperVToAzStackHCIRecoveryPointModelCustomProperties,
  type VMwareToAzStackHCIRecoveryPointModelCustomProperties,
  type ReplicationExtensionModel,
  type ReplicationExtensionModelProperties,
  type ReplicationExtensionModelCustomProperties,
  type ReplicationExtensionModelCustomPropertiesUnion,
  type HyperVToAzStackHCIReplicationExtensionModelCustomProperties,
  type VMwareToAzStackHCIReplicationExtensionModelCustomProperties,
  type CheckNameAvailabilityModel,
  type CheckNameAvailabilityResponseModel,
  type DeploymentPreflightModel,
  type DeploymentPreflightResource,
  type OperationStatus,
  KnownVersions,
} from "./models/index.js";
export type { AzureSiteRecoveryManagementServiceAPIOptionalParams } from "./api/index.js";
export type { CheckNameAvailabilityPostOptionalParams } from "./api/checkNameAvailability/index.js";
export type { DeploymentPreflightPostOptionalParams } from "./api/deploymentPreflight/index.js";
export type {
  EmailConfigurationListOptionalParams,
  EmailConfigurationCreateOptionalParams,
  EmailConfigurationGetOptionalParams,
} from "./api/emailConfiguration/index.js";
export type { EventListOptionalParams, EventGetOptionalParams } from "./api/event/index.js";
export type {
  FabricListBySubscriptionOptionalParams,
  FabricListOptionalParams,
  FabricDeleteOptionalParams,
  FabricUpdateOptionalParams,
  FabricCreateOptionalParams,
  FabricGetOptionalParams,
} from "./api/fabric/index.js";
export type {
  FabricAgentListOptionalParams,
  FabricAgentDeleteOptionalParams,
  FabricAgentCreateOptionalParams,
  FabricAgentGetOptionalParams,
} from "./api/fabricAgent/index.js";
export type { JobListOptionalParams, JobGetOptionalParams } from "./api/job/index.js";
export type { LocationBasedOperationResultsGetOptionalParams } from "./api/locationBasedOperationResults/index.js";
export type { OperationResultsGetOptionalParams } from "./api/operationResults/index.js";
export type { OperationsListOptionalParams } from "./api/operations/index.js";
export type {
  PolicyListOptionalParams,
  PolicyDeleteOptionalParams,
  PolicyCreateOptionalParams,
  PolicyGetOptionalParams,
} from "./api/policy/index.js";
export type {
  PrivateEndpointConnectionProxiesValidateOptionalParams,
  PrivateEndpointConnectionProxiesListOptionalParams,
  PrivateEndpointConnectionProxiesDeleteOptionalParams,
  PrivateEndpointConnectionProxiesCreateOptionalParams,
  PrivateEndpointConnectionProxiesGetOptionalParams,
} from "./api/privateEndpointConnectionProxies/index.js";
export type {
  PrivateEndpointConnectionsListOptionalParams,
  PrivateEndpointConnectionsDeleteOptionalParams,
  PrivateEndpointConnectionsUpdateOptionalParams,
  PrivateEndpointConnectionsGetOptionalParams,
} from "./api/privateEndpointConnections/index.js";
export type {
  PrivateLinkResourcesListOptionalParams,
  PrivateLinkResourcesGetOptionalParams,
} from "./api/privateLinkResources/index.js";
export type {
  ProtectedItemPlannedFailoverOptionalParams,
  ProtectedItemListOptionalParams,
  ProtectedItemDeleteOptionalParams,
  ProtectedItemUpdateOptionalParams,
  ProtectedItemCreateOptionalParams,
  ProtectedItemGetOptionalParams,
} from "./api/protectedItem/index.js";
export type {
  RecoveryPointListOptionalParams,
  RecoveryPointGetOptionalParams,
} from "./api/recoveryPoint/index.js";
export type {
  ReplicationExtensionListOptionalParams,
  ReplicationExtensionDeleteOptionalParams,
  ReplicationExtensionCreateOptionalParams,
  ReplicationExtensionGetOptionalParams,
} from "./api/replicationExtension/index.js";
export type {
  VaultListBySubscriptionOptionalParams,
  VaultListOptionalParams,
  VaultDeleteOptionalParams,
  VaultUpdateOptionalParams,
  VaultCreateOptionalParams,
  VaultGetOptionalParams,
} from "./api/vault/index.js";
export type {
  CheckNameAvailabilityOperations,
  DeploymentPreflightOperations,
  EmailConfigurationOperations,
  EventOperations,
  FabricOperations,
  FabricAgentOperations,
  JobOperations,
  LocationBasedOperationResultsOperations,
  OperationResultsOperations,
  OperationsOperations,
  PolicyOperations,
  PrivateEndpointConnectionProxiesOperations,
  PrivateEndpointConnectionsOperations,
  PrivateLinkResourcesOperations,
  ProtectedItemOperations,
  RecoveryPointOperations,
  ReplicationExtensionOperations,
  VaultOperations,
} from "./classic/index.js";
export type { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
