extends: ../../../warp.base.config.yml
exports:
  "./api": "./src/api/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./api/trafficControllerInterface": "./src/api/trafficControllerInterface/index.ts"
  "./api/securityPoliciesInterface": "./src/api/securityPoliciesInterface/index.ts"
  "./api/frontendsInterface": "./src/api/frontendsInterface/index.ts"
  "./api/associationsInterface": "./src/api/associationsInterface/index.ts"
  "./models": "./src/models/index.ts"
