# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/rateCard": "src/api/rateCard/index.ts"
  "./api/usageAggregates": "src/api/usageAggregates/index.ts"
  "./models": "./src/models/index.ts"
