# warp.config.yml — build configuration

exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/deletedAutomationAccounts": "./src/api/deletedAutomationAccounts/index.ts"
  "./api/watcher": "./src/api/watcher/index.ts"
  "./api/variable": "./src/api/variable/index.ts"
  "./api/sourceControlSyncJobStreams": "./src/api/sourceControlSyncJobStreams/index.ts"
  "./api/sourceControlSyncJob": "./src/api/sourceControlSyncJob/index.ts"
  "./api/sourceControl": "./src/api/sourceControl/index.ts"
  "./api/schedule": "./src/api/schedule/index.ts"
  "./api/testJob": "./src/api/testJob/index.ts"
  "./api/testJobStreams": "./src/api/testJobStreams/index.ts"
  "./api/runbookDraft": "./src/api/runbookDraft/index.ts"
  "./api/runbook": "./src/api/runbook/index.ts"
  "./api/package": "./src/api/package/index.ts"
  "./api/fields": "./src/api/fields/index.ts"
  "./api/activity": "./src/api/activity/index.ts"
  "./api/module": "./src/api/module/index.ts"
  "./api/jobSchedule": "./src/api/jobSchedule/index.ts"
  "./api/jobStream": "./src/api/jobStream/index.ts"
  "./api/hybridRunbookWorkerGroup": "./src/api/hybridRunbookWorkerGroup/index.ts"
  "./api/dscNodeConfiguration": "./src/api/dscNodeConfiguration/index.ts"
  "./api/dscConfiguration": "./src/api/dscConfiguration/index.ts"
  "./api/credential": "./src/api/credential/index.ts"
  "./api/connectionType": "./src/api/connectionType/index.ts"
  "./api/connection": "./src/api/connection/index.ts"
  "./api/certificate": "./src/api/certificate/index.ts"
  "./api/nodeReports": "./src/api/nodeReports/index.ts"
  "./api/dscNode": "./src/api/dscNode/index.ts"
  "./api/webhook": "./src/api/webhook/index.ts"
  "./api/softwareUpdateConfigurationRuns": "./src/api/softwareUpdateConfigurationRuns/index.ts"
  "./api/softwareUpdateConfigurationMachineRuns": "./src/api/softwareUpdateConfigurationMachineRuns/index.ts"
  "./api/objectDataTypes": "./src/api/objectDataTypes/index.ts"
  "./api/linkedWorkspace": "./src/api/linkedWorkspace/index.ts"
  "./api/job": "./src/api/job/index.ts"
  "./api/keys": "./src/api/keys/index.ts"
  "./api/usages": "./src/api/usages/index.ts"
  "./api/statistics": "./src/api/statistics/index.ts"
  "./api/agentRegistrationInformation": "./src/api/agentRegistrationInformation/index.ts"
  "./api/privateLinkResources": "./src/api/privateLinkResources/index.ts"
  "./api/nodeCountInformation": "./src/api/nodeCountInformation/index.ts"
  "./api/automationAccount": "./src/api/automationAccount/index.ts"
  "./api/privateEndpointConnections": "./src/api/privateEndpointConnections/index.ts"
  "./api/runtimeEnvironments": "./src/api/runtimeEnvironments/index.ts"
  "./api/python3Package": "./src/api/python3Package/index.ts"
  "./api/python2Package": "./src/api/python2Package/index.ts"
  "./api/hybridRunbookWorkers": "./src/api/hybridRunbookWorkers/index.ts"
  "./api/softwareUpdateConfigurations": "./src/api/softwareUpdateConfigurations/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "./config/tsconfig.src.browser.json"

  - name: esm
    condition: import
    tsconfig: "./config/tsconfig.src.esm.json"

  - name: commonjs
    condition: require
    tsconfig: "./config/tsconfig.src.cjs.json"
    moduleType: commonjs
