# warp.config.yml — build configuration

exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/deletedAutomationAccounts": "./src/api/deletedAutomationAccounts/index.ts"
  "./api/watcherOperations": "./src/api/watcherOperations/index.ts"
  "./api/variableOperations": "./src/api/variableOperations/index.ts"
  "./api/sourceControlSyncJobStreams": "./src/api/sourceControlSyncJobStreams/index.ts"
  "./api/sourceControlSyncJobOperations": "./src/api/sourceControlSyncJobOperations/index.ts"
  "./api/sourceControlOperations": "./src/api/sourceControlOperations/index.ts"
  "./api/scheduleOperations": "./src/api/scheduleOperations/index.ts"
  "./api/testJobOperations": "./src/api/testJobOperations/index.ts"
  "./api/testJobStreams": "./src/api/testJobStreams/index.ts"
  "./api/runbook": "./src/api/runbook/index.ts"
  "./api/runbookDraftOperations": "./src/api/runbookDraftOperations/index.ts"
  "./api/runbookOperations": "./src/api/runbookOperations/index.ts"
  "./api/package": "./src/api/package/index.ts"
  "./api/fields": "./src/api/fields/index.ts"
  "./api/activityOperations": "./src/api/activityOperations/index.ts"
  "./api/moduleOperations": "./src/api/moduleOperations/index.ts"
  "./api/jobScheduleOperations": "./src/api/jobScheduleOperations/index.ts"
  "./api/jobStreamOperations": "./src/api/jobStreamOperations/index.ts"
  "./api/hybridRunbookWorkerGroupOperations": "./src/api/hybridRunbookWorkerGroupOperations/index.ts"
  "./api/dscNodeConfiguration": "./src/api/dscNodeConfiguration/index.ts"
  "./api/dscNodeConfigurationOperations": "./src/api/dscNodeConfigurationOperations/index.ts"
  "./api/dscConfigurationOperations": "./src/api/dscConfigurationOperations/index.ts"
  "./api/credentialOperations": "./src/api/credentialOperations/index.ts"
  "./api/connectionTypeOperations": "./src/api/connectionTypeOperations/index.ts"
  "./api/connectionOperations": "./src/api/connectionOperations/index.ts"
  "./api/certificateOperations": "./src/api/certificateOperations/index.ts"
  "./api/nodeReports": "./src/api/nodeReports/index.ts"
  "./api/dscNodeOperations": "./src/api/dscNodeOperations/index.ts"
  "./api/webhookOperations": "./src/api/webhookOperations/index.ts"
  "./api/softwareUpdateConfigurationRuns": "./src/api/softwareUpdateConfigurationRuns/index.ts"
  "./api/softwareUpdateConfigurationMachineRuns": "./src/api/softwareUpdateConfigurationMachineRuns/index.ts"
  "./api/objectDataTypes": "./src/api/objectDataTypes/index.ts"
  "./api/linkedWorkspaceOperations": "./src/api/linkedWorkspaceOperations/index.ts"
  "./api/jobOperations": "./src/api/jobOperations/index.ts"
  "./api/keys": "./src/api/keys/index.ts"
  "./api/usages": "./src/api/usages/index.ts"
  "./api/statisticsOperations": "./src/api/statisticsOperations/index.ts"
  "./api/agentRegistrationInformation": "./src/api/agentRegistrationInformation/index.ts"
  "./api/privateLinkResources": "./src/api/privateLinkResources/index.ts"
  "./api/nodeCountInformation": "./src/api/nodeCountInformation/index.ts"
  "./api/automationAccountOperations": "./src/api/automationAccountOperations/index.ts"
  "./api/privateEndpointConnections": "./src/api/privateEndpointConnections/index.ts"
  "./api/runtimeEnvironments": "./src/api/runtimeEnvironments/index.ts"
  "./api/python3Package": "./src/api/python3Package/index.ts"
  "./api/python2Package": "./src/api/python2Package/index.ts"
  "./api/hybridRunbookWorkers": "./src/api/hybridRunbookWorkers/index.ts"
  "./api/softwareUpdateConfigurations": "./src/api/softwareUpdateConfigurations/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "./config/tsconfig.src.browser.json"

  - name: esm
    condition: import
    tsconfig: "./config/tsconfig.src.esm.json"

  - name: commonjs
    condition: require
    tsconfig: "./config/tsconfig.src.cjs.json"
    moduleType: commonjs
