exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/usageMetrics": "./src/api/usageMetrics/index.ts"
  "./api/summaries": "./src/api/summaries/index.ts"
  "./api/sbomComponents": "./src/api/sbomComponents/index.ts"
  "./api/passwordHashes": "./src/api/passwordHashes/index.ts"
  "./api/cves": "./src/api/cves/index.ts"
  "./api/cryptoKeys": "./src/api/cryptoKeys/index.ts"
  "./api/cryptoCertificates": "./src/api/cryptoCertificates/index.ts"
  "./api/binaryHardening": "./src/api/binaryHardening/index.ts"
  "./api/workspaces": "./src/api/workspaces/index.ts"
  "./api/firmwares": "./src/api/firmwares/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"
  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
    moduleType: commonjs
