// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export {
  listByLocation,
  scaleOut,
  start,
  listSkus,
  setOrchestrationServiceState,
  restart,
  reimageAll,
  reimage,
  redeploy,
  reapply,
  powerOff,
  performMaintenance,
  getOSUpgradeHistory,
  updateInstances,
  getInstanceView,
  forceRecoveryServiceFabricPlatformUpdateDomainWalk,
  deleteInstances,
  deallocate,
  convertToSinglePlacementGroup,
  approveRollingUpgrade,
  listAll,
  list,
  $delete,
  update,
  createOrUpdate,
  get,
} from "./operations.js";
export type {
  VirtualMachineScaleSetsListByLocationOptionalParams,
  VirtualMachineScaleSetsScaleOutOptionalParams,
  VirtualMachineScaleSetsStartOptionalParams,
  VirtualMachineScaleSetsListSkusOptionalParams,
  VirtualMachineScaleSetsSetOrchestrationServiceStateOptionalParams,
  VirtualMachineScaleSetsRestartOptionalParams,
  VirtualMachineScaleSetsReimageAllOptionalParams,
  VirtualMachineScaleSetsReimageOptionalParams,
  VirtualMachineScaleSetsRedeployOptionalParams,
  VirtualMachineScaleSetsReapplyOptionalParams,
  VirtualMachineScaleSetsPowerOffOptionalParams,
  VirtualMachineScaleSetsPerformMaintenanceOptionalParams,
  VirtualMachineScaleSetsGetOSUpgradeHistoryOptionalParams,
  VirtualMachineScaleSetsUpdateInstancesOptionalParams,
  VirtualMachineScaleSetsGetInstanceViewOptionalParams,
  VirtualMachineScaleSetsForceRecoveryServiceFabricPlatformUpdateDomainWalkOptionalParams,
  VirtualMachineScaleSetsDeleteInstancesOptionalParams,
  VirtualMachineScaleSetsDeallocateOptionalParams,
  VirtualMachineScaleSetsConvertToSinglePlacementGroupOptionalParams,
  VirtualMachineScaleSetsApproveRollingUpgradeOptionalParams,
  VirtualMachineScaleSetsListAllOptionalParams,
  VirtualMachineScaleSetsListOptionalParams,
  VirtualMachineScaleSetsDeleteOptionalParams,
  VirtualMachineScaleSetsUpdateOptionalParams,
  VirtualMachineScaleSetsCreateOrUpdateOptionalParams,
  VirtualMachineScaleSetsGetOptionalParams,
} from "./options.js";
