# warp.config.yml — build configuration

exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/memberCapOverrides": "./src/api/memberCapOverrides/index.ts"
  "./api/sharedLimitCaps": "./src/api/sharedLimitCaps/index.ts"
  "./api/vmFamilies": "./src/api/vmFamilies/index.ts"
  "./api/features": "./src/api/features/index.ts"
  "./api/sharedLimits": "./src/api/sharedLimits/index.ts"
  "./api/guestSubscriptions": "./src/api/guestSubscriptions/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "./config/tsconfig.src.browser.json"

  - name: esm
    condition: import
    tsconfig: "./config/tsconfig.src.esm.json"

  - name: commonjs
    condition: require
    tsconfig: "./config/tsconfig.src.cjs.json"
    moduleType: commonjs
