// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { ImpactClient } from "./impactClient.js";
export { restorePoller, type RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  type Connector,
  type ConnectorProperties,
  KnownProvisioningState,
  type ProvisioningState,
  KnownPlatform,
  type Platform,
  type ProxyResource,
  type Resource,
  type SystemData,
  KnownCreatedByType,
  type CreatedByType,
  type ErrorResponse,
  type ErrorDetail,
  type ErrorAdditionalInfo,
  type ConnectorUpdate,
  type ConnectorUpdateProperties,
  type Insight,
  type InsightProperties,
  type Content,
  type ImpactDetails,
  type ImpactCategory,
  type ImpactCategoryProperties,
  type RequiredImpactProperties,
  type WorkloadImpact,
  type WorkloadImpactProperties,
  type Performance,
  type ExpectedValueRange,
  KnownMetricUnit,
  type MetricUnit,
  type Connectivity,
  KnownProtocol,
  type Protocol,
  type SourceOrTarget,
  type ErrorDetailProperties,
  type Workload,
  KnownToolset,
  type Toolset,
  KnownConfidenceLevel,
  type ConfidenceLevel,
  type ClientIncidentDetails,
  KnownIncidentSource,
  type IncidentSource,
  type Operation,
  type OperationDisplay,
  KnownOrigin,
  type Origin,
  KnownActionType,
  type ActionType,
  KnownVersions,
} from "./models/index.js";
export {
  type ImpactClientOptionalParams,
  type ConnectorsListBySubscriptionOptionalParams,
  type ConnectorsDeleteOptionalParams,
  type ConnectorsUpdateOptionalParams,
  type ConnectorsCreateOrUpdateOptionalParams,
  type ConnectorsGetOptionalParams,
  type InsightsDeleteOptionalParams,
  type InsightsCreateOptionalParams,
  type InsightsListBySubscriptionOptionalParams,
  type InsightsGetOptionalParams,
  type ImpactCategoriesListBySubscriptionOptionalParams,
  type ImpactCategoriesGetOptionalParams,
  type WorkloadImpactsListBySubscriptionOptionalParams,
  type WorkloadImpactsDeleteOptionalParams,
  type WorkloadImpactsGetOptionalParams,
  type WorkloadImpactsCreateOptionalParams,
  type OperationsListOptionalParams,
} from "./api/index.js";
export {
  type ConnectorsOperations,
  type ImpactCategoriesOperations,
  type InsightsOperations,
  type OperationsOperations,
  type WorkloadImpactsOperations,
} from "./classic/index.js";
export { type PageSettings, type ContinuablePage, type PagedAsyncIterableIterator };
