# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/operationStatus": "src/api/operationStatus/index.ts"
  "./api/extensions": "src/api/extensions/index.ts"
  "./models": "./src/models/index.ts"
