# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/privateStoreCollectionOffer": "src/api/privateStoreCollectionOffer/index.ts"
  "./api/privateStoreCollection": "src/api/privateStoreCollection/index.ts"
  "./api/privateStore": "src/api/privateStore/index.ts"
  "./api/operations": "src/api/operations/index.ts"
  "./models": "./src/models/index.ts"
