# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/fluxConfigOperationStatus": "src/api/fluxConfigOperationStatus/index.ts"
  "./api/fluxConfigurations": "src/api/fluxConfigurations/index.ts"
  "./models": "./src/models/index.ts"
