# warp.config.yml — build configuration

exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/privateLinkResources": "src/api/privateLinkResources/index.ts"
  "./api/queryKeys": "src/api/queryKeys/index.ts"
  "./api/adminKeys": "src/api/adminKeys/index.ts"
  "./api/usages": "src/api/usages/index.ts"
  "./api/services": "src/api/services/index.ts"
  "./api/networkSecurityPerimeterConfigurations": "src/api/networkSecurityPerimeterConfigurations/index.ts"
  "./api/sharedPrivateLinkResources": "src/api/sharedPrivateLinkResources/index.ts"
  "./api/privateEndpointConnections": "src/api/privateEndpointConnections/index.ts"
  "./api/operations": "src/api/operations/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
    polyfillSuffix: "-browser"

  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
    polyfillSuffix: "-react-native"

  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"

  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
