extends: ../../../warp.base.config.yml
exports:
<<<<<<< HEAD
  "./package.json": "./package.json"
  ".": "./src/index.ts"

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"
  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
    moduleType: commonjs
=======
  "./api": "./src/api/index.ts"
  "./api/privateLinkResources": "./src/api/privateLinkResources/index.ts"
  "./api/queryKeys": "./src/api/queryKeys/index.ts"
  "./api/adminKeys": "./src/api/adminKeys/index.ts"
  "./api/usages": "./src/api/usages/index.ts"
  "./api/services": "./src/api/services/index.ts"
  "./api/networkSecurityPerimeterConfigurations": "./src/api/networkSecurityPerimeterConfigurations/index.ts"
  "./api/sharedPrivateLinkResources": "./src/api/sharedPrivateLinkResources/index.ts"
  "./api/privateEndpointConnections": "./src/api/privateEndpointConnections/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./api/offerings": "./src/api/offerings/index.ts"
  "./models": "./src/models/index.ts"
>>>>>>> origin/main
