# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/autoUpgradeProfileOperations": "src/api/autoUpgradeProfileOperations/index.ts"
  "./api/autoUpgradeProfiles": "src/api/autoUpgradeProfiles/index.ts"
  "./api/fleetUpdateStrategies": "src/api/fleetUpdateStrategies/index.ts"
  "./api/updateRuns": "src/api/updateRuns/index.ts"
  "./api/gates": "src/api/gates/index.ts"
  "./api/fleetManagedNamespaces": "src/api/fleetManagedNamespaces/index.ts"
  "./api/fleetMembers": "src/api/fleetMembers/index.ts"
  "./api/fleets": "src/api/fleets/index.ts"
  "./api/operations": "src/api/operations/index.ts"
  "./models": "./src/models/index.ts"
