// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import type { AzureSupportedClouds } from "./static-helpers/cloudSettingHelpers.js";
import { AzureClouds } from "./static-helpers/cloudSettingHelpers.js";
import type {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { RedisEnterpriseManagementClient } from "./redisEnterpriseManagementClient.js";
export type { RestorePollerOptions } from "./restorePollerHelpers.js";
export { restorePoller } from "./restorePollerHelpers.js";
export type {
  Operation,
  OperationDisplay,
  Origin,
  ActionType,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  Database,
  DatabaseCreateProperties,
  AccessKeysAuthentication,
  DatabaseProperties,
  Protocol,
  ProvisioningState,
  ResourceState,
  ClusteringPolicy,
  EvictionPolicy,
  Persistence,
  AofFrequency,
  RdbFrequency,
  Module,
  DatabasePropertiesGeoReplication,
  LinkedDatabase,
  LinkState,
  DeferUpgradeSetting,
  ProxyResource,
  Resource,
  SystemData,
  CreatedByType,
  DatabaseUpdate,
  DatabaseUpdateProperties,
  AccessKeys,
  RegenerateKeyParameters,
  AccessKeyType,
  ImportClusterParameters,
  ExportClusterParameters,
  ForceUnlinkParameters,
  ForceLinkParameters,
  ForceLinkParametersGeoReplication,
  FlushParameters,
  PrivateEndpointConnection,
  PrivateEndpointConnectionProperties,
  PrivateEndpoint,
  PrivateLinkServiceConnectionState,
  PrivateEndpointServiceConnectionStatus,
  PrivateEndpointConnectionProvisioningState,
  Cluster,
  ClusterCreateProperties,
  PublicNetworkAccess,
  Kind,
  Sku,
  SkuName,
  ManagedServiceIdentity,
  ManagedServiceIdentityType,
  UserAssignedIdentity,
  ClusterProperties,
  HighAvailability,
  TlsVersion,
  ClusterPropertiesEncryption,
  ClusterPropertiesEncryptionCustomerManagedKeyEncryption,
  ClusterPropertiesEncryptionCustomerManagedKeyEncryptionKeyIdentity,
  CmkIdentityType,
  MaintenanceConfiguration,
  MaintenanceWindow,
  MaintenanceWindowType,
  MaintenanceWindowSchedule,
  MaintenanceDayOfWeek,
  RedundancyMode,
  TrackedResource,
  ClusterUpdate,
  ClusterUpdateProperties,
  SkuDetailsList,
  SkuDetails,
  PrivateLinkResource,
  PrivateLinkResourceProperties,
  AccessPolicyAssignment,
  AccessPolicyAssignmentProperties,
  AccessPolicyAssignmentPropertiesUser,
  Migration,
  MigrationProperties,
  MigrationPropertiesUnion,
  SourceType,
  MigrationProvisioningState,
  AzureCacheForRedisMigrationProperties,
  OperationStatus,
} from "./models/index.js";
export {
  KnownOrigin,
  KnownActionType,
  KnownAccessKeysAuthentication,
  KnownProtocol,
  KnownProvisioningState,
  KnownResourceState,
  KnownClusteringPolicy,
  KnownEvictionPolicy,
  KnownAofFrequency,
  KnownRdbFrequency,
  KnownLinkState,
  KnownDeferUpgradeSetting,
  KnownCreatedByType,
  KnownPrivateEndpointServiceConnectionStatus,
  KnownPrivateEndpointConnectionProvisioningState,
  KnownPublicNetworkAccess,
  KnownKind,
  KnownSkuName,
  KnownManagedServiceIdentityType,
  KnownHighAvailability,
  KnownTlsVersion,
  KnownCmkIdentityType,
  KnownMaintenanceWindowType,
  KnownMaintenanceDayOfWeek,
  KnownRedundancyMode,
  KnownSourceType,
  KnownMigrationProvisioningState,
  KnownVersions,
} from "./models/index.js";
export type { RedisEnterpriseManagementClientOptionalParams } from "./api/index.js";
export type {
  AccessPolicyAssignmentListOptionalParams,
  AccessPolicyAssignmentDeleteOptionalParams,
  AccessPolicyAssignmentCreateUpdateOptionalParams,
  AccessPolicyAssignmentGetOptionalParams,
} from "./api/accessPolicyAssignment/index.js";
export type {
  DatabasesUpgradeDBRedisVersionOptionalParams,
  DatabasesFlushOptionalParams,
  DatabasesForceLinkToReplicationGroupOptionalParams,
  DatabasesForceUnlinkOptionalParams,
  DatabasesExportOptionalParams,
  DatabasesImportOptionalParams,
  DatabasesRegenerateKeyOptionalParams,
  DatabasesListKeysOptionalParams,
  DatabasesListByClusterOptionalParams,
  DatabasesDeleteOptionalParams,
  DatabasesUpdateOptionalParams,
  DatabasesCreateOptionalParams,
  DatabasesGetOptionalParams,
} from "./api/databases/index.js";
export type {
  MigrationCancelOptionalParams,
  MigrationListOptionalParams,
  MigrationStartOptionalParams,
  MigrationGetOptionalParams,
} from "./api/migration/index.js";
export type { OperationsListOptionalParams } from "./api/operations/index.js";
export type { OperationsStatusGetOptionalParams } from "./api/operationsStatus/index.js";
export type {
  PrivateEndpointConnectionsListOptionalParams,
  PrivateEndpointConnectionsDeleteOptionalParams,
  PrivateEndpointConnectionsPutOptionalParams,
  PrivateEndpointConnectionsGetOptionalParams,
} from "./api/privateEndpointConnections/index.js";
export type { PrivateLinkResourcesListByClusterOptionalParams } from "./api/privateLinkResources/index.js";
export type {
  RedisEnterpriseListSkusForScalingOptionalParams,
  RedisEnterpriseListOptionalParams,
  RedisEnterpriseListByResourceGroupOptionalParams,
  RedisEnterpriseDeleteOptionalParams,
  RedisEnterpriseUpdateOptionalParams,
  RedisEnterpriseCreateOptionalParams,
  RedisEnterpriseGetOptionalParams,
} from "./api/redisEnterprise/index.js";
export type {
  AccessPolicyAssignmentOperations,
  DatabasesOperations,
  MigrationOperations,
  OperationsOperations,
  OperationsStatusOperations,
  PrivateEndpointConnectionsOperations,
  PrivateLinkResourcesOperations,
  RedisEnterpriseOperations,
} from "./classic/index.js";
export type { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
export { AzureClouds };
export type { AzureSupportedClouds };
