# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/alertProcessingRules": "src/api/alertProcessingRules/index.ts"
  "./models": "./src/models/index.ts"
