trigger: none

extends:
    template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      PackageName: "@azure-tools/communication-recipient-verification"
      ServiceDirectory: communication
      CloudConfig:
        Communication:
          SubscriptionConfigurations:
            - $(sub-config-communication-services-cloud-test-resources-common)
            - $(sub-config-communication-services-cloud-test-resources-js)
      Clouds: Communication
      SupportedClouds: Communication
      TestResourceDirectories:
        - communication/test-resources/
