/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import type { PagedAsyncIterableIterator } from "@azure/core-paging";
import type { SimplePollerLike, OperationState } from "@azure/core-lro";
import type {
  ConnectedCluster,
  ConnectedClusterListByResourceGroupOptionalParams,
  ConnectedClusterListBySubscriptionOptionalParams,
  ConnectedClusterCreateOrReplaceOptionalParams,
  ConnectedClusterCreateOrReplaceResponse,
  ConnectedClusterPatch,
  ConnectedClusterUpdateOptionalParams,
  ConnectedClusterUpdateResponse,
  ConnectedClusterGetOptionalParams,
  ConnectedClusterGetResponse,
  ConnectedClusterDeleteOptionalParams,
  ListClusterUserCredentialProperties,
  ConnectedClusterListClusterUserCredentialOptionalParams,
  ConnectedClusterListClusterUserCredentialResponse,
} from "../models/index.js";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a ConnectedClusterOperations. */
export interface ConnectedClusterOperations {
  /**
   * API to enumerate registered connected K8s clusters under a Resource Group
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param options The options parameters.
   */
  listByResourceGroup(
    resourceGroupName: string,
    options?: ConnectedClusterListByResourceGroupOptionalParams,
  ): PagedAsyncIterableIterator<ConnectedCluster>;
  /**
   * API to enumerate registered connected K8s clusters under a Subscription
   * @param options The options parameters.
   */
  listBySubscription(
    options?: ConnectedClusterListBySubscriptionOptionalParams,
  ): PagedAsyncIterableIterator<ConnectedCluster>;
  /**
   * API to register a new Kubernetes cluster and create or replace a connected cluster tracked resource
   * in Azure Resource Manager (ARM).
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName The name of the Kubernetes cluster on which get is called.
   * @param connectedCluster Parameters supplied to Create a Connected Cluster.
   * @param options The options parameters.
   */
  beginCreateOrReplace(
    resourceGroupName: string,
    clusterName: string,
    connectedCluster: ConnectedCluster,
    options?: ConnectedClusterCreateOrReplaceOptionalParams,
  ): Promise<
    SimplePollerLike<
      OperationState<ConnectedClusterCreateOrReplaceResponse>,
      ConnectedClusterCreateOrReplaceResponse
    >
  >;
  /**
   * API to register a new Kubernetes cluster and create or replace a connected cluster tracked resource
   * in Azure Resource Manager (ARM).
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName The name of the Kubernetes cluster on which get is called.
   * @param connectedCluster Parameters supplied to Create a Connected Cluster.
   * @param options The options parameters.
   */
  beginCreateOrReplaceAndWait(
    resourceGroupName: string,
    clusterName: string,
    connectedCluster: ConnectedCluster,
    options?: ConnectedClusterCreateOrReplaceOptionalParams,
  ): Promise<ConnectedClusterCreateOrReplaceResponse>;
  /**
   * API to update certain properties of the connected cluster resource
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName The name of the Kubernetes cluster on which get is called.
   * @param connectedClusterPatch Parameters supplied to update Connected Cluster.
   * @param options The options parameters.
   */
  update(
    resourceGroupName: string,
    clusterName: string,
    connectedClusterPatch: ConnectedClusterPatch,
    options?: ConnectedClusterUpdateOptionalParams,
  ): Promise<ConnectedClusterUpdateResponse>;
  /**
   * Returns the properties of the specified connected cluster, including name, identity, properties, and
   * additional cluster details.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName The name of the Kubernetes cluster on which get is called.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    clusterName: string,
    options?: ConnectedClusterGetOptionalParams,
  ): Promise<ConnectedClusterGetResponse>;
  /**
   * Delete a connected cluster, removing the tracked resource in Azure Resource Manager (ARM).
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName The name of the Kubernetes cluster on which get is called.
   * @param options The options parameters.
   */
  beginDelete(
    resourceGroupName: string,
    clusterName: string,
    options?: ConnectedClusterDeleteOptionalParams,
  ): Promise<SimplePollerLike<OperationState<void>, void>>;
  /**
   * Delete a connected cluster, removing the tracked resource in Azure Resource Manager (ARM).
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName The name of the Kubernetes cluster on which get is called.
   * @param options The options parameters.
   */
  beginDeleteAndWait(
    resourceGroupName: string,
    clusterName: string,
    options?: ConnectedClusterDeleteOptionalParams,
  ): Promise<void>;
  /**
   * Gets cluster user credentials of the connected cluster with a specified resource group and name.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName The name of the Kubernetes cluster on which get is called.
   * @param properties ListClusterUserCredential properties
   * @param options The options parameters.
   */
  listClusterUserCredential(
    resourceGroupName: string,
    clusterName: string,
    properties: ListClusterUserCredentialProperties,
    options?: ConnectedClusterListClusterUserCredentialOptionalParams,
  ): Promise<ConnectedClusterListClusterUserCredentialResponse>;
}
