exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/skus": "./src/api/skus/index.ts"
  "./api/volumeSnapshots": "./src/api/volumeSnapshots/index.ts"
  "./api/privateLinkResources": "./src/api/privateLinkResources/index.ts"
  "./api/volumeGroups": "./src/api/volumeGroups/index.ts"
  "./api/volumes": "./src/api/volumes/index.ts"
  "./api/privateEndpointConnections": "./src/api/privateEndpointConnections/index.ts"
  "./api/elasticSans": "./src/api/elasticSans/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"
  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
    moduleType: commonjs
