// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export { AzureKeyCredential, AzureSASCredential } from "@azure/core-auth";

export type {
  CloudEvent,
  EventGridEvent,
  SendCloudEventInput,
  SendEventGridEventInput,
} from "./models.js";

export {
  EventGridPublisherClient,
  type EventGridPublisherClientOptions,
  type SendOptions,
  type CloudEventSendOptions,
  type InputSchema,
  type InputSchemaToInputTypeMap,
  type InputSchemaToOptionsTypeMap,
} from "./eventGridClient.js";

export {
  generateSharedAccessSignature,
  type GenerateSharedAccessSignatureOptions,
} from "./generateSharedAccessSignature.js";

export { EventGridDeserializer } from "./consumer.js";

export {
  isSystemEvent,
  type KnownSystemEventTypes,
  type SystemEventNameToEventData,
} from "./predicates.js";

export {
  type AcsCallEndedBy,
  type AcsCallEndedByKind,
  type AcsCallEndedEventData,
  type AcsCallEndReason,
  type AcsCallGroup,
  type AcsCallingEvent,
  type AcsCallParticipantAddedEventData,
  type AcsCallParticipantRemovedEventData,
  type AcsCallParticipant,
  type AcsCallParticipantEventData,
  type AcsCallRoom,
  type AcsCallStartedEventData,
  type AcsChatAzureBotCommandReceivedInThreadEventData,
  type AcsChatTypingIndicatorReceivedInThreadEventData,
  type ApiManagementCircuitBreaker,
  type ApiManagementCircuitBreakerOpenedEventData,
  type ApiManagementCircuitBreakerClosedEventData,
  type ApiManagementExpiredGatewayToken,
  type ApiManagementGateway,
  type ApiManagementGatewayTokenExpiredEventData,
  type ApiManagementGatewayTokenNearExpiry,
  type ApiManagementGatewayTokenNearExpiryEventData,
  type AcsChatEventBase,
  type AcsChatEventInThreadBase,
  type AcsChatMessageEventInThreadBase,
  type AcsChatMessageDeletedEventData,
  type AcsChatMessageDeletedInThreadEventData,
  type AcsChatMessageEditedEventData,
  type AcsChatMessageEditedInThreadEventData,
  type AcsChatMessageReceivedEventData,
  type AcsChatMessageReceivedInThreadEventData,
  type AcsChatMessageEventBase,
  type AcsChatThreadCreatedWithUserEventData,
  type AcsChatThreadPropertiesUpdatedPerUserEventData,
  type AcsChatThreadWithUserDeletedEventData,
  type AcsChatThreadEventBase,
  type AcsChatParticipantAddedToThreadEventData,
  type AcsChatParticipantAddedToThreadWithUserEventData,
  type AcsChatParticipantRemovedFromThreadEventData,
  type AcsChatParticipantRemovedFromThreadWithUserEventData,
  type AcsRecordingFileStatusUpdatedEventData,
  type AcsRecordingStorageInfo,
  type AcsRecordingChunkInfo,
  type ApiManagementApiCreatedEventData,
  type ApiManagementApiDeletedEventData,
  type ApiManagementApiReleaseCreatedEventData,
  type ApiManagementApiReleaseDeletedEventData,
  type ApiManagementApiReleaseUpdatedEventData,
  type ApiManagementApiUpdatedEventData,
  type ApiManagementProductCreatedEventData,
  type ApiManagementProductDeletedEventData,
  type ApiManagementProductUpdatedEventData,
  type ApiManagementSubscriptionCreatedEventData,
  type ApiManagementSubscriptionDeletedEventData,
  type ApiManagementSubscriptionUpdatedEventData,
  type ApiManagementUserCreatedEventData,
  type ApiManagementUserDeletedEventData,
  type ApiManagementUserUpdatedEventData,
  type CommunicationIdentifierModel,
  type CommunicationUserIdentifierModel,
  type CommunicationCloudEnvironmentModel,
  type MicrosoftTeamsUserIdentifierModel,
  type PhoneNumberIdentifierModel,
  type AcsChatThreadParticipant,
  type AcsUserDisconnectedEventData,
  type AcsSmsDeliveryAttempt,
  type AcsSmsDeliveryReportReceivedEventData,
  type AcsSmsEventBase,
  type AcsSmsReceivedEventData,
  type AppConfigurationKeyValueDeletedEventData,
  type AppConfigurationKeyValueModifiedEventData,
  type AppEventTypeDetail,
  type AppServicePlanEventTypeDetail,
  type ContainerRegistryArtifactEventTarget,
  type ContainerRegistryEventData,
  type ContainerRegistryImagePushedEventData,
  type ContainerRegistryImageDeletedEventData,
  type ContainerRegistryChartDeletedEventData,
  type ContainerRegistryChartPushedEventData,
  type ContainerServiceNewKubernetesVersionAvailableEventData,
  type DeviceConnectionStateEventInfo,
  type DeviceTwinInfo,
  type DeviceTwinInfoProperties,
  type DeviceTwinInfoX509Thumbprint,
  type HealthcareDicomImageCreatedEventData,
  type HealthcareDicomImageDeletedEventData,
  type HealthcareFhirResourceCreatedEventData,
  type HealthcareFhirResourceUpdatedEventData,
  type HealthcareFhirResourceDeletedEventData,
  type HealthcareFhirResourceType,
  type IotHubDeviceCreatedEventData,
  type IotHubDeviceDeletedEventData,
  type IotHubDeviceConnectedEventData,
  type IotHubDeviceDisconnectedEventData,
  type IotHubDeviceTelemetryEventData,
  type KeyVaultCertificateNewVersionCreatedEventData,
  type KeyVaultCertificateNearExpiryEventData,
  type KeyVaultCertificateExpiredEventData,
  type KeyVaultKeyNewVersionCreatedEventData,
  type KeyVaultKeyNearExpiryEventData,
  type KeyVaultKeyExpiredEventData,
  type KeyVaultSecretNewVersionCreatedEventData,
  type KeyVaultSecretNearExpiryEventData,
  type KeyVaultSecretExpiredEventData,
  type KeyVaultAccessPolicyChangedEventData,
  type SubscriptionValidationEventData,
  type SubscriptionDeletedEventData,
  type EdgeSolutionVersionPublishedEventData,
  type EventHubCaptureFileCreatedEventData,
  type MachineLearningServicesDatasetDriftDetectedEventData,
  type MachineLearningServicesModelDeployedEventData,
  type MachineLearningServicesModelRegisteredEventData,
  type MachineLearningServicesRunCompletedEventData,
  type MachineLearningServicesRunStatusChangedEventData,
  type MapsGeofenceEvent,
  type MapsGeofenceEnteredEventData,
  type MapsGeofenceExitedEventData,
  type MapsGeofenceResultEventData,
  type MediaJobStateChangeEventData,
  type MediaJobOutputStateChangeEventData,
  type MediaJobScheduledEventData,
  type MediaJobProcessingEventData,
  type MediaJobCancelingEventData,
  type MediaJobFinishedEventData,
  type MediaJobCanceledEventData,
  type MediaJobError,
  type MediaJobErrorCategory,
  type MediaJobErrorDetail,
  type MediaJobErrorCode,
  type MediaJobRetry,
  type MediaJobErroredEventData,
  type MediaJobOutputCanceledEventData,
  type MediaJobOutputCancelingEventData,
  type MediaJobOutputErroredEventData,
  type MediaJobOutputFinishedEventData,
  type MediaJobOutputProcessingEventData,
  type MediaJobOutputScheduledEventData,
  type MediaJobOutputProgressEventData,
  type MediaJobOutputUnion,
  type MediaJobState,
  type MediaLiveEventChannelArchiveHeartbeatEventData,
  type MediaLiveEventEncoderConnectedEventData,
  type MediaLiveEventConnectionRejectedEventData,
  type MediaLiveEventEncoderDisconnectedEventData,
  type MediaLiveEventIncomingStreamReceivedEventData,
  type MediaLiveEventIncomingStreamsOutOfSyncEventData,
  type MediaLiveEventIncomingVideoStreamsOutOfSyncEventData,
  type MediaLiveEventIncomingDataChunkDroppedEventData,
  type MediaLiveEventIngestHeartbeatEventData,
  type MediaLiveEventTrackDiscontinuityDetectedEventData,
  type ResourceWriteSuccessEventData,
  type ResourceWriteFailureEventData,
  type ResourceWriteCancelEventData,
  type ResourceDeleteSuccessEventData,
  type ResourceDeleteFailureEventData,
  type ResourceDeleteCancelEventData,
  type ResourceActionSuccessEventData,
  type ResourceActionFailureEventData,
  type ResourceActionCancelEventData,
  type ServiceBusActiveMessagesAvailableWithNoListenersEventData,
  type ServiceBusDeadletterMessagesAvailableWithNoListenersEventData,
  type StorageBlobCreatedEventData,
  type StorageBlobDeletedEventData,
  type StorageBlobRenamedEventData,
  type StorageDirectoryCreatedEventData,
  type StorageDirectoryDeletedEventData,
  type StorageDirectoryRenamedEventData,
  type StorageLifecyclePolicyActionSummaryDetail,
  type StorageLifecyclePolicyCompletedEventData,
  type WebAppUpdatedEventData,
  type WebBackupOperationStartedEventData,
  type WebBackupOperationCompletedEventData,
  type WebBackupOperationFailedEventData,
  type WebRestoreOperationStartedEventData,
  type WebRestoreOperationCompletedEventData,
  type WebRestoreOperationFailedEventData,
  type WebSlotSwapStartedEventData,
  type WebSlotSwapCompletedEventData,
  type WebSlotSwapFailedEventData,
  type WebSlotSwapWithPreviewStartedEventData,
  type WebSlotSwapWithPreviewCancelledEventData,
  type WebAppServicePlanUpdatedEventData,
  type WebAppServicePlanUpdatedEventDataSku,
  type AppAction,
  KnownAppAction,
  type StampKind,
  KnownStampKind,
  type AsyncStatus,
  KnownAsyncStatus,
  type ContainerRegistryArtifactEventData,
  type ContainerRegistryEventActor,
  type ContainerRegistryEventRequest,
  type ContainerRegistryEventSource,
  type ContainerRegistryEventTarget,
  type DeviceConnectionStateEvent,
  type DeviceLifeCycleEvent,
  type DeviceTelemetryEvent,
  type MapsGeofenceGeometry,
  type MediaJobOutput,
  type MediaJobOutputAsset,
  type DeviceTwin,
  type DeviceTwinMetadata,
  type AppServicePlanAction,
  KnownAppServicePlanAction,
  type PolicyInsightsPolicyStateChangedEventData,
  type PolicyInsightsPolicyStateCreatedEventData,
  type PolicyInsightsPolicyStateDeletedEventData,
  type StorageAsyncOperationInitiatedEventData,
  type StorageBlobTierChangedEventData,
  type StorageBlobInventoryPolicyCompletedEventData,
  type RecordingChannelType,
  type RecordingContentType,
  type RecordingFormatType,
  type ResourceAuthorization,
  type ResourceHttpRequest,
  type ContainerRegistryEventConnectedRegistry,
  type StorageTaskQueuedEventData,
  type StorageTaskCompletedEventData,
  type DataBoxCopyStartedEventData,
  type DataBoxCopyCompletedEventData,
  type DataBoxOrderCompletedEventData,
  type AcsIncomingCallEventData,
  type AcsEmailDeliveryReportReceivedEventData,
  type AcsEmailEngagementTrackingReportReceivedEventData,
  type ApiManagementGatewayCreatedEventData,
  type ApiManagementGatewayUpdatedEventData,
  type ApiManagementGatewayDeletedEventData,
  type ApiManagementGatewayHostnameConfigurationCreatedEventData,
  type ApiManagementGatewayHostnameConfigurationUpdatedEventData,
  type ApiManagementGatewayHostnameConfigurationDeletedEventData,
  type ApiManagementGatewayCertificateAuthorityCreatedEventData,
  type ApiManagementGatewayCertificateAuthorityUpdatedEventData,
  type ApiManagementGatewayCertificateAuthorityDeletedEventData,
  type ApiManagementGatewayApiAddedEventData,
  type ApiManagementGatewayApiRemovedEventData,
  type HealthcareDicomImageUpdatedEventData,
  type AcsEmailDeliveryReportStatusDetails,
  type AcsEmailDeliveryReportStatus,
  type AcsUserEngagement,
  type AcsIncomingCallCustomContext,
  type DataBoxStageName,
  type StorageTaskCompletedStatus,
  type ContainerServiceClusterSupportEndedEventData,
  type ContainerServiceClusterSupportEndingEventData,
  type ContainerServiceNodePoolRollingStartedEventData,
  type ContainerServiceNodePoolRollingSucceededEventData,
  type ContainerServiceNodePoolRollingFailedEventData,
  type ContainerServiceClusterSupportEventData,
  type ContainerServiceNodePoolRollingEventData,
  type EventGridMqttClientCreatedOrUpdatedEventData,
  type EventGridMqttClientDeletedEventData,
  type EventGridMqttClientSessionConnectedEventData,
  type EventGridMqttClientSessionDisconnectedEventData,
  type EventGridMqttClientEventData,
  type EventGridMqttClientState,
  KnownEventGridMqttClientState,
  type EventGridMqttClientDisconnectionReason,
  KnownEventGridMqttClientDisconnectionReason,
  type AppConfigurationSnapshotCreatedEventData,
  type AppConfigurationSnapshotModifiedEventData,
  type AppConfigurationSnapshotEventData,
  type AcsRouterJobEventData,
  type AcsRouterWorkerEventData,
  type AcsRouterWorkerDeregisteredEventData,
  type AcsRouterWorkerRegisteredEventData,
  type ResourceNotificationsResourceUpdatedEventData,
  type ResourceNotificationsOperationalDetails,
  type ResourceNotificationsResourceUpdatedDetails,
  type ResourceNotificationsHealthResourcesAvailabilityStatusChangedEventData,
  type ResourceNotificationsHealthResourcesAnnotatedEventData,
  type AcsRouterCommunicationError,
  type AcsRouterQueueDetails,
  type AcsRouterWorkerSelector,
  type AcsRouterJobStatus,
  KnownAcsRouterJobStatus,
  type AcsRouterEventData,
  type AcsRouterLabelOperator,
  KnownAcsRouterLabelOperator,
  type AcsRouterWorkerSelectorState,
  KnownAcsRouterWorkerSelectorState,
  type AcsRouterJobCancelledEventData,
  type AcsRouterJobClassificationFailedEventData,
  type AcsRouterJobClassifiedEventData,
  type AcsRouterJobClosedEventData,
  type AcsRouterJobCompletedEventData,
  type AcsRouterJobDeletedEventData,
  type AcsRouterJobExceptionTriggeredEventData,
  type AcsRouterJobQueuedEventData,
  type AcsRouterJobReceivedEventData,
  type AcsRouterJobSchedulingFailedEventData,
  type AcsRouterJobUnassignedEventData,
  type AcsRouterJobWaitingForActivationEventData,
  type AcsRouterJobWorkerSelectorsExpiredEventData,
  type AcsRouterWorkerDeletedEventData,
  type AcsRouterWorkerOfferAcceptedEventData,
  type AcsRouterWorkerOfferDeclinedEventData,
  type AcsRouterWorkerOfferExpiredEventData,
  type AcsRouterWorkerOfferIssuedEventData,
  type AcsRouterWorkerOfferRevokedEventData,
  type AcsRouterChannelConfiguration,
  type ResourceNotificationsResourceManagementCreatedOrUpdatedEventData,
  type ResourceNotificationsResourceManagementDeletedEventData,
  type ResourceNotificationsResourceDeletedEventData,
  type ResourceNotificationsResourceDeletedDetails,
  type StorageTaskAssignmentQueuedEventData,
  type AvsScriptExecutionStartedEventData,
  type AvsScriptExecutionCancelledEventData,
  type AvsClusterCreatedEventData,
  type AvsPrivateCloudFailedEventData,
  type AvsPrivateCloudUpdatingEventData,
  type AvsPrivateCloudUpdatedEventData,
  type AvsClusterUpdatingEventData,
  type AvsClusterDeletedEventData,
  type AvsScriptExecutionFailedEventData,
  type AvsScriptExecutionFinishedEventData,
  type StorageTaskAssignmentCompletedEventData,
  type AvsClusterUpdatedEventData,
  type AvsClusterFailedEventData,
  type AvsClusterEventData,
  type AvsPrivateCloudEventData,
  type AvsScriptExecutionEventData,
  type StorageTaskAssignmentCompletedStatus,
  KnownStorageTaskCompletedStatus,
  KnownStorageTaskAssignmentCompletedStatus,
  KnownDataBoxStageName,
  KnownCommunicationCloudEnvironmentModel,
  KnownRecordingContentType,
  KnownRecordingChannelType,
  KnownRecordingFormatType,
  KnownAcsCallEndedByKind,
  KnownAcsEmailDeliveryReportStatus,
  KnownAcsUserEngagement,
  KnownHealthcareFhirResourceType,
  type ApiCenterApiDefinitionAddedEventData,
  type ApiCenterApiDefinitionUpdatedEventData,
  type ApiCenterApiSpecification,
  type AcsMessageDeliveryStatusUpdatedEventData,
  type AcsMessageReactionContent,
  type AcsMessageReceivedEventData,
  type AcsRouterWorkerUpdatedEventData,
  type AcsMessageEventData,
  type AcsRouterUpdatedWorkerProperty,
  KnownAcsRouterUpdatedWorkerProperty,
  type CommunicationIdentifierModelKind,
  KnownCommunicationIdentifierModelKind,
  type MicrosoftTeamsAppIdentifierModel,
  type AcsMessageMediaContent,
  type AcsMessageContext,
  type AcsMessageButtonContent,
  type AcsMessageInteractiveContent,
  type AcsMessageChannelKind,
  KnownAcsMessageChannelKind,
  type AcsMessageChannelEventError,
  type AcsMessageInteractiveButtonReplyContent,
  type AcsMessageInteractiveListReplyContent,
  type AcsInteractiveReplyKind,
  KnownAcsInteractiveReplyKind,
  type AcsMessageDeliveryStatus,
  KnownAcsMessageDeliveryStatus,
  type AcsChatThreadCreatedEventData,
  type AcsChatThreadDeletedEventData,
  type AcsChatThreadPropertiesUpdatedEventData,
  type AcsChatThreadEventInThreadBase,
  type StorageBlobAccessTier,
  type ResourceNotificationsContainerServiceEventResourcesScheduledEventData,
  type StorageLifecyclePolicyRunSummary,
  type StorageLifecycleCompletionStatus,
  KnownStorageLifecycleCompletionStatus,
} from "./generated/models/index.js";
