exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/recoveryServices": "./src/api/recoveryServices/index.ts"
  "./api/vaultExtendedInfo": "./src/api/vaultExtendedInfo/index.ts"
  "./api/usages": "./src/api/usages/index.ts"
  "./api/replicationUsages": "./src/api/replicationUsages/index.ts"
  "./api/registeredIdentities": "./src/api/registeredIdentities/index.ts"
  "./api/vaultCertificates": "./src/api/vaultCertificates/index.ts"
  "./api/privateLinkResources": "./src/api/privateLinkResources/index.ts"
  "./api/deletedVaults": "./src/api/deletedVaults/index.ts"
  "./api/vaults": "./src/api/vaults/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"
  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
