extends: ../../../warp.base.config.yml
exports:
  "./api": "./src/api/index.ts"
  "./api/solutionTypes": "./src/api/solutionTypes/index.ts"
  "./api/inventory": "./src/api/inventory/index.ts"
  "./api/solutionConfigurations": "./src/api/solutionConfigurations/index.ts"
  "./api/publicCloudConnectors": "./src/api/publicCloudConnectors/index.ts"
  "./api/generateAwsTemplate": "./src/api/generateAwsTemplate/index.ts"
  "./api/serviceConfigurations": "./src/api/serviceConfigurations/index.ts"
  "./api/endpoints": "./src/api/endpoints/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"
