# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/suppressionListAddresses": "src/api/suppressionListAddresses/index.ts"
  "./api/suppressionLists": "src/api/suppressionLists/index.ts"
  "./api/smtpUsernames": "src/api/smtpUsernames/index.ts"
  "./api/senderUsernames": "src/api/senderUsernames/index.ts"
  "./api/emailServices": "src/api/emailServices/index.ts"
  "./api/domains": "src/api/domains/index.ts"
  "./api/communicationServices": "src/api/communicationServices/index.ts"
  "./api/operations": "src/api/operations/index.ts"
  "./models": "./src/models/index.ts"
