# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/alertRuleRecommendations": "src/api/alertRuleRecommendations/index.ts"
  "./models": "./src/models/index.ts"
