exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/endpoints": "./src/api/endpoints/index.ts"
  "./api/neonRoles": "./src/api/neonRoles/index.ts"
  "./api/neonDatabases": "./src/api/neonDatabases/index.ts"
  "./api/computes": "./src/api/computes/index.ts"
  "./api/branches": "./src/api/branches/index.ts"
  "./api/projects": "./src/api/projects/index.ts"
  "./api/organizations": "./src/api/organizations/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"
  "./models/models": "./src/models/models/index.ts"

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"
  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
