# warp.config.yml — @typespec/ts-http-runtime build configuration

exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./internal/util": "./src/util/internal.ts"
  "./internal/logger": "./src/logger/internal.ts"
  "./internal/policies": "./src/policies/internal.ts"

targets:
  - name: browser
    tsconfig: "./config/tsconfig.src.browser.json"

  - name: react-native
    tsconfig: "./config/tsconfig.src.react-native.json"

  - name: esm
    condition: import
    tsconfig: "./config/tsconfig.src.esm.json"

  - name: commonjs
    condition: require
    tsconfig: "./config/tsconfig.src.cjs.json"
    moduleType: commonjs
