extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/certificateRegistrationProvider": "./src/api/certificateRegistrationProvider/index.ts"
  "./api/certificateOrdersDiagnostics": "./src/api/certificateOrdersDiagnostics/index.ts"
  "./api/appServiceCertificateOrders": "./src/api/appServiceCertificateOrders/index.ts"
  "./models": "./src/models/index.ts"
