/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as msRestAzure from "@azure/ms-rest-azure-js";
import * as Models from "../models";
import * as Mappers from "../models/virtualMachinesMappers";
import * as Parameters from "../models/parameters";
import { HDInsightManagementClientContext } from "../hDInsightManagementClientContext";

/** Class representing a VirtualMachines. */
export class VirtualMachines {
  private readonly client: HDInsightManagementClientContext;

  /**
   * Create a VirtualMachines.
   * @param {HDInsightManagementClientContext} client Reference to the service client.
   */
  constructor(client: HDInsightManagementClientContext) {
    this.client = client;
  }

  /**
   * Lists the HDInsight clusters hosts
   * @param resourceGroupName The name of the resource group.
   * @param clusterName The name of the cluster.
   * @param [options] The optional parameters
   * @returns Promise<Models.VirtualMachinesListHostsResponse>
   */
  listHosts(
    resourceGroupName: string,
    clusterName: string,
    options?: msRest.RequestOptionsBase
  ): Promise<Models.VirtualMachinesListHostsResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param clusterName The name of the cluster.
   * @param callback The callback
   */
  listHosts(
    resourceGroupName: string,
    clusterName: string,
    callback: msRest.ServiceCallback<Models.HostInfo[]>
  ): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param clusterName The name of the cluster.
   * @param options The optional parameters
   * @param callback The callback
   */
  listHosts(
    resourceGroupName: string,
    clusterName: string,
    options: msRest.RequestOptionsBase,
    callback: msRest.ServiceCallback<Models.HostInfo[]>
  ): void;
  listHosts(
    resourceGroupName: string,
    clusterName: string,
    options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.HostInfo[]>,
    callback?: msRest.ServiceCallback<Models.HostInfo[]>
  ): Promise<Models.VirtualMachinesListHostsResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        clusterName,
        options
      },
      listHostsOperationSpec,
      callback
    ) as Promise<Models.VirtualMachinesListHostsResponse>;
  }

  /**
   * Restarts the specified HDInsight cluster hosts.
   * @param resourceGroupName The name of the resource group.
   * @param clusterName The name of the cluster.
   * @param hosts The list of hosts to restart
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  restartHosts(
    resourceGroupName: string,
    clusterName: string,
    hosts: string[],
    options?: msRest.RequestOptionsBase
  ): Promise<msRest.RestResponse> {
    return this.beginRestartHosts(
      resourceGroupName,
      clusterName,
      hosts,
      options
    ).then((lroPoller) => lroPoller.pollUntilFinished());
  }

  /**
   * Gets the async operation status.
   * @param resourceGroupName The name of the resource group.
   * @param clusterName The name of the cluster.
   * @param operationId The long running operation id.
   * @param [options] The optional parameters
   * @returns Promise<Models.VirtualMachinesGetAsyncOperationStatusResponse>
   */
  getAsyncOperationStatus(
    resourceGroupName: string,
    clusterName: string,
    operationId: string,
    options?: msRest.RequestOptionsBase
  ): Promise<Models.VirtualMachinesGetAsyncOperationStatusResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param clusterName The name of the cluster.
   * @param operationId The long running operation id.
   * @param callback The callback
   */
  getAsyncOperationStatus(
    resourceGroupName: string,
    clusterName: string,
    operationId: string,
    callback: msRest.ServiceCallback<Models.AsyncOperationResult>
  ): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param clusterName The name of the cluster.
   * @param operationId The long running operation id.
   * @param options The optional parameters
   * @param callback The callback
   */
  getAsyncOperationStatus(
    resourceGroupName: string,
    clusterName: string,
    operationId: string,
    options: msRest.RequestOptionsBase,
    callback: msRest.ServiceCallback<Models.AsyncOperationResult>
  ): void;
  getAsyncOperationStatus(
    resourceGroupName: string,
    clusterName: string,
    operationId: string,
    options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.AsyncOperationResult>,
    callback?: msRest.ServiceCallback<Models.AsyncOperationResult>
  ): Promise<Models.VirtualMachinesGetAsyncOperationStatusResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        clusterName,
        operationId,
        options
      },
      getAsyncOperationStatusOperationSpec,
      callback
    ) as Promise<Models.VirtualMachinesGetAsyncOperationStatusResponse>;
  }

  /**
   * Restarts the specified HDInsight cluster hosts.
   * @param resourceGroupName The name of the resource group.
   * @param clusterName The name of the cluster.
   * @param hosts The list of hosts to restart
   * @param [options] The optional parameters
   * @returns Promise<msRestAzure.LROPoller>
   */
  beginRestartHosts(
    resourceGroupName: string,
    clusterName: string,
    hosts: string[],
    options?: msRest.RequestOptionsBase
  ): Promise<msRestAzure.LROPoller> {
    return this.client.sendLRORequest(
      {
        resourceGroupName,
        clusterName,
        hosts,
        options
      },
      beginRestartHostsOperationSpec,
      options
    );
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const listHostsOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path:
    "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HDInsight/clusters/{clusterName}/listHosts",
  urlParameters: [Parameters.subscriptionId, Parameters.resourceGroupName, Parameters.clusterName],
  queryParameters: [Parameters.apiVersion],
  headerParameters: [Parameters.acceptLanguage],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "HostInfo"
            }
          }
        }
      }
    },
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  serializer
};

const getAsyncOperationStatusOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path:
    "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HDInsight/clusters/{clusterName}/restartHosts/azureasyncoperations/{operationId}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.clusterName,
    Parameters.operationId
  ],
  queryParameters: [Parameters.apiVersion],
  headerParameters: [Parameters.acceptLanguage],
  responses: {
    200: {
      bodyMapper: Mappers.AsyncOperationResult
    },
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  serializer
};

const beginRestartHostsOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path:
    "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HDInsight/clusters/{clusterName}/restartHosts",
  urlParameters: [Parameters.subscriptionId, Parameters.resourceGroupName, Parameters.clusterName],
  queryParameters: [Parameters.apiVersion],
  headerParameters: [Parameters.acceptLanguage],
  requestBody: {
    parameterPath: "hosts",
    mapper: {
      required: true,
      serializedName: "hosts",
      type: {
        name: "Sequence",
        element: {
          type: {
            name: "String"
          }
        }
      }
    }
  },
  responses: {
    200: {},
    202: {},
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  serializer
};
