# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./models": "./src/models/index.ts"
  "./models/common": "./src/models/common/index.ts"
  "./models/compute": "./src/models/compute/index.ts"
  "./models/computeDisk": "./src/models/computeDisk/index.ts"
  "./models/computeGallery": "./src/models/computeGallery/index.ts"
  "./models/computeSku": "./src/models/computeSku/index.ts"
