exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/siteReferences": "./src/api/siteReferences/index.ts"
  "./api/contexts": "./src/api/contexts/index.ts"
  "./api/diagnostics": "./src/api/diagnostics/index.ts"
  "./api/executions": "./src/api/executions/index.ts"
  "./api/workflowVersions": "./src/api/workflowVersions/index.ts"
  "./api/workflows": "./src/api/workflows/index.ts"
  "./api/configTemplateVersions": "./src/api/configTemplateVersions/index.ts"
  "./api/configTemplates": "./src/api/configTemplates/index.ts"
  "./api/instanceHistories": "./src/api/instanceHistories/index.ts"
  "./api/instances": "./src/api/instances/index.ts"
  "./api/solutionTemplates": "./src/api/solutionTemplates/index.ts"
  "./api/solutionTemplateVersions": "./src/api/solutionTemplateVersions/index.ts"
  "./api/solutions": "./src/api/solutions/index.ts"
  "./api/schemaReferences": "./src/api/schemaReferences/index.ts"
  "./api/dynamicSchemaVersions": "./src/api/dynamicSchemaVersions/index.ts"
  "./api/targets": "./src/api/targets/index.ts"
  "./api/jobs": "./src/api/jobs/index.ts"
  "./api/solutionVersions": "./src/api/solutionVersions/index.ts"
  "./api/schemaVersions": "./src/api/schemaVersions/index.ts"
  "./api/schemas": "./src/api/schemas/index.ts"
  "./api/dynamicSchemas": "./src/api/dynamicSchemas/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"
  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
    moduleType: commonjs
