# warp.config.yml — build configuration

exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/usages": "./src/api/usages/index.ts"
  "./api/resourceSkus": "./src/api/resourceSkus/index.ts"
  "./api/files": "./src/api/files/index.ts"
  "./api/tasks": "./src/api/tasks/index.ts"
  "./api/services": "./src/api/services/index.ts"
  "./api/databaseMigrationsSqlVm": "./src/api/databaseMigrationsSqlVm/index.ts"
  "./api/databaseMigrationsSqlMi": "./src/api/databaseMigrationsSqlMi/index.ts"
  "./api/databaseMigrationsSqlDb": "./src/api/databaseMigrationsSqlDb/index.ts"
  "./api/databaseMigrationsMongoToCosmosDbRUMongo": "./src/api/databaseMigrationsMongoToCosmosDbRUMongo/index.ts"
  "./api/projects": "./src/api/projects/index.ts"
  "./api/serviceTasks": "./src/api/serviceTasks/index.ts"
  "./api/sqlMigrationServices": "./src/api/sqlMigrationServices/index.ts"
  "./api/migrationServices": "./src/api/migrationServices/index.ts"
  "./api/databaseMigrationsMongoToCosmosDbvCoreMongo": "./src/api/databaseMigrationsMongoToCosmosDbvCoreMongo/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "./config/tsconfig.src.browser.json"

  - name: esm
    condition: import
    tsconfig: "./config/tsconfig.src.esm.json"

  - name: commonjs
    condition: require
    tsconfig: "./config/tsconfig.src.cjs.json"
    moduleType: commonjs
