let nock = require('nock');

module.exports.testInfo = {"uniqueName":{},"newDate":{}}

nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .post('/certificates/mergeCertificateName-canmergeaselfsignedcertificate-/create')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '91667278-0bf5-4b4f-a4fa-8953ebd7078b',
  'x-ms-keyvault-service-version',
  '1.1.0.878',
  'x-ms-keyvault-network-info',
  'addr=23.100.22.158;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 03 Oct 2019 01:44:30 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3599,"ext_expires_in":3599,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '545a3cb0-cd17-4266-9542-c56dcdf20c00',
  'x-ms-ests-server',
  '2.1.9485.10 - EUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AixHjqJQOPlAjnAlQtMysPw_aSJHAQAAAH5JJ9UOAAAA; expires=Sat, 02-Nov-2019 01:44:30 GMT; path=/; secure; HttpOnly; SameSite=None',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 03 Oct 2019 01:44:30 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .post('/certificates/mergeCertificateName-canmergeaselfsignedcertificate-/create', {"policy":{"key_props":{},"secret_props":{},"x509_props":{"subject":"cn=MyCert","sans":{}},"issuer":{"name":"Unknown","cert_transparency":false},"attributes":{}},"attributes":{}})
  .query(true)
  .reply(202, {"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeaselfsignedcertificate-/pending","issuer":{"name":"Unknown"},"csr":"MIICoTCCAYkCAQAwETEPMA0GA1UEAxMGTXlDZXJ0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA06bnm7Y+Rwv0p2iGvlaH/Iz1DXwVMF1GsmjqMGz/gQlkNt2KFHRPALnNxa18sIwvKDJ9OS5Qxd7PH/MKFkoErZewQT8/+HJu/vRoRtR9XX1+WFGKDDMzEXfbJcAMBvJBsXh90KI8EfqQ+DqM4O5WuKtz0+RWAYI1Xl4oMbm5GqLfugWzteW3Yroob9tzc8SOKwjbEc0lRZ3F6qpmII4ic9weiMYbWmH8abEpDA79RDpEjEshQUU3PU1i/diPXPDjU4UR/ybzNAGMvMAuQPm9pP4JA0DGfj7wUVvp95H9kde5ayU4+zz2qkrB7OfhIHd28t+pIqC5ZllaNV2lK3dJGQIDAQABoEswSQYJKoZIhvcNAQkOMTwwOjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggEBAKKqT1TaXp7UptXXoGBFifI7UvLQDI7B8YnDqm4U/4JvQCiM2RXcT0gejZ/dHDzXYHAcSOYzhjwtQNZm4GNg2fVgU3R7HLgT3cQtIpy0Ox0R6uBYtoWqMshttB3xJvKxLY2KG1Q560E6yTGmDs4uj2Lu15/arEXVOZp4e2GXUimk44seBBLpkailgXgdp0qA/m7/nlKRsAkLeeQp+Yqa7awmYPcsJF/AQCsuQI1xSwTXhmQLmRFtNp7voeQSb0rqY3Y/OxfpKWxqmoKcVmfsiuY7gXBdRIg5yBpKvpnLke0cNfBrzN6Dq1WePz8Xa/BIpAHDrSZZDFmalpDpkpEU8lQ=","cancellation_requested":false,"status":"inProgress","status_details":"Pending certificate created. Please Perform Merge to complete the request.","request_id":"1be9966d1fe34fc1b16df923204a436f"}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Location',
  'https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeaselfsignedcertificate-/pending?api-version=7.0&request_id=1be9966d1fe34fc1b16df923204a436f',
  'Retry-After',
  '10',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '0d16575b-d2ba-4a48-8208-27546abf2d86',
  'x-ms-keyvault-service-version',
  '1.1.0.878',
  'x-ms-keyvault-network-info',
  'addr=23.100.22.158;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 03 Oct 2019 01:44:30 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1270' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .get('/certificates/mergeCertificateName-canmergeaselfsignedcertificate-/pending')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'd84a4ee8-b1f5-4442-8654-60e71dd0853b',
  'x-ms-keyvault-service-version',
  '1.1.0.878',
  'x-ms-keyvault-network-info',
  'addr=23.100.22.158;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 03 Oct 2019 01:44:31 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '52afee2a-411c-4e6e-aecb-c3d142d80900',
  'x-ms-ests-server',
  '2.1.9485.10 - NCUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AixHjqJQOPlAjnAlQtMysPw_aSJHAgAAAH5JJ9UOAAAA; expires=Sat, 02-Nov-2019 01:44:32 GMT; path=/; secure; HttpOnly; SameSite=None',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 03 Oct 2019 01:44:31 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .get('/certificates/mergeCertificateName-canmergeaselfsignedcertificate-/pending')
  .query(true)
  .reply(200, {"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeaselfsignedcertificate-/pending","issuer":{"name":"Unknown"},"csr":"MIICoTCCAYkCAQAwETEPMA0GA1UEAxMGTXlDZXJ0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA06bnm7Y+Rwv0p2iGvlaH/Iz1DXwVMF1GsmjqMGz/gQlkNt2KFHRPALnNxa18sIwvKDJ9OS5Qxd7PH/MKFkoErZewQT8/+HJu/vRoRtR9XX1+WFGKDDMzEXfbJcAMBvJBsXh90KI8EfqQ+DqM4O5WuKtz0+RWAYI1Xl4oMbm5GqLfugWzteW3Yroob9tzc8SOKwjbEc0lRZ3F6qpmII4ic9weiMYbWmH8abEpDA79RDpEjEshQUU3PU1i/diPXPDjU4UR/ybzNAGMvMAuQPm9pP4JA0DGfj7wUVvp95H9kde5ayU4+zz2qkrB7OfhIHd28t+pIqC5ZllaNV2lK3dJGQIDAQABoEswSQYJKoZIhvcNAQkOMTwwOjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggEBAKKqT1TaXp7UptXXoGBFifI7UvLQDI7B8YnDqm4U/4JvQCiM2RXcT0gejZ/dHDzXYHAcSOYzhjwtQNZm4GNg2fVgU3R7HLgT3cQtIpy0Ox0R6uBYtoWqMshttB3xJvKxLY2KG1Q560E6yTGmDs4uj2Lu15/arEXVOZp4e2GXUimk44seBBLpkailgXgdp0qA/m7/nlKRsAkLeeQp+Yqa7awmYPcsJF/AQCsuQI1xSwTXhmQLmRFtNp7voeQSb0rqY3Y/OxfpKWxqmoKcVmfsiuY7gXBdRIg5yBpKvpnLke0cNfBrzN6Dq1WePz8Xa/BIpAHDrSZZDFmalpDpkpEU8lQ=","cancellation_requested":false,"status":"inProgress","status_details":"Pending certificate created. Please Perform Merge to complete the request.","request_id":"1be9966d1fe34fc1b16df923204a436f"}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Retry-After',
  '10',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'a6c817b1-06b9-4e9c-8b04-9ca47a0a2d7d',
  'x-ms-keyvault-service-version',
  '1.1.0.878',
  'x-ms-keyvault-network-info',
  'addr=23.100.22.158;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 03 Oct 2019 01:44:32 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1270' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .post('/certificates/mergeCertificateName-canmergeaselfsignedcertificate-/pending/merge')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '996c89c9-7a99-4399-a355-a5f47a5a9344',
  'x-ms-keyvault-service-version',
  '1.1.0.878',
  'x-ms-keyvault-network-info',
  'addr=23.100.22.158;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 03 Oct 2019 01:44:32 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '910cb382-302b-4146-84aa-688bb6500b00',
  'x-ms-ests-server',
  '2.1.9485.10 - NCUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AixHjqJQOPlAjnAlQtMysPw_aSJHAwAAAH5JJ9UOAAAA; expires=Sat, 02-Nov-2019 01:44:32 GMT; path=/; secure; HttpOnly; SameSite=None',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 03 Oct 2019 01:44:32 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .post('/certificates/mergeCertificateName-canmergeaselfsignedcertificate-/pending/merge', {"x5c":["TUlJQzBqQ0NBYm9DQ1FDdldWdWMxOXF5RERBTkJna3Foa2lHOXcwQkFRc0ZBREJGTVFzd0NRWURWUVFHRXdKQlZURVRNQkVHQTFVRUNBd0tVMjl0WlMxVGRHRjBaVEVoTUI4R0ExVUVDZ3dZU1c1MFpYSnVaWFFnVjJsa1oybDBjeUJRZEhrZ1RIUmtNQjRYRFRFNU1UQXdNekF4TkRRek1sb1hEVEU1TVRFd01qQXhORFF6TWxvd0VURVBNQTBHQTFVRUF4TUdUWGxEWlhKME1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMDZibm03WStSd3YwcDJpR3ZsYUgvSXoxRFh3Vk1GMUdzbWpxTUd6L2dRbGtOdDJLRkhSUEFMbk54YTE4c0l3dktESjlPUzVReGQ3UEgvTUtGa29Fclpld1FUOC8rSEp1L3ZSb1J0UjlYWDErV0ZHS0RETXpFWGZiSmNBTUJ2SkJzWGg5MEtJOEVmcVErRHFNNE81V3VLdHowK1JXQVlJMVhsNG9NYm01R3FMZnVnV3p0ZVczWXJvb2I5dHpjOFNPS3dqYkVjMGxSWjNGNnFwbUlJNGljOXdlaU1ZYldtSDhhYkVwREE3OVJEcEVqRXNoUVVVM1BVMWkvZGlQWFBEalU0VVIveWJ6TkFHTXZNQXVRUG05cFA0SkEwREdmajd3VVZ2cDk1SDlrZGU1YXlVNCt6ejJxa3JCN09maElIZDI4dCtwSXFDNVpsbGFOVjJsSzNkSkdRSURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBTTc4SC9ZSjNzbG9pUGpZVzRZOE53QTA4Ty8wNEF2QXNxVTduVktJR2ROTlUwVkJvL3I1aWtIL1VQbnllZ2Rob3NrZ1dkSkVzRDg5MWw3Y2RITHBxMmhobVk3cWd1czM4V1IxMk82cFpieFhPTE12YmtRN25ad3FBanVtRVNlSC9XSGVRQ24rWTZNYU9zSFZSb2tya1htQ0o0MVVQVGtIVytiVlJDNE9kOW5PUWMvY21wVmwxaGE2NnF3cUhnU0JqOXV6SU5ldVBvQW1MREtubjNmZC9SU3VNN1QySUF1Zklqais4SmhEYmoxT0l2OVd2RlhaWS8yS2lxcm9UcEpLVkpCUlNqN0FiR2RHVUtUdm5jNmd3UW5ZU2hVS1JvRFFBdE1US2VVVXR3ZHJ6NXZWR2VDRWNidTIwL0RVQXBlYjRxU1BtODVsUHJUU2FMeG1TVkJzc1UtLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"]})
  .query(true)
  .reply(201, {"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeaselfsignedcertificate-/b2c1d3235cb74066a2377a5c5e8337e5","kid":"https://keyvault_name.vault.azure.net/keys/mergeCertificateName-canmergeaselfsignedcertificate-/b2c1d3235cb74066a2377a5c5e8337e5","sid":"https://keyvault_name.vault.azure.net/secrets/mergeCertificateName-canmergeaselfsignedcertificate-/b2c1d3235cb74066a2377a5c5e8337e5","x5t":"GJcHf9OeXZWG_lwORjbUqqJukQE","cer":"MIIC0jCCAboCCQCvWVuc19qyDDANBgkqhkiG9w0BAQsFADBFMQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMB4XDTE5MTAwMzAxNDQzMloXDTE5MTEwMjAxNDQzMlowETEPMA0GA1UEAxMGTXlDZXJ0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA06bnm7Y+Rwv0p2iGvlaH/Iz1DXwVMF1GsmjqMGz/gQlkNt2KFHRPALnNxa18sIwvKDJ9OS5Qxd7PH/MKFkoErZewQT8/+HJu/vRoRtR9XX1+WFGKDDMzEXfbJcAMBvJBsXh90KI8EfqQ+DqM4O5WuKtz0+RWAYI1Xl4oMbm5GqLfugWzteW3Yroob9tzc8SOKwjbEc0lRZ3F6qpmII4ic9weiMYbWmH8abEpDA79RDpEjEshQUU3PU1i/diPXPDjU4UR/ybzNAGMvMAuQPm9pP4JA0DGfj7wUVvp95H9kde5ayU4+zz2qkrB7OfhIHd28t+pIqC5ZllaNV2lK3dJGQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQAM78H/YJ3sloiPjYW4Y8NwA08O/04AvAsqU7nVKIGdNNU0VBo/r5ikH/UPnyegdhoskgWdJEsD891l7cdHLpq2hhmY7qgus38WR12O6pZbxXOLMvbkQ7nZwqAjumESeH/WHeQCn+Y6MaOsHVRokrkXmCJ41UPTkHW+bVRC4Od9nOQc/cmpVl1ha66qwqHgSBj9uzINeuPoAmLDKnn3fd/RSuM7T2IAufIjj+8JhDbj1OIv9WvFXZY/2KiqroTpJKVJBRSj7AbGdGUKTvnc6gwQnYShUKRoDQAtMTKeUUtwdrz5vVGeCEcbu20/DUApeb4qSPm85lPrTSaLxmSVBssU","attributes":{"enabled":true,"nbf":1570067072,"exp":1572659072,"created":1570067073,"updated":1570067073,"recoveryLevel":"Recoverable+Purgeable"},"policy":{"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeaselfsignedcertificate-/policy","key_props":{"exportable":true,"kty":"RSA","key_size":2048,"reuse_key":false},"secret_props":{"contentType":"application/x-pkcs12"},"x509_props":{"subject":"cn=MyCert","sans":{},"ekus":["1.3.6.1.5.5.7.3.1","1.3.6.1.5.5.7.3.2"],"key_usage":["digitalSignature","keyEncipherment"],"validity_months":12,"basic_constraints":{"ca":false}},"lifetime_actions":[{"trigger":{"lifetime_percentage":80},"action":{"action_type":"EmailContacts"}}],"issuer":{"name":"Unknown","cert_transparency":false},"attributes":{"enabled":true,"created":1570067071,"updated":1570067071}},"pending":{"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeaselfsignedcertificate-/pending"}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Location',
  'https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeaselfsignedcertificate-?api-version=7.0',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'bfb8d844-b5a9-49d9-8bf2-e84426c9a055',
  'x-ms-keyvault-service-version',
  '1.1.0.878',
  'x-ms-keyvault-network-info',
  'addr=23.100.22.158;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 03 Oct 2019 01:44:33 GMT',
  'Connection',
  'close',
  'Content-Length',
  '2471' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/certificates/mergeCertificateName-canmergeaselfsignedcertificate-')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '8f00e454-c8d1-499c-926a-95a768c4713e',
  'x-ms-keyvault-service-version',
  '1.1.0.878',
  'x-ms-keyvault-network-info',
  'addr=23.100.22.158;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 03 Oct 2019 01:44:33 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '8232d6e9-e5de-46b6-9a3d-b20c03fd0900',
  'x-ms-ests-server',
  '2.1.9485.10 - WUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AixHjqJQOPlAjnAlQtMysPw_aSJHBAAAAH5JJ9UOAAAA; expires=Sat, 02-Nov-2019 01:44:34 GMT; path=/; secure; HttpOnly; SameSite=None',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 03 Oct 2019 01:44:34 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/certificates/mergeCertificateName-canmergeaselfsignedcertificate-')
  .query(true)
  .reply(200, {"recoveryId":"https://keyvault_name.vault.azure.net/deletedcertificates/mergeCertificateName-canmergeaselfsignedcertificate-","deletedDate":1570067074,"scheduledPurgeDate":1577843074,"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeaselfsignedcertificate-/b2c1d3235cb74066a2377a5c5e8337e5","kid":"https://keyvault_name.vault.azure.net/keys/mergeCertificateName-canmergeaselfsignedcertificate-/b2c1d3235cb74066a2377a5c5e8337e5","sid":"https://keyvault_name.vault.azure.net/secrets/mergeCertificateName-canmergeaselfsignedcertificate-/b2c1d3235cb74066a2377a5c5e8337e5","x5t":"GJcHf9OeXZWG_lwORjbUqqJukQE","cer":"MIIC0jCCAboCCQCvWVuc19qyDDANBgkqhkiG9w0BAQsFADBFMQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMB4XDTE5MTAwMzAxNDQzMloXDTE5MTEwMjAxNDQzMlowETEPMA0GA1UEAxMGTXlDZXJ0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA06bnm7Y+Rwv0p2iGvlaH/Iz1DXwVMF1GsmjqMGz/gQlkNt2KFHRPALnNxa18sIwvKDJ9OS5Qxd7PH/MKFkoErZewQT8/+HJu/vRoRtR9XX1+WFGKDDMzEXfbJcAMBvJBsXh90KI8EfqQ+DqM4O5WuKtz0+RWAYI1Xl4oMbm5GqLfugWzteW3Yroob9tzc8SOKwjbEc0lRZ3F6qpmII4ic9weiMYbWmH8abEpDA79RDpEjEshQUU3PU1i/diPXPDjU4UR/ybzNAGMvMAuQPm9pP4JA0DGfj7wUVvp95H9kde5ayU4+zz2qkrB7OfhIHd28t+pIqC5ZllaNV2lK3dJGQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQAM78H/YJ3sloiPjYW4Y8NwA08O/04AvAsqU7nVKIGdNNU0VBo/r5ikH/UPnyegdhoskgWdJEsD891l7cdHLpq2hhmY7qgus38WR12O6pZbxXOLMvbkQ7nZwqAjumESeH/WHeQCn+Y6MaOsHVRokrkXmCJ41UPTkHW+bVRC4Od9nOQc/cmpVl1ha66qwqHgSBj9uzINeuPoAmLDKnn3fd/RSuM7T2IAufIjj+8JhDbj1OIv9WvFXZY/2KiqroTpJKVJBRSj7AbGdGUKTvnc6gwQnYShUKRoDQAtMTKeUUtwdrz5vVGeCEcbu20/DUApeb4qSPm85lPrTSaLxmSVBssU","attributes":{"enabled":true,"nbf":1570067072,"exp":1572659072,"created":1570067073,"updated":1570067073,"recoveryLevel":"Recoverable+Purgeable"},"policy":{"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeaselfsignedcertificate-/policy","key_props":{"exportable":true,"kty":"RSA","key_size":2048,"reuse_key":false},"secret_props":{"contentType":"application/x-pkcs12"},"x509_props":{"subject":"cn=MyCert","sans":{},"ekus":["1.3.6.1.5.5.7.3.1","1.3.6.1.5.5.7.3.2"],"key_usage":["digitalSignature","keyEncipherment"],"validity_months":12,"basic_constraints":{"ca":false}},"lifetime_actions":[{"trigger":{"lifetime_percentage":80},"action":{"action_type":"EmailContacts"}}],"issuer":{"name":"Unknown","cert_transparency":false},"attributes":{"enabled":true,"created":1570067071,"updated":1570067071}},"pending":{"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeaselfsignedcertificate-/pending"}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'd77903d7-e147-4bc3-a99e-3eb0b66f8018',
  'x-ms-keyvault-service-version',
  '1.1.0.878',
  'x-ms-keyvault-network-info',
  'addr=23.100.22.158;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 03 Oct 2019 01:44:34 GMT',
  'Connection',
  'close',
  'Content-Length',
  '2668' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canmergeaselfsignedcertificate-')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'dec1b5b7-3eef-45a4-bbf9-a3cde6a5356c',
  'x-ms-keyvault-service-version',
  '1.1.0.878',
  'x-ms-keyvault-network-info',
  'addr=23.100.22.158;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 03 Oct 2019 01:44:34 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '80af9a05-943a-4f52-a660-b5b199bc0a00',
  'x-ms-ests-server',
  '2.1.9485.10 - EUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AixHjqJQOPlAjnAlQtMysPw_aSJHBQAAAH5JJ9UOAAAA; expires=Sat, 02-Nov-2019 01:44:35 GMT; path=/; secure; HttpOnly; SameSite=None',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 03 Oct 2019 01:44:34 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canmergeaselfsignedcertificate-')
  .query(true)
  .reply(409, {"error":{"code":"Conflict","message":"Certificate is currently being deleted.","innererror":{"code":"ObjectIsBeingDeleted"}}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '126',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'ee68c59b-822f-4cb4-a14b-4096460ae0d4',
  'x-ms-keyvault-service-version',
  '1.1.0.878',
  'x-ms-keyvault-network-info',
  'addr=23.100.22.158;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 03 Oct 2019 01:44:35 GMT',
  'Connection',
  'close' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canmergeaselfsignedcertificate-')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '165450db-94cf-439d-8094-cd190c11c6ec',
  'x-ms-keyvault-service-version',
  '1.1.0.878',
  'x-ms-keyvault-network-info',
  'addr=23.100.22.158;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 03 Oct 2019 01:44:45 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  'f553380f-12d8-4357-aea1-50287d4c0d00',
  'x-ms-ests-server',
  '2.1.9485.10 - EUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AixHjqJQOPlAjnAlQtMysPw_aSJHBgAAAH5JJ9UOAAAA; expires=Sat, 02-Nov-2019 01:44:46 GMT; path=/; secure; HttpOnly; SameSite=None',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 03 Oct 2019 01:44:45 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canmergeaselfsignedcertificate-')
  .query(true)
  .reply(409, {"error":{"code":"Conflict","message":"Certificate is currently being deleted.","innererror":{"code":"ObjectIsBeingDeleted"}}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '126',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '871b2825-8b48-4a11-be80-08869a86b932',
  'x-ms-keyvault-service-version',
  '1.1.0.878',
  'x-ms-keyvault-network-info',
  'addr=23.100.22.158;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 03 Oct 2019 01:44:45 GMT',
  'Connection',
  'close' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canmergeaselfsignedcertificate-')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '1ab92bc9-52da-49f2-980b-7a645981d4cc',
  'x-ms-keyvault-service-version',
  '1.1.0.878',
  'x-ms-keyvault-network-info',
  'addr=23.100.22.158;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 03 Oct 2019 01:44:55 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '1e762c84-5169-4fde-9e0d-d0f960990b00',
  'x-ms-ests-server',
  '2.1.9485.10 - NCUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AixHjqJQOPlAjnAlQtMysPw_aSJHBwAAAH5JJ9UOAAAA; expires=Sat, 02-Nov-2019 01:44:56 GMT; path=/; secure; HttpOnly; SameSite=None',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 03 Oct 2019 01:44:56 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canmergeaselfsignedcertificate-')
  .query(true)
  .reply(204, "", [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'a91333c1-4cb6-47f8-a29d-b7f062d89d4b',
  'x-ms-keyvault-service-version',
  '1.1.0.878',
  'x-ms-keyvault-network-info',
  'addr=23.100.22.158;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 03 Oct 2019 01:44:56 GMT',
  'Connection',
  'close' ]);

