let nock = require('nock');

module.exports.testInfo = {"uniqueName":{},"newDate":{}}

nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .post('/certificates/mergeCertificateName-canimportacertificatefromabackup-0/create')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '847f67bc-6fbd-487e-bbc7-53b19ecdc08d',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:07 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  'ab7afc5c-212c-4734-91d7-f6be869c2600',
  'x-ms-ests-server',
  '2.1.9316.5 - WUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AuipUp-PMctFs4SEvtuvPfw_aSJHAQAAACNC-tQOAAAA; expires=Sat, 28-Sep-2019 22:01:08 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 29 Aug 2019 22:01:07 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .post('/certificates/mergeCertificateName-canimportacertificatefromabackup-0/create', {"policy":{"x509_props":{"subject":"cn=MyCert"},"issuer":{"name":"Self"}}})
  .query(true)
  .reply(202, {"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canimportacertificatefromabackup-0/pending","issuer":{"name":"Self"},"csr":"MIICoTCCAYkCAQAwETEPMA0GA1UEAxMGTXlDZXJ0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1VOoWd8BJBiuBmPGM/Vteb52z5icZWXAUsqy4jzVtlBMb4OzU7B8qw40Np65L7LCl6l5IgJFWAuTu3kIVJftJ6qx22DhAv8YEM/JtpAeN//p0IDi/H9OXEyTEKpOAFfq65xwHsc6q78aR+fWMKQbxvaQhJQW+zbBxFGxYKLHijDHmWSsIHkIFnJCNpQQD8OUav91J2i8lUijLJHxFesJQUfVCpmJPWIpU6n7aiesc0GeBcHUWFhfwg7N7grtSqg7Q2JyjMLHANLTXJekQ3kgKNXhZL2+ARzFy62+2Pl2M1CGyzvEjSmqCnA5e6wqoiteV0XXWSUYyDUL8wr1nXWX+wIDAQABoEswSQYJKoZIhvcNAQkOMTwwOjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggEBAK+j+rgdTSDFk1rArIhHVUSKDlYyokhEoqFww1neuIz7+0+H2n+FU1lGyw96yGIvIgr9QvJc3ybLOtbSoi+X0i7dAIy/7GLw+Q/DF/6iHPxebwDoKDxbF5lEVLfH63xzU9ctEf6BlDhODYU3EEHBy2AszTdY66bJ5Z7GbE8wba2dmP3BlHWmK32/N59SnpiC5xNYH2bZaxF1Rt8f0SZSFJXWMJNFke3m8POjbDkbKW/K7Q7fGJpt63H6PkEtHxT9WQSOM22kJvubFDqR9vC+7OzKUyDGBIMdUpNK5GeHOogpNOsmHbV9a0m8cs3GFmFw9TLGvfdmb7dPUeEY9P3Rr00=","cancellation_requested":false,"status":"inProgress","status_details":"Pending certificate created. Certificate request is in progress. This may take some time based on the issuer provider. Please check again later.","request_id":"311d33cbb3bd430ea52925b6f2cca28a"}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Location',
  'https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canimportacertificatefromabackup-0/pending?api-version=7.0&request_id=311d33cbb3bd430ea52925b6f2cca28a',
  'Retry-After',
  '10',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '2f5f999e-fcc7-449d-a0b3-3944f3bd964e',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:08 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1340' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .get('/secrets/mergeCertificateName-canimportacertificatefromabackup-0/')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'e1b86ed4-74ae-4430-86ba-0212f1c12b57',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:09 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  'bec668de-6e41-44c2-9ee7-69f192b50900',
  'x-ms-ests-server',
  '2.1.9316.5 - EUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AuipUp-PMctFs4SEvtuvPfw_aSJHAgAAACNC-tQOAAAA; expires=Sat, 28-Sep-2019 22:01:10 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 29 Aug 2019 22:01:09 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .get('/secrets/mergeCertificateName-canimportacertificatefromabackup-0/')
  .query(true)
  .reply(403, {"error":{"code":"Forbidden","message":"Operation get is not allowed on a disabled secret.","innererror":{"code":"SecretDisabled"}}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '132',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '88b76e7a-a708-4632-80d0-fc1ac5cedab8',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:09 GMT',
  'Connection',
  'close' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .get('/secrets/mergeCertificateName-canimportacertificatefromabackup-0/')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '128cefb0-5733-4a66-a138-69d74d7facb5',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:20 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  'd14d099b-bc90-42ea-93b9-99d797a90a00',
  'x-ms-ests-server',
  '2.1.9316.5 - EUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AuipUp-PMctFs4SEvtuvPfw_aSJHAwAAACNC-tQOAAAA; expires=Sat, 28-Sep-2019 22:01:20 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 29 Aug 2019 22:01:20 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .get('/secrets/mergeCertificateName-canimportacertificatefromabackup-0/')
  .query(true)
  .reply(200, {"value":"MIIKNAIBAzCCCfQGCSqGSIb3DQEHAaCCCeUEggnhMIIJ3TCCBhYGCSqGSIb3DQEHAaCCBgcEggYDMIIF/zCCBfsGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAgxAl4t90nOxQICB9AEggTYLoxJtKALtBfzWuWWNMRDWw27ZHK798iPWHa1BP9sOYC2bfUgi+9uSNon1FhopzSR9A3YA0BmavYEZlZ2BMLWeUTLod0/UY/SS2XEw/pfEoAfaxtFwW4GJweA8sN/UsDg4eWwB6+on2CSOxPCXfn9VrQ4x2JRcRoEYf/XSCeiU4d4zwwCD7ZVm3Tbq4MiG6HjoAQqPAbYRpRRi2IdKZhuaUyc8omahzQi3qAgPtJn17A/YLqVhTAkoLOPl4ch87y82tMpLsujO1UFhsPJMdVJCKb3WLJfRCFrqFr/+DMfPajfxJbqfQaZyjedSj/kmIlrGNAeK49xi1PZJmc4+80nnHOWk9xwqgNadGA5WelGF6jagAUIWeTJQaqI6lxr0PLEMITXSJ12cwrz0pw1q0LlS2PqHQiErsFdjjut+ipPz7muzMUqp7/gw32hMUD+crObrpTvtxYIX1KTksjGfLOfie1QXtLbmUSPNMdwtvST7kpugkfsbYeiSahTC4ggNY8TKKCrIVL0CQD1tT92QU8s352TT1M3HkqT3+zW4Ru09Ly5mhivkhGFXus0YTPCbG3AcChnDWeQvUao2i8oUU7vdrbPEZFVmJ6NCwpa/gYOYBXOL9RH2Yga0rM4hoAN9u1tbxU8guNdBJ0B14NhhtE1+KqF4bVyuwx1gIRbEw307uc1WTg0puku4aSsSyGzrjearQSEupq8yHCs/PV0WHihnkS6TOo2drtrcDh4jbuXFErE4uZsVaolP9AhdE7HRLeE+lkXio2xSwt+TxQVHvLIrWvk4LQcWNg6DUoSqkiSr30IfmRuD6Lfz869hbopvjMFPrEafNY5Fp1nPt5yR6rn0q6Cxeq+NyhS1gie9s/rHR6FcFaZ+idYSFJXM1Ovs2JmSiPiZDd7JyIhkHFnvBeB6a23rOb2Cg2RFu4xljw/ewedlqwtq4kfdTiAkYsivrtuFJKq4jJg74WFPV2D0W600jnojN0fWy7lZ5q0/CXy95lYwsj2UC54yoPReoWIhhbtJ+78NUDkt7YBbCEthWa7+A/EhDWfoUY80Dp16KQ7gSYQTGmv33u600gETdgMEQ1eWHORAxzuDmPci0JM7J70BfLabGOl+aAnN2LVdoaLaAyIHk6tG5hVDHJfRCOl2QJnW67Laysk876b6vKIdjcPGpGKBw+62dHyf8U7AqK7fdoGY63FZ6dOI+wEjcLEs6Csqz5mJHiJgnvZiv7g+cP57Awgy4TJIFaWiHPJJUjlwAwKakMgpcuNWpa6aPCLCqIcuu0R58u9l38HwxGjTAa1Mgx0ZoLrfcPlsHbY1f8kleLGHx3vQ3imRQa7TuJejB4Kx1NwcFDlXfjRuv4KYIGJIU+CiCTwF6LdbPZf0N+QLzQg/9fy4vZKV5IA9/3dtS1mHjNu1mPpUqnGwge52wtHANCodTmQGjcllINl+p83H7sXLKHkWCaE3oVafkK9CE1L3QKyxo46Jfv4o2njXrEyBMBR2lyjnmWiMhRUDX4hxduVOqD08EoDyhQ2H9DEEzEljQpCFtHOrE/DXrH2dKMyb0YHtqkn7t2kSKMdtvFRgj8nLT9NlW7O1HFeK5v7JXoHCu3kBrGjLqOxIkjvHJuJjfiv2l0Ic5pqmH/2rSuWrz1vd4jkXhrnZDGB6TATBgkqhkiG9w0BCRUxBgQEAQAAADBXBgkqhkiG9w0BCRQxSh5IADEAOAA3AGMAMgA5ADAAYgAtADYANwAzADEALQA0AGMAZQBmAC0AOAA0ADkANAAtAGEAMgAxAGQAYgAxAGMANABiADUANABmMHkGCSsGAQQBgjcRATFsHmoATQBpAGMAcgBvAHMAbwBmAHQAIABFAG4AaABhAG4AYwBlAGQAIABSAFMAQQAgAGEAbgBkACAAQQBFAFMAIABDAHIAeQBwAHQAbwBnAHIAYQBwAGgAaQBjACAAUAByAG8AdgBpAGQAZQByMIIDvwYJKoZIhvcNAQcGoIIDsDCCA6wCAQAwggOlBgkqhkiG9w0BBwEwHAYKKoZIhvcNAQwBBjAOBAjR8+4Do9pKpQICB9CAggN4byR4Nttzw9QnmGJE72IODr3dURV46nC9kuaIxC7ojO/INumSAoiIW+xKY5+lBwtAE+1/u+yY6XwCMQ4n3L+DUKNycOpl7JYOFinlCYKT9zSCoGKV3c4PMl3bVEWBHvf1g88+CGih91Q37EWKo3uzoqL3Um13J4IStvrtYDBdYjIU4ASWyXcIEduGxSDEMuL5suSPm4nJUsvaXd/bq4Z2scfHscQXzWgW0wEw5B6ZBOFl2+uLS+M20oHf0kz/9CAcRm1LeXPDIOk8v0Wg55Z9UrFTmcCJNpMm6X1rVV0osoTB9T1YDAHCgQkuThCO6kWJWFc24vNHJ0sPWmM+uVXvb8Y60WWNRxWOh6qc2VwibfbKVnqupKqQEHdfq2B3sYOwvv/HOgIU9/ODZ/DDJYXZP/RjdiIa+zBexxDeOHiw5m1bvmypvbWzKbu49pkKfnYyHLGFsOrINlGmy+Fa+P5j0dprWRnWq0hYqmfo834ObTjHu3Ygz1Ay6Z3nWlBfVH5+DWbM/AwB8AdVQ5XPG/NJISeGSOPgwEzPo6Q2VXrabV6ZBmlAFTkIsn9mBH7xiH80rzRjq2fw2rpCXd6wwlVRAHv4CSoglsDMOKzFkERYvLlQgTRYAwcKaJyhtXhVWYPAI/1P5ueas/LiRAefFHla4qV0011t4FGbjt97hRaUMgB/W1o66NYIvFGU1Xwp1kMFMWy66yZ+uzWJ0ZUgX4HRgeyjGxuObmzHq6T2l2LPkxhfW4HgwXuYxGgTcX8r2mZwvagfK9IVWnIw1oSTLJ/4Edv5o2qqD6NTGZNTghMKx1+WfGbm5fXTXReNzWonqNFiB2WNy4N+oI9ldSFc10LGzSTiocvuiIpJVYkm3fQcW5hhhIvaVk2VavJ5DwjSmEqgWMCIwgPqToDh3UXgTPn/C87vOmAE09vC6Yx+DnxBT+eynh5B03gTwQYbl6lVhPDS8+5vePZFIeb7e8CSG39lgdRDt6RHJuAqtUfZoIWM4lBMdwYGWqFjmDUKh9glSZgP/58jdRsQUzD0K6P5TU18X94PI7K3dBpVyOsyhMFZelyrdXHrSke0C9vxNHK255CnE4p7r90/w9aUUZB8fzBche9xL0apBIUYeSgqC5FtJpd4yi5LwikyDS87l/AO/XXS7T3+YbXQ+2HnvUXS4nlYbxUGxX5ZCEesMDcwHzAHBgUrDgMCGgQUwA176SBKBiASudxPwf9M0jPurRgEFP93AOowhsajzGp+C0k4t0mFZDN2","contentType":"application/x-pkcs12","id":"https://keyvault_name.vault.azure.net/secrets/mergeCertificateName-canimportacertificatefromabackup-0/48a5c64a1ecc4640904b08f3ed000482","managed":true,"attributes":{"enabled":true,"nbf":1567115478,"exp":1598738478,"created":1567116078,"updated":1567116078,"recoveryLevel":"Recoverable+Purgeable"},"kid":"https://keyvault_name.vault.azure.net/keys/mergeCertificateName-canimportacertificatefromabackup-0/48a5c64a1ecc4640904b08f3ed000482"}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '1a59551f-d635-41c5-a718-64fbe41d12d1',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:20 GMT',
  'Connection',
  'close',
  'Content-Length',
  '4008' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .post('/certificates/mergeCertificateName-canimportacertificatefromabackup-1/import')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'ebf46221-bd2f-477e-a8df-8fc6fbda53d2',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:21 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3599,"ext_expires_in":3599,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '5daa754e-a93b-4486-947c-0a86e27a0900',
  'x-ms-ests-server',
  '2.1.9316.5 - NCUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AuipUp-PMctFs4SEvtuvPfw_aSJHBAAAACNC-tQOAAAA; expires=Sat, 28-Sep-2019 22:01:21 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 29 Aug 2019 22:01:21 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .post('/certificates/mergeCertificateName-canimportacertificatefromabackup-1/import', {"value":"MIIKNAIBAzCCCfQGCSqGSIb3DQEHAaCCCeUEggnhMIIJ3TCCBhYGCSqGSIb3DQEHAaCCBgcEggYDMIIF/zCCBfsGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAgxAl4t90nOxQICB9AEggTYLoxJtKALtBfzWuWWNMRDWw27ZHK798iPWHa1BP9sOYC2bfUgi+9uSNon1FhopzSR9A3YA0BmavYEZlZ2BMLWeUTLod0/UY/SS2XEw/pfEoAfaxtFwW4GJweA8sN/UsDg4eWwB6+on2CSOxPCXfn9VrQ4x2JRcRoEYf/XSCeiU4d4zwwCD7ZVm3Tbq4MiG6HjoAQqPAbYRpRRi2IdKZhuaUyc8omahzQi3qAgPtJn17A/YLqVhTAkoLOPl4ch87y82tMpLsujO1UFhsPJMdVJCKb3WLJfRCFrqFr/+DMfPajfxJbqfQaZyjedSj/kmIlrGNAeK49xi1PZJmc4+80nnHOWk9xwqgNadGA5WelGF6jagAUIWeTJQaqI6lxr0PLEMITXSJ12cwrz0pw1q0LlS2PqHQiErsFdjjut+ipPz7muzMUqp7/gw32hMUD+crObrpTvtxYIX1KTksjGfLOfie1QXtLbmUSPNMdwtvST7kpugkfsbYeiSahTC4ggNY8TKKCrIVL0CQD1tT92QU8s352TT1M3HkqT3+zW4Ru09Ly5mhivkhGFXus0YTPCbG3AcChnDWeQvUao2i8oUU7vdrbPEZFVmJ6NCwpa/gYOYBXOL9RH2Yga0rM4hoAN9u1tbxU8guNdBJ0B14NhhtE1+KqF4bVyuwx1gIRbEw307uc1WTg0puku4aSsSyGzrjearQSEupq8yHCs/PV0WHihnkS6TOo2drtrcDh4jbuXFErE4uZsVaolP9AhdE7HRLeE+lkXio2xSwt+TxQVHvLIrWvk4LQcWNg6DUoSqkiSr30IfmRuD6Lfz869hbopvjMFPrEafNY5Fp1nPt5yR6rn0q6Cxeq+NyhS1gie9s/rHR6FcFaZ+idYSFJXM1Ovs2JmSiPiZDd7JyIhkHFnvBeB6a23rOb2Cg2RFu4xljw/ewedlqwtq4kfdTiAkYsivrtuFJKq4jJg74WFPV2D0W600jnojN0fWy7lZ5q0/CXy95lYwsj2UC54yoPReoWIhhbtJ+78NUDkt7YBbCEthWa7+A/EhDWfoUY80Dp16KQ7gSYQTGmv33u600gETdgMEQ1eWHORAxzuDmPci0JM7J70BfLabGOl+aAnN2LVdoaLaAyIHk6tG5hVDHJfRCOl2QJnW67Laysk876b6vKIdjcPGpGKBw+62dHyf8U7AqK7fdoGY63FZ6dOI+wEjcLEs6Csqz5mJHiJgnvZiv7g+cP57Awgy4TJIFaWiHPJJUjlwAwKakMgpcuNWpa6aPCLCqIcuu0R58u9l38HwxGjTAa1Mgx0ZoLrfcPlsHbY1f8kleLGHx3vQ3imRQa7TuJejB4Kx1NwcFDlXfjRuv4KYIGJIU+CiCTwF6LdbPZf0N+QLzQg/9fy4vZKV5IA9/3dtS1mHjNu1mPpUqnGwge52wtHANCodTmQGjcllINl+p83H7sXLKHkWCaE3oVafkK9CE1L3QKyxo46Jfv4o2njXrEyBMBR2lyjnmWiMhRUDX4hxduVOqD08EoDyhQ2H9DEEzEljQpCFtHOrE/DXrH2dKMyb0YHtqkn7t2kSKMdtvFRgj8nLT9NlW7O1HFeK5v7JXoHCu3kBrGjLqOxIkjvHJuJjfiv2l0Ic5pqmH/2rSuWrz1vd4jkXhrnZDGB6TATBgkqhkiG9w0BCRUxBgQEAQAAADBXBgkqhkiG9w0BCRQxSh5IADEAOAA3AGMAMgA5ADAAYgAtADYANwAzADEALQA0AGMAZQBmAC0AOAA0ADkANAAtAGEAMgAxAGQAYgAxAGMANABiADUANABmMHkGCSsGAQQBgjcRATFsHmoATQBpAGMAcgBvAHMAbwBmAHQAIABFAG4AaABhAG4AYwBlAGQAIABSAFMAQQAgAGEAbgBkACAAQQBFAFMAIABDAHIAeQBwAHQAbwBnAHIAYQBwAGgAaQBjACAAUAByAG8AdgBpAGQAZQByMIIDvwYJKoZIhvcNAQcGoIIDsDCCA6wCAQAwggOlBgkqhkiG9w0BBwEwHAYKKoZIhvcNAQwBBjAOBAjR8+4Do9pKpQICB9CAggN4byR4Nttzw9QnmGJE72IODr3dURV46nC9kuaIxC7ojO/INumSAoiIW+xKY5+lBwtAE+1/u+yY6XwCMQ4n3L+DUKNycOpl7JYOFinlCYKT9zSCoGKV3c4PMl3bVEWBHvf1g88+CGih91Q37EWKo3uzoqL3Um13J4IStvrtYDBdYjIU4ASWyXcIEduGxSDEMuL5suSPm4nJUsvaXd/bq4Z2scfHscQXzWgW0wEw5B6ZBOFl2+uLS+M20oHf0kz/9CAcRm1LeXPDIOk8v0Wg55Z9UrFTmcCJNpMm6X1rVV0osoTB9T1YDAHCgQkuThCO6kWJWFc24vNHJ0sPWmM+uVXvb8Y60WWNRxWOh6qc2VwibfbKVnqupKqQEHdfq2B3sYOwvv/HOgIU9/ODZ/DDJYXZP/RjdiIa+zBexxDeOHiw5m1bvmypvbWzKbu49pkKfnYyHLGFsOrINlGmy+Fa+P5j0dprWRnWq0hYqmfo834ObTjHu3Ygz1Ay6Z3nWlBfVH5+DWbM/AwB8AdVQ5XPG/NJISeGSOPgwEzPo6Q2VXrabV6ZBmlAFTkIsn9mBH7xiH80rzRjq2fw2rpCXd6wwlVRAHv4CSoglsDMOKzFkERYvLlQgTRYAwcKaJyhtXhVWYPAI/1P5ueas/LiRAefFHla4qV0011t4FGbjt97hRaUMgB/W1o66NYIvFGU1Xwp1kMFMWy66yZ+uzWJ0ZUgX4HRgeyjGxuObmzHq6T2l2LPkxhfW4HgwXuYxGgTcX8r2mZwvagfK9IVWnIw1oSTLJ/4Edv5o2qqD6NTGZNTghMKx1+WfGbm5fXTXReNzWonqNFiB2WNy4N+oI9ldSFc10LGzSTiocvuiIpJVYkm3fQcW5hhhIvaVk2VavJ5DwjSmEqgWMCIwgPqToDh3UXgTPn/C87vOmAE09vC6Yx+DnxBT+eynh5B03gTwQYbl6lVhPDS8+5vePZFIeb7e8CSG39lgdRDt6RHJuAqtUfZoIWM4lBMdwYGWqFjmDUKh9glSZgP/58jdRsQUzD0K6P5TU18X94PI7K3dBpVyOsyhMFZelyrdXHrSke0C9vxNHK255CnE4p7r90/w9aUUZB8fzBche9xL0apBIUYeSgqC5FtJpd4yi5LwikyDS87l/AO/XXS7T3+YbXQ+2HnvUXS4nlYbxUGxX5ZCEesMDcwHzAHBgUrDgMCGgQUwA176SBKBiASudxPwf9M0jPurRgEFP93AOowhsajzGp+C0k4t0mFZDN2"})
  .query(true)
  .reply(200, {"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canimportacertificatefromabackup-1/370f3051f275465fb0181df10d179b81","kid":"https://keyvault_name.vault.azure.net/keys/mergeCertificateName-canimportacertificatefromabackup-1/370f3051f275465fb0181df10d179b81","sid":"https://keyvault_name.vault.azure.net/secrets/mergeCertificateName-canimportacertificatefromabackup-1/370f3051f275465fb0181df10d179b81","x5t":"F7vnmyK18E9ECIUpe1hlumixbU8","cer":"MIIDKDCCAhCgAwIBAgIQBg4wiN3ORUmrWRt4/gHPozANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDEwZNeUNlcnQwHhcNMTkwODI5MjE1MTE4WhcNMjAwODI5MjIwMTE4WjARMQ8wDQYDVQQDEwZNeUNlcnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDVU6hZ3wEkGK4GY8Yz9W15vnbPmJxlZcBSyrLiPNW2UExvg7NTsHyrDjQ2nrkvssKXqXkiAkVYC5O7eQhUl+0nqrHbYOEC/xgQz8m2kB43/+nQgOL8f05cTJMQqk4AV+rrnHAexzqrvxpH59YwpBvG9pCElBb7NsHEUbFgoseKMMeZZKwgeQgWckI2lBAPw5Rq/3UnaLyVSKMskfEV6wlBR9UKmYk9YilTqftqJ6xzQZ4FwdRYWF/CDs3uCu1KqDtDYnKMwscA0tNcl6RDeSAo1eFkvb4BHMXLrb7Y+XYzUIbLO8SNKaoKcDl7rCqiK15XRddZJRjINQvzCvWddZf7AgMBAAGjfDB6MA4GA1UdDwEB/wQEAwIFoDAJBgNVHRMEAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAfBgNVHSMEGDAWgBSRzZ6Y7U8FobLDBQU1xjAlfunjQTAdBgNVHQ4EFgQUkc2emO1PBaGywwUFNcYwJX7p40EwDQYJKoZIhvcNAQELBQADggEBAM2+fGIbS7i+8BrAfBn2ZMUhmsxbYknKiwkE+6Yh2mc/9+Wdx7DqbcgFe4G/xNrSZEoVz/i9jJ6pO3lUw617TCzBqzacSGem2Cqdrc9LX3bPXqCDJkk1QVENogPTYxMt29zdRBTtBlyz/gybGf1b95eHdLd3sUQFVmwsxZtdvcsP0SW5LnaWgMSBQ3FOYVb1yiDrqz2E7BenGXJpsU5SA3IjxiGqCn2kizBNs3K16l6mZu1r23ZbBfehHbigz+EFirZ4bPaJGNAt5YuTPcMhr2+WHP03qJH9Zh/FC3kB6dbvUkC0K49uBNx3RutruBW7KzXej/JJ9yWd/Afj9x+v3Fg=","attributes":{"enabled":true,"nbf":1567115478,"exp":1598738478,"created":1567116081,"updated":1567116081,"recoveryLevel":"Recoverable+Purgeable"},"policy":{"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canimportacertificatefromabackup-1/policy","key_props":{"exportable":true,"kty":"RSA","key_size":2048,"reuse_key":false},"secret_props":{"contentType":"application/x-pkcs12"},"x509_props":{"subject":"CN=MyCert","ekus":["1.3.6.1.5.5.7.3.1","1.3.6.1.5.5.7.3.2"],"key_usage":["digitalSignature","keyEncipherment"],"validity_months":13,"basic_constraints":{"ca":false}},"lifetime_actions":[{"trigger":{"lifetime_percentage":80},"action":{"action_type":"EmailContacts"}}],"issuer":{"name":"Unknown"},"attributes":{"enabled":true,"created":1567116081,"updated":1567116081}}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'b20f49ed-44e1-4fdb-bb06-aafc453bbc4c',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:21 GMT',
  'Connection',
  'close',
  'Content-Length',
  '2418' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/certificates/mergeCertificateName-canimportacertificatefromabackup-0')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'ba8e051c-d70e-4c08-a715-0eba0051690f',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:22 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3599,"ext_expires_in":3599,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '1d8b59eb-e0dc-4b45-bdc6-ebde5f580800',
  'x-ms-ests-server',
  '2.1.9316.5 - NCUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AuipUp-PMctFs4SEvtuvPfw_aSJHBQAAACNC-tQOAAAA; expires=Sat, 28-Sep-2019 22:01:22 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 29 Aug 2019 22:01:22 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/certificates/mergeCertificateName-canimportacertificatefromabackup-0')
  .query(true)
  .reply(200, {"recoveryId":"https://keyvault_name.vault.azure.net/deletedcertificates/mergeCertificateName-canimportacertificatefromabackup-0","deletedDate":1567116083,"scheduledPurgeDate":1574892083,"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canimportacertificatefromabackup-0/48a5c64a1ecc4640904b08f3ed000482","kid":"https://keyvault_name.vault.azure.net/keys/mergeCertificateName-canimportacertificatefromabackup-0/48a5c64a1ecc4640904b08f3ed000482","sid":"https://keyvault_name.vault.azure.net/secrets/mergeCertificateName-canimportacertificatefromabackup-0/48a5c64a1ecc4640904b08f3ed000482","x5t":"F7vnmyK18E9ECIUpe1hlumixbU8","cer":"MIIDKDCCAhCgAwIBAgIQBg4wiN3ORUmrWRt4/gHPozANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDEwZNeUNlcnQwHhcNMTkwODI5MjE1MTE4WhcNMjAwODI5MjIwMTE4WjARMQ8wDQYDVQQDEwZNeUNlcnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDVU6hZ3wEkGK4GY8Yz9W15vnbPmJxlZcBSyrLiPNW2UExvg7NTsHyrDjQ2nrkvssKXqXkiAkVYC5O7eQhUl+0nqrHbYOEC/xgQz8m2kB43/+nQgOL8f05cTJMQqk4AV+rrnHAexzqrvxpH59YwpBvG9pCElBb7NsHEUbFgoseKMMeZZKwgeQgWckI2lBAPw5Rq/3UnaLyVSKMskfEV6wlBR9UKmYk9YilTqftqJ6xzQZ4FwdRYWF/CDs3uCu1KqDtDYnKMwscA0tNcl6RDeSAo1eFkvb4BHMXLrb7Y+XYzUIbLO8SNKaoKcDl7rCqiK15XRddZJRjINQvzCvWddZf7AgMBAAGjfDB6MA4GA1UdDwEB/wQEAwIFoDAJBgNVHRMEAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAfBgNVHSMEGDAWgBSRzZ6Y7U8FobLDBQU1xjAlfunjQTAdBgNVHQ4EFgQUkc2emO1PBaGywwUFNcYwJX7p40EwDQYJKoZIhvcNAQELBQADggEBAM2+fGIbS7i+8BrAfBn2ZMUhmsxbYknKiwkE+6Yh2mc/9+Wdx7DqbcgFe4G/xNrSZEoVz/i9jJ6pO3lUw617TCzBqzacSGem2Cqdrc9LX3bPXqCDJkk1QVENogPTYxMt29zdRBTtBlyz/gybGf1b95eHdLd3sUQFVmwsxZtdvcsP0SW5LnaWgMSBQ3FOYVb1yiDrqz2E7BenGXJpsU5SA3IjxiGqCn2kizBNs3K16l6mZu1r23ZbBfehHbigz+EFirZ4bPaJGNAt5YuTPcMhr2+WHP03qJH9Zh/FC3kB6dbvUkC0K49uBNx3RutruBW7KzXej/JJ9yWd/Afj9x+v3Fg=","attributes":{"enabled":true,"nbf":1567115478,"exp":1598738478,"created":1567116078,"updated":1567116078,"recoveryLevel":"Recoverable+Purgeable"},"policy":{"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canimportacertificatefromabackup-0/policy","key_props":{"exportable":true,"kty":"RSA","key_size":2048,"reuse_key":false},"secret_props":{"contentType":"application/x-pkcs12"},"x509_props":{"subject":"cn=MyCert","ekus":["1.3.6.1.5.5.7.3.1","1.3.6.1.5.5.7.3.2"],"key_usage":["digitalSignature","keyEncipherment"],"validity_months":12,"basic_constraints":{"ca":false}},"lifetime_actions":[{"trigger":{"lifetime_percentage":80},"action":{"action_type":"AutoRenew"}}],"issuer":{"name":"Self"},"attributes":{"enabled":true,"created":1567116069,"updated":1567116069}},"pending":{"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canimportacertificatefromabackup-0/pending"}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'd22e5057-76b9-4603-94a0-2dae331b0a79',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:22 GMT',
  'Connection',
  'close',
  'Content-Length',
  '2759' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canimportacertificatefromabackup-0')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '935dea71-811a-454c-804c-431b3e94b31b',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:22 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '1ce7accb-52e6-4e2b-84ad-adb9e74e2600',
  'x-ms-ests-server',
  '2.1.9316.5 - WUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AuipUp-PMctFs4SEvtuvPfw_aSJHBgAAACNC-tQOAAAA; expires=Sat, 28-Sep-2019 22:01:23 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 29 Aug 2019 22:01:23 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canimportacertificatefromabackup-0')
  .query(true)
  .reply(409, {"error":{"code":"Conflict","message":"Certificate is currently being deleted.","innererror":{"code":"ObjectIsBeingDeleted"}}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '126',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '7f1b4a02-e819-4ec2-ab86-8f263ec1debd',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:23 GMT',
  'Connection',
  'close' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canimportacertificatefromabackup-0')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'd5dcc8be-bfbd-45cf-89f8-12f7026b0720',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:33 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3599,"ext_expires_in":3599,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '82c4fbe2-dfb6-4ff2-a642-6db7ae1b2800',
  'x-ms-ests-server',
  '2.1.9316.5 - WUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AuipUp-PMctFs4SEvtuvPfw_aSJHBwAAACNC-tQOAAAA; expires=Sat, 28-Sep-2019 22:01:34 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 29 Aug 2019 22:01:34 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canimportacertificatefromabackup-0')
  .query(true)
  .reply(204, "", [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'b8a77479-950f-4263-b04b-a8d1ec07d6d7',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:34 GMT',
  'Connection',
  'close' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/certificates/mergeCertificateName-canimportacertificatefromabackup-1')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'd5d8336b-ad6c-45e9-af91-6fd8141b1f23',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:34 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '5367755d-62ab-4c88-80a9-7fb7fe480a00',
  'x-ms-ests-server',
  '2.1.9316.5 - EUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AuipUp-PMctFs4SEvtuvPfw_aSJHCAAAACNC-tQOAAAA; expires=Sat, 28-Sep-2019 22:01:35 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 29 Aug 2019 22:01:35 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/certificates/mergeCertificateName-canimportacertificatefromabackup-1')
  .query(true)
  .reply(200, {"recoveryId":"https://keyvault_name.vault.azure.net/deletedcertificates/mergeCertificateName-canimportacertificatefromabackup-1","deletedDate":1567116095,"scheduledPurgeDate":1574892095,"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canimportacertificatefromabackup-1/370f3051f275465fb0181df10d179b81","kid":"https://keyvault_name.vault.azure.net/keys/mergeCertificateName-canimportacertificatefromabackup-1/370f3051f275465fb0181df10d179b81","sid":"https://keyvault_name.vault.azure.net/secrets/mergeCertificateName-canimportacertificatefromabackup-1/370f3051f275465fb0181df10d179b81","x5t":"F7vnmyK18E9ECIUpe1hlumixbU8","cer":"MIIDKDCCAhCgAwIBAgIQBg4wiN3ORUmrWRt4/gHPozANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDEwZNeUNlcnQwHhcNMTkwODI5MjE1MTE4WhcNMjAwODI5MjIwMTE4WjARMQ8wDQYDVQQDEwZNeUNlcnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDVU6hZ3wEkGK4GY8Yz9W15vnbPmJxlZcBSyrLiPNW2UExvg7NTsHyrDjQ2nrkvssKXqXkiAkVYC5O7eQhUl+0nqrHbYOEC/xgQz8m2kB43/+nQgOL8f05cTJMQqk4AV+rrnHAexzqrvxpH59YwpBvG9pCElBb7NsHEUbFgoseKMMeZZKwgeQgWckI2lBAPw5Rq/3UnaLyVSKMskfEV6wlBR9UKmYk9YilTqftqJ6xzQZ4FwdRYWF/CDs3uCu1KqDtDYnKMwscA0tNcl6RDeSAo1eFkvb4BHMXLrb7Y+XYzUIbLO8SNKaoKcDl7rCqiK15XRddZJRjINQvzCvWddZf7AgMBAAGjfDB6MA4GA1UdDwEB/wQEAwIFoDAJBgNVHRMEAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAfBgNVHSMEGDAWgBSRzZ6Y7U8FobLDBQU1xjAlfunjQTAdBgNVHQ4EFgQUkc2emO1PBaGywwUFNcYwJX7p40EwDQYJKoZIhvcNAQELBQADggEBAM2+fGIbS7i+8BrAfBn2ZMUhmsxbYknKiwkE+6Yh2mc/9+Wdx7DqbcgFe4G/xNrSZEoVz/i9jJ6pO3lUw617TCzBqzacSGem2Cqdrc9LX3bPXqCDJkk1QVENogPTYxMt29zdRBTtBlyz/gybGf1b95eHdLd3sUQFVmwsxZtdvcsP0SW5LnaWgMSBQ3FOYVb1yiDrqz2E7BenGXJpsU5SA3IjxiGqCn2kizBNs3K16l6mZu1r23ZbBfehHbigz+EFirZ4bPaJGNAt5YuTPcMhr2+WHP03qJH9Zh/FC3kB6dbvUkC0K49uBNx3RutruBW7KzXej/JJ9yWd/Afj9x+v3Fg=","attributes":{"enabled":true,"nbf":1567115478,"exp":1598738478,"created":1567116081,"updated":1567116081,"recoveryLevel":"Recoverable+Purgeable"},"policy":{"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canimportacertificatefromabackup-1/policy","key_props":{"exportable":true,"kty":"RSA","key_size":2048,"reuse_key":false},"secret_props":{"contentType":"application/x-pkcs12"},"x509_props":{"subject":"CN=MyCert","ekus":["1.3.6.1.5.5.7.3.1","1.3.6.1.5.5.7.3.2"],"key_usage":["digitalSignature","keyEncipherment"],"validity_months":13,"basic_constraints":{"ca":false}},"lifetime_actions":[{"trigger":{"lifetime_percentage":80},"action":{"action_type":"EmailContacts"}}],"issuer":{"name":"Unknown"},"attributes":{"enabled":true,"created":1567116081,"updated":1567116081}}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'c37c9eb6-2a62-44dd-907b-35ec2a116330',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:35 GMT',
  'Connection',
  'close',
  'Content-Length',
  '2618' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canimportacertificatefromabackup-1')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '8ddb247c-3ecd-49da-89fe-40c3cfe9e74e',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:36 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  'ecf8ae77-3ae5-4d6e-8cac-591b2e650500',
  'x-ms-ests-server',
  '2.1.9316.5 - SCUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AuipUp-PMctFs4SEvtuvPfw_aSJHCQAAACNC-tQOAAAA; expires=Sat, 28-Sep-2019 22:01:36 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 29 Aug 2019 22:01:36 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canimportacertificatefromabackup-1')
  .query(true)
  .reply(409, {"error":{"code":"Conflict","message":"Certificate is currently being deleted.","innererror":{"code":"ObjectIsBeingDeleted"}}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '126',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '65d9569c-9612-4341-a7dc-95f2f48bbee4',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:35 GMT',
  'Connection',
  'close' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canimportacertificatefromabackup-1')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '1980a228-3b8c-43b9-8411-ed75bc62cf8f',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:46 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '096df083-d282-4a0b-b6f2-3e66cd3d0900',
  'x-ms-ests-server',
  '2.1.9316.5 - NCUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AuipUp-PMctFs4SEvtuvPfw_aSJHCgAAACNC-tQOAAAA; expires=Sat, 28-Sep-2019 22:01:47 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 29 Aug 2019 22:01:47 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canimportacertificatefromabackup-1')
  .query(true)
  .reply(409, {"error":{"code":"Conflict","message":"Certificate is currently being deleted.","innererror":{"code":"ObjectIsBeingDeleted"}}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '126',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '0b5d963e-d658-477f-bf08-8b7062ca6105',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:47 GMT',
  'Connection',
  'close' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canimportacertificatefromabackup-1')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'c5b52d35-9ffc-4cb3-9fe8-5b6f91fce394',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:58 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3599,"ext_expires_in":3599,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '70fbc22e-a450-40fd-beab-d00bae2a0900',
  'x-ms-ests-server',
  '2.1.9316.5 - NCUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=AuipUp-PMctFs4SEvtuvPfw_aSJHCwAAACNC-tQOAAAA; expires=Sat, 28-Sep-2019 22:01:58 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Thu, 29 Aug 2019 22:01:58 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .delete('/deletedcertificates/mergeCertificateName-canimportacertificatefromabackup-1')
  .query(true)
  .reply(204, "", [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '3bb413e7-1aab-42e8-be5b-e8f10fc84eab',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=52.186.81.22;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Thu, 29 Aug 2019 22:01:58 GMT',
  'Connection',
  'close' ]);

