let nock = require('nock');

module.exports.testInfo = {"uniqueName":{},"newDate":{}}

nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .post('/certificates/mergeCertificateName-canmergeacertificate-0/create')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '245306d6-ccf9-4889-89d5-bffe7fffe21e',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=40.121.200.113;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Wed, 28 Aug 2019 01:53:14 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '84c31ed7-8ab2-40a5-93ce-c3c681631200',
  'x-ms-ests-server',
  '2.1.9288.15 - EUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=As6vWkNpBe5CjS4SxbywH5E_aSJHAQAAAIvV99QOAAAA; expires=Fri, 27-Sep-2019 01:53:15 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Wed, 28 Aug 2019 01:53:14 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .post('/certificates/mergeCertificateName-canmergeacertificate-0/create', {"policy":{"x509_props":{"subject":"cn=MyCert"},"issuer":{"name":"Self"}}})
  .query(true)
  .reply(202, {"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeacertificate-0/pending","issuer":{"name":"Self"},"csr":"MIICoTCCAYkCAQAwETEPMA0GA1UEAxMGTXlDZXJ0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwLr8piEcWeVaTJax+PlbmFVec48YDa+S8Tv+5icS0Iek9EpBAnD1YGYnpMgJiJQho6Ww26TOk352E/JcjbOwj1i8ZyEQuObsCuCoAWWKUUY42mcPHC0JSiEfu4TiIh4JxQA30I8zS+3RTSaSKT6XrDNlYJ3QKz1ddUix0gKeNa7sYPM3ibiPkVc4+pdy5ipV4JI8vvI7gz3mEx0hueOGaobttCG/NJGu5U/3V7Fa1KJTAtDLczsG6Qpnt66yOCAki7jNwX5tnwDhwgDfJ6Q+qVsl5B384KsOnM357FzSmj16wUSqQtDafH41eyPBdrouqb9qudxwKVrEeQSDGnIUiQIDAQABoEswSQYJKoZIhvcNAQkOMTwwOjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggEBACkD4rbIHDAzFspyLiUboOOvIwREQFG5eOGgBAnY7vsGPujTOXdLLpwxsVctm1GG9Yn7Ma9dfzuS1YuRYy+qZ+JS+ZJHAwqMu13UdKxKutUCAUYpTJaE2kl5J62l0/lPwme+zZu9Tkj7yxWUrQiu5C1ep2WpVX0TQ9fcHrfmSYVjoG2CYy6W8i0RYZMegZau2ggowVp3z4/ayzoXrGBvpW79iTZ+0lo7g4oo9qOHJeoEJegssv8OuKPbCIKvMn9sUqoiV82tM0l/0muT5HJ8MhA1hQXX73XIACo0zJ9YFqzJkLlsSyp1U2CwsLQ7Lawxj7Cu9MWLfOLAkQTsGEWe2EM=","cancellation_requested":false,"status":"inProgress","status_details":"Pending certificate created. Certificate request is in progress. This may take some time based on the issuer provider. Please check again later.","request_id":"55201696821d427a8e2110fbec4d4cda"}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Location',
  'https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeacertificate-0/pending?api-version=7.0&request_id=55201696821d427a8e2110fbec4d4cda',
  'Retry-After',
  '10',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '5ba584a6-69b4-439c-bcab-61e48fa3efa4',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=40.121.200.113;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Wed, 28 Aug 2019 01:53:16 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1328' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .get('/certificates/mergeCertificateName-canmergeacertificate-0/pending')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '6fe7f318-0bdf-4e6c-b406-63914097b5c8',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=40.121.200.113;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Wed, 28 Aug 2019 01:53:16 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '5f4d87aa-91b4-4975-b76c-f9df81c01000',
  'x-ms-ests-server',
  '2.1.9288.15 - EUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=As6vWkNpBe5CjS4SxbywH5E_aSJHAgAAAIvV99QOAAAA; expires=Fri, 27-Sep-2019 01:53:17 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Wed, 28 Aug 2019 01:53:16 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .get('/certificates/mergeCertificateName-canmergeacertificate-0/pending')
  .query(true)
  .reply(200, {"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeacertificate-0/pending","issuer":{"name":"Self"},"csr":"MIICoTCCAYkCAQAwETEPMA0GA1UEAxMGTXlDZXJ0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwLr8piEcWeVaTJax+PlbmFVec48YDa+S8Tv+5icS0Iek9EpBAnD1YGYnpMgJiJQho6Ww26TOk352E/JcjbOwj1i8ZyEQuObsCuCoAWWKUUY42mcPHC0JSiEfu4TiIh4JxQA30I8zS+3RTSaSKT6XrDNlYJ3QKz1ddUix0gKeNa7sYPM3ibiPkVc4+pdy5ipV4JI8vvI7gz3mEx0hueOGaobttCG/NJGu5U/3V7Fa1KJTAtDLczsG6Qpnt66yOCAki7jNwX5tnwDhwgDfJ6Q+qVsl5B384KsOnM357FzSmj16wUSqQtDafH41eyPBdrouqb9qudxwKVrEeQSDGnIUiQIDAQABoEswSQYJKoZIhvcNAQkOMTwwOjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggEBACkD4rbIHDAzFspyLiUboOOvIwREQFG5eOGgBAnY7vsGPujTOXdLLpwxsVctm1GG9Yn7Ma9dfzuS1YuRYy+qZ+JS+ZJHAwqMu13UdKxKutUCAUYpTJaE2kl5J62l0/lPwme+zZu9Tkj7yxWUrQiu5C1ep2WpVX0TQ9fcHrfmSYVjoG2CYy6W8i0RYZMegZau2ggowVp3z4/ayzoXrGBvpW79iTZ+0lo7g4oo9qOHJeoEJegssv8OuKPbCIKvMn9sUqoiV82tM0l/0muT5HJ8MhA1hQXX73XIACo0zJ9YFqzJkLlsSyp1U2CwsLQ7Lawxj7Cu9MWLfOLAkQTsGEWe2EM=","cancellation_requested":false,"status":"inProgress","status_details":"Pending certificate created. Certificate request is in progress. This may take some time based on the issuer provider. Please check again later.","request_id":"55201696821d427a8e2110fbec4d4cda"}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Retry-After',
  '10',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '6e8e1f4c-6fb1-4340-bdcd-8fbddc11e94f',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=40.121.200.113;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Wed, 28 Aug 2019 01:53:17 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1328' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .post('/certificates/mergeCertificateName-canmergeacertificate-1/create')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '0a6414ac-8592-4db9-ab20-65b46e42a1ea',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=40.121.200.113;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Wed, 28 Aug 2019 01:53:17 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '2931c8ee-d80a-4a02-a4db-f49dfd660000',
  'x-ms-ests-server',
  '2.1.9288.15 - SCUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=As6vWkNpBe5CjS4SxbywH5E_aSJHAwAAAIvV99QOAAAA; expires=Fri, 27-Sep-2019 01:53:18 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Wed, 28 Aug 2019 01:53:17 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .post('/certificates/mergeCertificateName-canmergeacertificate-1/create', {"policy":{"key_props":{"exportable":true,"kty":"RSA","key_size":2048,"reuse_key":false},"secret_props":{"contentType":"application/x-pem-file"},"x509_props":{"subject":"CN=*.microsoft.com","sans":{"dns_names":["sdk.azure-int.net"]},"validity_months":24},"lifetime_actions":[{"trigger":{"lifetime_percentage":2},"action":{"action_type":"EmailContacts"}}],"issuer":{"name":"Unknown"}}})
  .query(true)
  .reply(202, {"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeacertificate-1/pending","issuer":{"name":"Unknown"},"csr":"MIICyDCCAbACAQAwGjEYMBYGA1UEAwwPKi5taWNyb3NvZnQuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxm/dYl9QDsuG5t4AlbcvRijfgosZt2/9FxsjbrtoYpsddQKeTjdPuEMan71kIu9YYej1Q3w3S4Ga249sBPfTOeflpkPSo298kwWQATvhCFNOrhA/wxtErP8dtD1+UCeMgU92ZXo5qPqrMGGWydYJCx/okcNF82EsApkx1NxL1xDwZHgSo16oygON+dfOWoYZVerzlyoj5tNbfo9S0GJl2Ady4/FKxFMr6B+ewF/LtPYZbGsDcmgP0iBN2YOHJh0nayybR93bPNyIQtSTmQgVLlGiHUce1XMYABcwgnSriEouEKcOG2/js4bcrbI4FMwZ6Y5qg7fdpjOdOGQoXh1lzQIDAQABoGkwZwYJKoZIhvcNAQkOMVowWDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMBwGA1UdEQQVMBOCEXNkay5henVyZS1pbnQubmV0MAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggEBAJFBC4mvpL5P3dZH4viDZwNKq4GfwKHJ0aaTBhrQzj/FngcT7LkScApof6in+Q/5MCPZSMRvCr0oa583HDgi3ZlcPol4P+Hpr7ovknM33vkUIU4PgqDZlNIu1U1Kk7R9yTiucF02ncKyDZzKwfjUYhbYi56ePr5TebEdG7hfIMZOQIiJdcuq6IwE1Cd/5KBEvsHVH74Ts/7MtG61G8oVsNBLA56u9f69gGrNTNsYTsYL8Cqfsid/A7SLANU1erCT9RLpYFiPjVEiEO6sqTt9myeaZABq+AqdndfW4JZtfe1jt1c54syfAZZFZjAZ8Hfh7n8dvKPDooyiDqH5iqc2Jfc=","cancellation_requested":false,"status":"inProgress","status_details":"Pending certificate created. Please Perform Merge to complete the request.","request_id":"c688b4d27a1945c19bc0cf7127b7a973"}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Location',
  'https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeacertificate-1/pending?api-version=7.0&request_id=c688b4d27a1945c19bc0cf7127b7a973',
  'Retry-After',
  '10',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'd416e357-527a-4e33-bc62-9838fc5bf9a7',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=40.121.200.113;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Wed, 28 Aug 2019 01:53:18 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1313' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .get('/certificates/mergeCertificateName-canmergeacertificate-1/pending')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '07802706-4ece-412a-9268-dcd9dac38b7f',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=40.121.200.113;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Wed, 28 Aug 2019 01:53:18 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  'a462a94c-c03f-4740-8b62-56aaf7490100',
  'x-ms-ests-server',
  '2.1.9288.15 - NCUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=As6vWkNpBe5CjS4SxbywH5E_aSJHBAAAAIvV99QOAAAA; expires=Fri, 27-Sep-2019 01:53:19 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Wed, 28 Aug 2019 01:53:19 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .get('/certificates/mergeCertificateName-canmergeacertificate-1/pending')
  .query(true)
  .reply(200, {"id":"https://keyvault_name.vault.azure.net/certificates/mergeCertificateName-canmergeacertificate-1/pending","issuer":{"name":"Unknown"},"csr":"MIICyDCCAbACAQAwGjEYMBYGA1UEAwwPKi5taWNyb3NvZnQuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxm/dYl9QDsuG5t4AlbcvRijfgosZt2/9FxsjbrtoYpsddQKeTjdPuEMan71kIu9YYej1Q3w3S4Ga249sBPfTOeflpkPSo298kwWQATvhCFNOrhA/wxtErP8dtD1+UCeMgU92ZXo5qPqrMGGWydYJCx/okcNF82EsApkx1NxL1xDwZHgSo16oygON+dfOWoYZVerzlyoj5tNbfo9S0GJl2Ady4/FKxFMr6B+ewF/LtPYZbGsDcmgP0iBN2YOHJh0nayybR93bPNyIQtSTmQgVLlGiHUce1XMYABcwgnSriEouEKcOG2/js4bcrbI4FMwZ6Y5qg7fdpjOdOGQoXh1lzQIDAQABoGkwZwYJKoZIhvcNAQkOMVowWDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMBwGA1UdEQQVMBOCEXNkay5henVyZS1pbnQubmV0MAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggEBAJFBC4mvpL5P3dZH4viDZwNKq4GfwKHJ0aaTBhrQzj/FngcT7LkScApof6in+Q/5MCPZSMRvCr0oa583HDgi3ZlcPol4P+Hpr7ovknM33vkUIU4PgqDZlNIu1U1Kk7R9yTiucF02ncKyDZzKwfjUYhbYi56ePr5TebEdG7hfIMZOQIiJdcuq6IwE1Cd/5KBEvsHVH74Ts/7MtG61G8oVsNBLA56u9f69gGrNTNsYTsYL8Cqfsid/A7SLANU1erCT9RLpYFiPjVEiEO6sqTt9myeaZABq+AqdndfW4JZtfe1jt1c54syfAZZFZjAZ8Hfh7n8dvKPDooyiDqH5iqc2Jfc=","cancellation_requested":false,"status":"inProgress","status_details":"Pending certificate created. Please Perform Merge to complete the request.","request_id":"c688b4d27a1945c19bc0cf7127b7a973"}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Retry-After',
  '10',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'b34d6845-0392-4744-9237-d6fa4547fc5f',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=40.121.200.113;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Wed, 28 Aug 2019 01:53:19 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1313' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .post('/keys/mergeCertificateName-canmergeacertificate-Key/create')
  .query(true)
  .reply(401, {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Length',
  '87',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'WWW-Authenticate',
  'Bearer authorization="https://login.windows.net/azure_tenant_id", resource="https://vault.azure.net"',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  '8695aac5-4504-45d4-bc89-04a7f2c9ce7b',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=40.121.200.113;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Wed, 28 Aug 2019 01:53:19 GMT',
  'Connection',
  'close' ]);


nock('https://login.microsoftonline.com:443', {"encodedQueryParams":true})
  .post('/azure_tenant_id/oauth2/v2.0/token', "response_type=token&grant_type=client_credentials&client_id=azure_client_id&client_secret=azure_client_secret&scope=https%3A%2F%2Fvault.azure.net%2F.default")
  .reply(200, {"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"access_token"}, [ 'Cache-Control',
  'no-cache, no-store',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'x-ms-request-id',
  '3e76fe56-123d-45c3-89c6-03181cab1200',
  'x-ms-ests-server',
  '2.1.9288.15 - EUS ProdSlices',
  'P3P',
  'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'Set-Cookie',
  'fpc=As6vWkNpBe5CjS4SxbywH5E_aSJHBQAAAIvV99QOAAAA; expires=Fri, 27-Sep-2019 01:53:20 GMT; path=/; secure; HttpOnly',
  'Set-Cookie',
  'x-ms-gateway-slice=estsfd; path=/; secure; HttpOnly',
  'Set-Cookie',
  'stsservicecookie=estsfd; path=/; secure; HttpOnly',
  'Date',
  'Wed, 28 Aug 2019 01:53:20 GMT',
  'Connection',
  'close',
  'Content-Length',
  '1231' ]);


nock('https://keyvault_name.vault.azure.net:443', {"encodedQueryParams":true})
  .post('/keys/mergeCertificateName-canmergeacertificate-Key/create', {"kty":"RSA","key_size":2048,"attributes":{}})
  .query(true)
  .reply(200, {"key":{"kid":"https://keyvault_name.vault.azure.net/keys/mergeCertificateName-canmergeacertificate-Key/e662f05375b843edb30c7ec032ef12b7","kty":"RSA","key_ops":["encrypt","decrypt","sign","verify","wrapKey","unwrapKey"],"n":"yYKtfCtQRtBSMDo41IyGwoej4aZdC-gzs4xnKxc30Y3CyAb_MuA6FX8HdFsdHe-WeOqJ3aCIaJkWjZOT0q7iB3sqUY55VBZkcOfvNn20KZB_Kiwrxd2RYDS0iylkiIfBQGuY2zS8omnRIiwUEW9QutVQ-QceclUcE8hMvFgvgDjgseN5_6dXsXHPhFyEhKvYzBmg04Vc-iZRnv0o7XEw5EsHRw-7AK6Mh9pfHjk5TnpwXwhc0e-HOJT7G3EsV-WfdKe5g4r26JytwW8umv7SQfqqkWIIG27cT_o8r8HDQBhU0N56XJ__VhllfxRWHwLUI5C507q8zmvDVcH5NaIyOQ","e":"AQAB"},"attributes":{"enabled":true,"created":1566957200,"updated":1566957200,"recoveryLevel":"Recoverable+Purgeable"}}, [ 'Cache-Control',
  'no-cache',
  'Pragma',
  'no-cache',
  'Content-Type',
  'application/json; charset=utf-8',
  'Expires',
  '-1',
  'Server',
  'Microsoft-IIS/10.0',
  'x-ms-keyvault-region',
  'westus',
  'x-ms-request-id',
  'c018f07a-206a-4167-ab84-57c8e9dd1b36',
  'x-ms-keyvault-service-version',
  '1.1.0.876',
  'x-ms-keyvault-network-info',
  'addr=40.121.200.113;act_addr_fam=InterNetwork;',
  'X-AspNet-Version',
  '4.0.30319',
  'X-Powered-By',
  'ASP.NET',
  'Strict-Transport-Security',
  'max-age=31536000;includeSubDomains',
  'X-Content-Type-Options',
  'nosniff',
  'Date',
  'Wed, 28 Aug 2019 01:53:20 GMT',
  'Connection',
  'close',
  'Content-Length',
  '707' ]);

