# warp.config.yml — @azure/web-pubsub-client build configuration

extends: ../../../warp.base.config.yml

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"

  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"

  - name: esm
    condition: import
    tsconfig: "./config/tsconfig.src.esm.json"

  - name: commonjs
    condition: require
    tsconfig: "./config/tsconfig.src.cjs.json"
    moduleType: commonjs
