# warp.config.yml — build configuration

exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/imageVersions": "./src/api/imageVersions/index.ts"
  "./api/subscriptionUsages": "./src/api/subscriptionUsages/index.ts"
  "./api/sku": "./src/api/sku/index.ts"
  "./api/resourceDetails": "./src/api/resourceDetails/index.ts"
  "./api/pools": "./src/api/pools/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "./config/tsconfig.src.browser.json"

  - name: esm
    condition: import
    tsconfig: "./config/tsconfig.src.esm.json"

  - name: commonjs
    condition: require
    tsconfig: "./config/tsconfig.src.cjs.json"
    moduleType: commonjs
