# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/mhsmPrivateEndpointConnections": "src/api/mhsmPrivateEndpointConnections/index.ts"
  "./api/mhsmRegions": "src/api/mhsmRegions/index.ts"
  "./api/mhsmPrivateLinkResources": "src/api/mhsmPrivateLinkResources/index.ts"
  "./api/privateLinkResources": "src/api/privateLinkResources/index.ts"
  "./api/managedHsmKeys": "src/api/managedHsmKeys/index.ts"
  "./api/keys": "src/api/keys/index.ts"
  "./api/secrets": "src/api/secrets/index.ts"
  "./api/managedHsms": "src/api/managedHsms/index.ts"
  "./api/privateEndpointConnections": "src/api/privateEndpointConnections/index.ts"
  "./api/vaults": "src/api/vaults/index.ts"
  "./api/operations": "src/api/operations/index.ts"
  "./models": "./src/models/index.ts"
