exports:
  "./package.json": "./package.json"
  ".": "./src/index.ts"
  "./api": "./src/api/index.ts"
  "./api/dedicatedHsm": "./src/api/dedicatedHsm/index.ts"
  "./api/cloudHsmClusterPrivateEndpointConnections": "./src/api/cloudHsmClusterPrivateEndpointConnections/index.ts"
  "./api/cloudHsmClusterRestoreStatus": "./src/api/cloudHsmClusterRestoreStatus/index.ts"
  "./api/cloudHsmClusterBackupStatus": "./src/api/cloudHsmClusterBackupStatus/index.ts"
  "./api/cloudHsmClusterPrivateLinkResources": "./src/api/cloudHsmClusterPrivateLinkResources/index.ts"
  "./api/privateEndpointConnections": "./src/api/privateEndpointConnections/index.ts"
  "./api/cloudHsmClusters": "./src/api/cloudHsmClusters/index.ts"
  "./api/operations": "./src/api/operations/index.ts"
  "./models": "./src/models/index.ts"

targets:
  - name: browser
    tsconfig: "../../../tsconfig.src.browser.json"
  - name: react-native
    tsconfig: "../../../tsconfig.src.react-native.json"
  - name: esm
    condition: import
    tsconfig: "../../../tsconfig.src.esm.json"
  - name: commonjs
    condition: require
    tsconfig: "../../../tsconfig.src.cjs.json"
    moduleType: commonjs
