/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { SimplePollerLike, OperationState } from "@azure/core-lro";
import {
  DatabaseMigrationsSqlVmGetOptionalParams,
  DatabaseMigrationsSqlVmGetResponse,
  DatabaseMigrationSqlVm,
  DatabaseMigrationsSqlVmCreateOrUpdateOptionalParams,
  DatabaseMigrationsSqlVmCreateOrUpdateResponse,
  MigrationOperationInput,
  DatabaseMigrationsSqlVmCancelOptionalParams,
  DatabaseMigrationsSqlVmCutoverOptionalParams,
} from "../models/index.js";

/** Interface representing a DatabaseMigrationsSqlVm. */
export interface DatabaseMigrationsSqlVm {
  /**
   * Retrieve the specified database migration for a given SQL VM.
   * @param resourceGroupName Name of the resource group that contains the resource. You can obtain this
   *                          value from the Azure Resource Manager API or the portal.
   * @param sqlVirtualMachineName
   * @param targetDbName The name of the target database.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    sqlVirtualMachineName: string,
    targetDbName: string,
    options?: DatabaseMigrationsSqlVmGetOptionalParams,
  ): Promise<DatabaseMigrationsSqlVmGetResponse>;
  /**
   * Create a new database migration to a given SQL VM.
   * @param resourceGroupName Name of the resource group that contains the resource. You can obtain this
   *                          value from the Azure Resource Manager API or the portal.
   * @param sqlVirtualMachineName
   * @param targetDbName The name of the target database.
   * @param parameters Details of SqlMigrationService resource.
   * @param options The options parameters.
   */
  beginCreateOrUpdate(
    resourceGroupName: string,
    sqlVirtualMachineName: string,
    targetDbName: string,
    parameters: DatabaseMigrationSqlVm,
    options?: DatabaseMigrationsSqlVmCreateOrUpdateOptionalParams,
  ): Promise<
    SimplePollerLike<
      OperationState<DatabaseMigrationsSqlVmCreateOrUpdateResponse>,
      DatabaseMigrationsSqlVmCreateOrUpdateResponse
    >
  >;
  /**
   * Create a new database migration to a given SQL VM.
   * @param resourceGroupName Name of the resource group that contains the resource. You can obtain this
   *                          value from the Azure Resource Manager API or the portal.
   * @param sqlVirtualMachineName
   * @param targetDbName The name of the target database.
   * @param parameters Details of SqlMigrationService resource.
   * @param options The options parameters.
   */
  beginCreateOrUpdateAndWait(
    resourceGroupName: string,
    sqlVirtualMachineName: string,
    targetDbName: string,
    parameters: DatabaseMigrationSqlVm,
    options?: DatabaseMigrationsSqlVmCreateOrUpdateOptionalParams,
  ): Promise<DatabaseMigrationsSqlVmCreateOrUpdateResponse>;
  /**
   * Stop in-progress database migration to SQL VM.
   * @param resourceGroupName Name of the resource group that contains the resource. You can obtain this
   *                          value from the Azure Resource Manager API or the portal.
   * @param sqlVirtualMachineName
   * @param targetDbName The name of the target database.
   * @param parameters Migration Operation Input
   * @param options The options parameters.
   */
  beginCancel(
    resourceGroupName: string,
    sqlVirtualMachineName: string,
    targetDbName: string,
    parameters: MigrationOperationInput,
    options?: DatabaseMigrationsSqlVmCancelOptionalParams,
  ): Promise<SimplePollerLike<OperationState<void>, void>>;
  /**
   * Stop in-progress database migration to SQL VM.
   * @param resourceGroupName Name of the resource group that contains the resource. You can obtain this
   *                          value from the Azure Resource Manager API or the portal.
   * @param sqlVirtualMachineName
   * @param targetDbName The name of the target database.
   * @param parameters Migration Operation Input
   * @param options The options parameters.
   */
  beginCancelAndWait(
    resourceGroupName: string,
    sqlVirtualMachineName: string,
    targetDbName: string,
    parameters: MigrationOperationInput,
    options?: DatabaseMigrationsSqlVmCancelOptionalParams,
  ): Promise<void>;
  /**
   * Initiate cutover for in-progress online database migration to SQL VM.
   * @param resourceGroupName Name of the resource group that contains the resource. You can obtain this
   *                          value from the Azure Resource Manager API or the portal.
   * @param sqlVirtualMachineName
   * @param targetDbName The name of the target database.
   * @param parameters Migration Operation Input
   * @param options The options parameters.
   */
  beginCutover(
    resourceGroupName: string,
    sqlVirtualMachineName: string,
    targetDbName: string,
    parameters: MigrationOperationInput,
    options?: DatabaseMigrationsSqlVmCutoverOptionalParams,
  ): Promise<SimplePollerLike<OperationState<void>, void>>;
  /**
   * Initiate cutover for in-progress online database migration to SQL VM.
   * @param resourceGroupName Name of the resource group that contains the resource. You can obtain this
   *                          value from the Azure Resource Manager API or the portal.
   * @param sqlVirtualMachineName
   * @param targetDbName The name of the target database.
   * @param parameters Migration Operation Input
   * @param options The options parameters.
   */
  beginCutoverAndWait(
    resourceGroupName: string,
    sqlVirtualMachineName: string,
    targetDbName: string,
    parameters: MigrationOperationInput,
    options?: DatabaseMigrationsSqlVmCutoverOptionalParams,
  ): Promise<void>;
}
