// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import { AzureClouds, AzureSupportedClouds } from "./static-helpers/cloudSettingHelpers.js";
import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { RecoveryServicesClient } from "./recoveryServicesClient.js";
export { restorePoller, type RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  type OperationResource,
  type ErrorModel,
  type ErrorAdditionalInfo,
  type CloudError,
  type Vault,
  type VaultProperties,
  type UpgradeDetails,
  KnownVaultUpgradeState,
  type VaultUpgradeState,
  KnownTriggerType,
  type TriggerType,
  type PrivateEndpointConnectionVaultProperties,
  type PrivateEndpointConnection,
  KnownProvisioningState,
  type ProvisioningState,
  type PrivateEndpoint,
  type PrivateLinkServiceConnectionState,
  KnownPrivateEndpointConnectionStatus,
  type PrivateEndpointConnectionStatus,
  KnownVaultSubResourceType,
  type VaultSubResourceType,
  KnownVaultPrivateEndpointState,
  type VaultPrivateEndpointState,
  type VaultPropertiesEncryption,
  type CmkKeyVaultProperties,
  type CmkKekIdentity,
  KnownInfrastructureEncryptionState,
  type InfrastructureEncryptionState,
  type VaultPropertiesMoveDetails,
  KnownResourceMoveState,
  type ResourceMoveState,
  KnownBackupStorageVersion,
  type BackupStorageVersion,
  KnownPublicNetworkAccess,
  type PublicNetworkAccess,
  type MonitoringSettings,
  type AzureMonitorAlertSettings,
  KnownAlertsState,
  type AlertsState,
  type ClassicAlertSettings,
  type RestoreSettings,
  type CrossSubscriptionRestoreSettings,
  KnownCrossSubscriptionRestoreState,
  type CrossSubscriptionRestoreState,
  type VaultPropertiesRedundancySettings,
  KnownStandardTierStorageRedundancy,
  type StandardTierStorageRedundancy,
  KnownCrossRegionRestore,
  type CrossRegionRestore,
  type SecuritySettings,
  type ImmutabilitySettings,
  KnownImmutabilityState,
  type ImmutabilityState,
  type SoftDeleteSettings,
  KnownSoftDeleteState,
  type SoftDeleteState,
  KnownEnhancedSecurityState,
  type EnhancedSecurityState,
  KnownMultiUserAuthorization,
  type MultiUserAuthorization,
  type SourceScanConfiguration,
  KnownState,
  type State,
  type AssociatedIdentity,
  KnownIdentityType,
  type IdentityType,
  KnownSecureScoreLevel,
  type SecureScoreLevel,
  KnownBcdrSecurityLevel,
  type BcdrSecurityLevel,
  type IdentityData,
  KnownResourceIdentityType,
  type ResourceIdentityType,
  type UserIdentity,
  type Sku,
  KnownSkuName,
  type SkuName,
  type TrackedResource,
  type Resource,
  type SystemData,
  KnownCreatedByType,
  type CreatedByType,
  type ClientDiscoveryValueForSingleApi,
  type ClientDiscoveryDisplay,
  type ClientDiscoveryForProperties,
  type ClientDiscoveryForServiceSpecification,
  type ClientDiscoveryForLogSpecification,
  type ErrorDetail,
  type PatchVault,
  type PatchTrackedResource,
  type ErrorResponse,
  type DeletedVault,
  type DeletedVaultProperties,
  type ProxyResource,
  type DeletedVaultUndeleteInput,
  type DeletedVaultUndeleteInputProperties,
  type PrivateLinkResource,
  type PrivateLinkResourceProperties,
  type CertificateRequest,
  type RawCertificateData,
  KnownAuthType,
  type AuthType,
  type VaultCertificateResponse,
  type ResourceCertificateDetails,
  type ResourceCertificateDetailsUnion,
  type ResourceCertificateAndAadDetails,
  type ResourceCertificateAndAcsDetails,
  type ReplicationUsage,
  type MonitoringSummary,
  type JobsSummary,
  type VaultUsage,
  KnownUsagesUnit,
  type UsagesUnit,
  type NameInfo,
  type VaultExtendedInfoResource,
  type VaultExtendedInfo,
  type CheckNameAvailabilityParameters,
  type CheckNameAvailabilityResult,
  type ResourceCapabilities,
  type CapabilitiesProperties,
  type DNSZone,
  type ResourceCapabilitiesBase,
  type CapabilitiesResponse,
  type CapabilitiesResponseProperties,
  type DNSZoneResponse,
  KnownVersions,
} from "./models/index.js";
export {
  type GetOperationResultOptionalParams,
  type GetOperationStatusOptionalParams,
  type RecoveryServicesClientOptionalParams,
} from "./api/index.js";
export {
  type DeletedVaultsGetOperationStatusOptionalParams,
  type DeletedVaultsUndeleteOptionalParams,
  type DeletedVaultsGetOptionalParams,
  type DeletedVaultsListBySubscriptionIdOptionalParams,
} from "./api/deletedVaults/index.js";
export { type OperationsListOptionalParams } from "./api/operations/index.js";
export {
  type PrivateLinkResourcesListOptionalParams,
  type PrivateLinkResourcesGetOptionalParams,
} from "./api/privateLinkResources/index.js";
export {
  type RecoveryServicesCapabilitiesOptionalParams,
  type RecoveryServicesCheckNameAvailabilityOptionalParams,
} from "./api/recoveryServices/index.js";
export { type RegisteredIdentitiesDeleteOptionalParams } from "./api/registeredIdentities/index.js";
export { type ReplicationUsagesListOptionalParams } from "./api/replicationUsages/index.js";
export { type UsagesListByVaultsOptionalParams } from "./api/usages/index.js";
export { type VaultCertificatesCreateOptionalParams } from "./api/vaultCertificates/index.js";
export {
  type VaultExtendedInfoUpdateOptionalParams,
  type VaultExtendedInfoCreateOrUpdateOptionalParams,
  type VaultExtendedInfoGetOptionalParams,
} from "./api/vaultExtendedInfo/index.js";
export {
  type VaultsListByResourceGroupOptionalParams,
  type VaultsListBySubscriptionIdOptionalParams,
  type VaultsDeleteOptionalParams,
  type VaultsUpdateOptionalParams,
  type VaultsCreateOrUpdateOptionalParams,
  type VaultsGetOptionalParams,
} from "./api/vaults/index.js";
export {
  type DeletedVaultsOperations,
  type OperationsOperations,
  type PrivateLinkResourcesOperations,
  type RecoveryServicesOperations,
  type RegisteredIdentitiesOperations,
  type ReplicationUsagesOperations,
  type UsagesOperations,
  type VaultCertificatesOperations,
  type VaultExtendedInfoOperations,
  type VaultsOperations,
} from "./classic/index.js";
export { type PageSettings, type ContinuablePage, type PagedAsyncIterableIterator };
export { AzureClouds, type AzureSupportedClouds };
