# warp.config.yml — build configuration

extends: ../../../warp.base.config.yml

exports:
  "./api": "./src/api/index.ts"
  "./api/tenantActivityLogAlerts": "src/api/tenantActivityLogAlerts/index.ts"
  "./models": "./src/models/index.ts"
